WITH
	ADMTDEPT     AS 
	(	SELECT
			HAR.HSP_ACCOUNT_ID,
			DEP.DEPARTMENT_NAME,
			DEP.REV_LOC_ID 
		FROM
			HSP_ACCOUNT HAR 
			LEFT OUTER JOIN (	SELECT
									MAX(ADT.EVENT_ID) EVENT_ID,
									ADT.PAT_ENC_CSN_ID 
								FROM
									CLARITY_ADT ADT 
								WHERE
									ADT.EVENT_SUBTYPE_C <> 2 AND
									ADT.EVENT_TYPE_C = 1 
								GROUP BY
									ADT.PAT_ENC_CSN_ID) ADT_ONE 
			ON ADT_ONE.PAT_ENC_CSN_ID = HAR.PRIM_ENC_CSN_ID 
			LEFT OUTER JOIN CLARITY_ADT ADT_TWO 
			ON ADT_TWO.EVENT_ID = ADT_ONE.EVENT_ID 
			LEFT OUTER JOIN CLARITY_DEP DEP 
			ON DEP.DEPARTMENT_ID = ADT_TWO.DEPARTMENT_ID 
			LEFT OUTER JOIN HSP_ACCT_LAST_UPDATE LASTUP 
			ON LASTUP.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID 
		WHERE
			HAR.HSP_ACCOUNT_ID IS NOT NULL AND
			TO_DATE(LASTUP.INST_OF_UPDATE_DTTM, 'DD/MM/YYYY') BETWEEN TO_DATE(SYSDATE - 3, 'DD/MM/YYYY') AND
			TO_DATE(SYSDATE - 1, 'DD/MM/YYYY') AND
			DEP.DEPARTMENT_ID IS NOT NULL 
		GROUP BY
			HAR.HSP_ACCOUNT_ID,
			DEP.DEPARTMENT_NAME,
			DEP.REV_LOC_ID),
	BKT          AS 
	(	SELECT
			HLB.HSP_ACCOUNT_ID,
			HLB.BENEFIT_PLAN_ID,
			ZFC.INTERNAL_ID,
			ZFC.FINANCIAL_CLASS,
			MAXBKTID.BKTID 
		FROM
			HSP_BUCKET HLB 
			LEFT OUTER JOIN (	SELECT
									MAXBKT.HSP_ACCOUNT_ID,
									MAX(MAXBKT.BUCKET_ID) BKTID 
								FROM
									HSP_BUCKET MAXBKT 
								WHERE
									MAXBKT.BKT_TYPE_HA_C IN ('2',
									'3',
									'6',
									'7') 
								GROUP BY
									MAXBKT.HSP_ACCOUNT_ID) MAXBKTID 
			ON MAXBKTID.BKTID = HLB.BUCKET_ID 
			LEFT OUTER JOIN CLARITY_EPM EPM 
			ON EPM.PAYOR_ID = HLB.PAYOR_ID 
			LEFT OUTER JOIN ZC_FINANCIAL_CLASS ZFC 
			ON ZFC.FINANCIAL_CLASS = EPM.FINANCIAL_CLASS 
			LEFT OUTER JOIN HSP_ACCT_LAST_UPDATE LASTUP 
			ON LASTUP.HSP_ACCOUNT_ID = HLB.HSP_ACCOUNT_ID 
		WHERE
			MAXBKTID.BKTID IS NOT NULL AND
			TO_DATE(LASTUP.INST_OF_UPDATE_DTTM, 'DD/MM/YYYY') BETWEEN TO_DATE(SYSDATE - 3, 'DD/MM/YYYY') AND
			TO_DATE(SYSDATE - 1, 'DD/MM/YYYY') AND
			HLB.BKT_TYPE_HA_C IN ('2',
			'3',
			'6',
			'7')),
	CLMBKT       AS 
	(	SELECT
			HLB.HSP_ACCOUNT_ID,
			MAX(TO_CHAR(TRUNC(HLB.FST_EXT_CLM_SENT_DT), 'mm/dd/yyyy')) CLMDATE,
			MAX(TO_CHAR(TRUNC(HLB.FIRST_CLAIM_DATE), 'mm/dd/yyyy')) CLMDATE2 
		FROM
			HSP_BUCKET HLB 
			LEFT OUTER JOIN HSP_ACCT_LAST_UPDATE LASTUP 
			ON LASTUP.HSP_ACCOUNT_ID = HLB.HSP_ACCOUNT_ID 
		WHERE
			TO_DATE(LASTUP.INST_OF_UPDATE_DTTM, 'DD/MM/YYYY') BETWEEN TO_DATE(SYSDATE - 3, 'DD/MM/YYYY') AND
			TO_DATE(SYSDATE - 1, 'DD/MM/YYYY') AND
			HLB.BKT_TYPE_HA_C IN ('2',
			'6') 
		GROUP BY
			HLB.HSP_ACCOUNT_ID),
	MAXMSDRGTYPE AS 
	(	SELECT
			MS.HSP_ACCOUNT_ID,
			MS2.DRG_MPI_CODE 
		FROM
			(	SELECT
					HAM.HSP_ACCOUNT_ID,
					MAX(HAM.DRG_ID) MAXDRGID,
					DRGC.DRG_CODE_SET_C 
				FROM
					HSP_ACCT_MULT_DRGS HAM 
					LEFT OUTER JOIN DRG_CODE_SET_TYPES DRGC 
					ON DRGC.DRG_TYPE_ID = HAM.DRG_ID_TYPE_ID 
				WHERE
					DRGC.DRG_CODE_SET_C = '6' 
				GROUP BY
					HAM.HSP_ACCOUNT_ID,
					DRGC.DRG_CODE_SET_C) MS 
			LEFT OUTER JOIN (	SELECT
									HAM.DRG_MPI_CODE,
									HAM.DRG_ID 
								FROM
									HSP_ACCT_MULT_DRGS HAM 
									LEFT OUTER JOIN DRG_CODE_SET_TYPES DRGC 
									ON DRGC.DRG_TYPE_ID = HAM.DRG_ID_TYPE_ID 
								WHERE
									DRGC.DRG_CODE_SET_C = '6' 
								GROUP BY
									HAM.DRG_MPI_CODE,
									HAM.DRG_ID) MS2 
			ON MS2.DRG_ID = MS.MAXDRGID 
			LEFT OUTER JOIN HSP_ACCT_LAST_UPDATE LASTUP 
			ON LASTUP.HSP_ACCOUNT_ID = MS.HSP_ACCOUNT_ID 
		WHERE
			TO_DATE(LASTUP.INST_OF_UPDATE_DTTM, 'DD/MM/YYYY') BETWEEN TO_DATE(SYSDATE - 3, 'DD/MM/YYYY') AND
			TO_DATE(SYSDATE - 1, 'DD/MM/YYYY')),
	MAXAPRTYPE   AS 
	(	SELECT
			APR.HSP_ACCOUNT_ID,
			APR2.DRG_MPI_CODE,
			APR.DRG_PS,
			APR2.DRG_MPI_CODE || '-' || APR.DRG_PS APRPS 
		FROM
			(	SELECT
					HAM.HSP_ACCOUNT_ID,
					MAX(HAM.DRG_ID) MAXDRGID,
					DRGC.DRG_CODE_SET_C,
					MAX(HAM.DRG_PS) DRG_PS 
				FROM
					HSP_ACCT_MULT_DRGS HAM 
					LEFT OUTER JOIN DRG_CODE_SET_TYPES DRGC 
					ON DRGC.DRG_TYPE_ID = HAM.DRG_ID_TYPE_ID 
				WHERE
					DRGC.DRG_CODE_SET_C = '3' AND
					HAM.DRG_QLFR_C IS NULL 
				GROUP BY
					HAM.HSP_ACCOUNT_ID,
					DRGC.DRG_CODE_SET_C) APR 
			LEFT OUTER JOIN (	SELECT
									HAM.DRG_MPI_CODE,
									HAM.DRG_ID 
								FROM
									HSP_ACCT_MULT_DRGS HAM 
									LEFT OUTER JOIN DRG_CODE_SET_TYPES DRGC 
									ON DRGC.DRG_TYPE_ID = HAM.DRG_ID_TYPE_ID 
								WHERE
									DRGC.DRG_CODE_SET_C = '3' AND
									HAM.DRG_QLFR_C IS NULL 
								GROUP BY
									HAM.DRG_MPI_CODE,
									HAM.DRG_ID) APR2 
			ON APR2.DRG_ID = APR.MAXDRGID 
			LEFT OUTER JOIN HSP_ACCT_LAST_UPDATE LASTUP 
			ON LASTUP.HSP_ACCOUNT_ID = APR.HSP_ACCOUNT_ID 
		WHERE
			TO_DATE(LASTUP.INST_OF_UPDATE_DTTM, 'DD/MM/YYYY') BETWEEN TO_DATE(SYSDATE - 3, 'DD/MM/YYYY') AND
			TO_DATE(SYSDATE - 1, 'DD/MM/YYYY')),
	MAXAPTYPE    AS 
	(	SELECT
			AP.HSP_ACCOUNT_ID,
			AP2.DRG_MPI_CODE 
		FROM
			(	SELECT
					HAM.HSP_ACCOUNT_ID,
					MAX(HAM.DRG_ID) MAXDRGID,
					DRGC.DRG_CODE_SET_C 
				FROM
					HSP_ACCT_MULT_DRGS HAM 
					LEFT OUTER JOIN DRG_CODE_SET_TYPES DRGC 
					ON DRGC.DRG_TYPE_ID = HAM.DRG_ID_TYPE_ID 
				WHERE
					DRGC.DRG_CODE_SET_C = '2' 
				GROUP BY
					HAM.HSP_ACCOUNT_ID,
					DRGC.DRG_CODE_SET_C) AP 
			LEFT OUTER JOIN (	SELECT
									HAM.DRG_MPI_CODE,
									HAM.DRG_ID 
								FROM
									HSP_ACCT_MULT_DRGS HAM 
									LEFT OUTER JOIN DRG_CODE_SET_TYPES DRGC 
									ON DRGC.DRG_TYPE_ID = HAM.DRG_ID_TYPE_ID 
								WHERE
									DRGC.DRG_CODE_SET_C = '2' 
								GROUP BY
									HAM.DRG_MPI_CODE,
									HAM.DRG_ID) AP2 
			ON AP2.DRG_ID = AP.MAXDRGID),
	ADX          AS 
	(	SELECT
			HADMIT.HSP_ACCOUNT_ID,
			HADMIT.ADMIT_DX_ID,
			EDG.EXTERNAL_ID DX 
		FROM
			HSP_ACCT_ADMIT_DX HADMIT 
			LEFT OUTER JOIN CLARITY_EDG EDG 
			ON EDG.DX_ID = HADMIT.ADMIT_DX_ID 
			LEFT OUTER JOIN HSP_ACCT_LAST_UPDATE LASTUP 
			ON LASTUP.HSP_ACCOUNT_ID = HADMIT.HSP_ACCOUNT_ID 
		WHERE
			TO_DATE(LASTUP.INST_OF_UPDATE_DTTM, 'DD/MM/YYYY') BETWEEN TO_DATE(SYSDATE - 3, 'DD/MM/YYYY') AND
			TO_DATE(SYSDATE - 1, 'DD/MM/YYYY') AND
			HADMIT.LINE = 1),
	REFUN        AS 
	(	SELECT
			HTR2.HSP_ACCOUNT_ID,
			SUM(HTR2.TX_AMOUNT) REFUN 
		FROM
			HSP_TRANSACTIONS HTR2 
			LEFT OUTER JOIN CLARITY_EAP EAP 
			ON EAP.PROC_ID = HTR2.PROC_ID 
		WHERE
			EAP.RPT_GRP_ELEVEN_C = '800' 
		GROUP BY
			HTR2.HSP_ACCOUNT_ID),
	PCP_PROV     AS 
	(	SELECT
			HAR.HSP_ACCOUNT_ID,
			PCP2.PCP_PROV_ID 
		FROM
			(	SELECT
					PCPI.PAT_ID,
					MAX(PCPI.LINE) PCPLINE 
				FROM
					PAT_PCP PCPI 
				GROUP BY
					PCPI.PAT_ID) PCP 
			LEFT OUTER JOIN PAT_PCP PCP2 
			ON PCP2.PAT_ID = PCP.PAT_ID AND
			PCP2.LINE = PCP.PCPLINE 
			LEFT OUTER JOIN HSP_ACCOUNT HAR 
			ON HAR.PAT_ID = PCP.PAT_ID 
			LEFT OUTER JOIN CLARITY_SER SER 
			ON SER.PROV_ID = PCP2.PCP_PROV_ID 
			LEFT OUTER JOIN HSP_ACCT_LAST_UPDATE LASTUP 
			ON LASTUP.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID 
		WHERE
			TO_DATE(LASTUP.INST_OF_UPDATE_DTTM, 'DD/MM/YYYY') BETWEEN TO_DATE(SYSDATE - 3, 'DD/MM/YYYY') AND
			TO_DATE(SYSDATE - 1, 'DD/MM/YYYY') 
		GROUP BY
			HAR.HSP_ACCOUNT_ID,
			PCP2.PCP_PROV_ID),
	ATTD_PROV    AS 
	(	SELECT
			HAR.HSP_ACCOUNT_ID,
			HAP.PROV_ID 
		FROM
			HSP_ACCOUNT HAR 
			LEFT OUTER JOIN HSP_ATND_PROV HAP 
			ON HAP.PAT_ENC_CSN_ID = HAR.PRIM_ENC_CSN_ID 
			LEFT OUTER JOIN HSP_ACCT_LAST_UPDATE LASTUP 
			ON LASTUP.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID 
		WHERE
			HAR.HSP_ACCOUNT_ID IS NOT NULL AND
			HAP.PROV_ID IS NOT NULL AND
			TO_DATE(LASTUP.INST_OF_UPDATE_DTTM, 'DD/MM/YYYY') BETWEEN TO_DATE(SYSDATE - 3, 'DD/MM/YYYY') AND
			TO_DATE(SYSDATE - 1, 'DD/MM/YYYY') AND
			HAP.LINE = '1'),
	OR_PROV      AS 
	(	SELECT
			HAR.HSP_ACCOUNT_ID,
			CD1.OPERATING_PROV_ID 
		FROM
			HSP_ACCOUNT HAR 
			LEFT OUTER JOIN (	SELECT
									CD2.HOSPITAL_ACCT_ID,
									MAX(CD2.CLAIM_PRINT_ID) CLAIM_PRINT_ID 
								FROM
									HSP_CLAIM_DETAIL2 CD2 
								GROUP BY
									CD2.HOSPITAL_ACCT_ID) CD2 
			ON CD2.HOSPITAL_ACCT_ID = HAR.HSP_ACCOUNT_ID 
			LEFT OUTER JOIN HSP_ACCT_LAST_UPDATE LASTUP 
			ON LASTUP.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID 
			INNER JOIN HSP_CLAIM_DETAIL1 CD1 
			ON CD1.CLAIM_PRINT_ID = CD2.CLAIM_PRINT_ID 
		WHERE
			HAR.HSP_ACCOUNT_ID IS NOT NULL AND
			CD1.OPERATING_PROV_ID IS NOT NULL AND
			TO_DATE(LASTUP.INST_OF_UPDATE_DTTM, 'DD/MM/YYYY') BETWEEN TO_DATE(SYSDATE - 3, 'DD/MM/YYYY') AND
			TO_DATE(SYSDATE - 1, 'DD/MM/YYYY')),
	UNCHGS       AS 
	(	SELECT
			BKTSNAP.HSP_ACCOUNT_ID,
			BKTSNAP.TOT_CHGS 
		FROM
			HSP_BKT_SNAPSHOT BKTSNAP 
			INNER JOIN HSP_BUCKET BKT 
			ON BKTSNAP.BUCKET_ID = BKT.BUCKET_ID 
			INNER JOIN DATE_DIMENSION DT 
			ON BKTSNAP.SNAP_START_DATE <= DT.CALENDAR_DT AND
			BKTSNAP.SNAP_END_DATE >= DT.CALENDAR_DT AND
			DT.CALENDAR_DT = EPIC_UTIL.EFN_DIN('T-1') 
WHERE
	BKT.BKT_TYPE_HA_C = 1 AND
	BKTSNAP.BUCKET_BAL <> 0),
	REFUNDS2 AS (	SELECT
						VRATIO.HSP_ACCOUNT_ID,
						NVL(NVL(VRATIO.INS_REFUND_ADJS, 0) + NVL(VRATIO.SP_REFUND_ADJS, 0), 0) REFUNDS 
					FROM
						HSP_ACCOUNT HAR 
						LEFT OUTER JOIN V_ARHB_COLLECTION_RATIO VRATIO 
						ON HAR.HSP_ACCOUNT_ID = VRATIO.HSP_ACCOUNT_ID 
						LEFT OUTER JOIN HSP_ACCT_LAST_UPDATE LASTUP 
						ON LASTUP.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID 
					WHERE
						VRATIO.HSP_ACCOUNT_ID IS NOT NULL AND
						HAR.HSP_ACCOUNT_ID IS NOT NULL AND
						TO_DATE(LASTUP.INST_OF_UPDATE_DTTM, 'DD/MM/YYYY') BETWEEN TO_DATE(SYSDATE - 365, 'DD/MM/YYYY') AND
						TO_DATE(SYSDATE - 1, 'DD/MM/YYYY')) 
SELECT
	CASE 
		WHEN HAR.HSP_ACCOUNT_ID IS NOT NULL 
		THEN HAR.HSP_ACCOUNT_ID 
		ELSE NULL 
	END                          AS ACCOUNTNUMBER,
	CASE 
		-- Epic upgrade Aug 2020 replace HSP_ACCOUNT.PATIENT_MRN wit new HSP_ACCT_PAT_MRN.PAT_MRN
		--WHEN HAR.PATIENT_MRN IS NOT NULL 
		--THEN HAR.PATIENT_MRN 
		WHEN ACCTMRN.PAT_MRN IS NOT NULL 
		THEN ACCTMRN.PAT_MRN 
		ELSE NULL 
	END                          AS PATIENTMRN,
	CASE 
		WHEN HAR.LOC_ID IS NOT NULL 
		THEN HAR.LOC_ID 
		ELSE NULL 
	END                          AS FACILITYCODE,
	CASE 
		WHEN HAR.ADM_DATE_TIME IS NOT NULL 
		THEN TO_CHAR(TRUNC(HAR.ADM_DATE_TIME), 'mm/dd/yyyy') 
		ELSE NULL 
	END                          AS ADMITDATE,
	CASE 
		WHEN HAR.DISCH_DATE_TIME IS NOT NULL 
		THEN TO_CHAR(TRUNC(HAR.DISCH_DATE_TIME), 'mm/dd/yyyy') 
		ELSE NULL 
	END                          AS DISCHARGEDATE,
	CASE 
		WHEN HAR.ACCT_FIN_CLASS_C = '4' 
		THEN TO_CHAR(HAR.FRST_DET_BILL_DATE) 
		ELSE 
		CASE 
			WHEN CLMBKT.CLMDATE IS NOT NULL 
			THEN CLMBKT.CLMDATE 
			ELSE NULL 
		END 
	END                          AS BILLDATEHIS,
	NULL                     AS BILLDATESCRUBBER,
	CASE 
		WHEN BC.ABBR IS NOT NULL 
		THEN BC.ABBR 
		ELSE NULL 
	END                          AS PATIENTCLASSCODE,
	CASE 
		WHEN AC.NAME IS NOT NULL 
		THEN AC.NAME 
		ELSE NULL 
	END                          AS PATIENTTYPECODE,
	CASE 
		WHEN MAXMSDRGTYPE.DRG_MPI_CODE IS NOT NULL 
		THEN MAXMSDRGTYPE.DRG_MPI_CODE 
		ELSE NULL 
	END                          AS MSDRGCODE,
	CASE 
		WHEN MAXAPTYPE.DRG_MPI_CODE IS NOT NULL 
		THEN MAXAPTYPE.DRG_MPI_CODE 
		ELSE NULL 
	END                          AS APDRGCODE,
	CASE 
		WHEN MAXAPRTYPE.APRPS IS NOT NULL 
		THEN MAXAPRTYPE.APRPS 
		ELSE NULL 
	END                          AS APRDRGCODE,
	CASE 
		WHEN HAR.PATIENT_STATUS_C IS NOT NULL 
		THEN HAR.PATIENT_STATUS_C 
		ELSE 
		CASE 
			WHEN PENC.DISCH_DISP_C IS NOT NULL 
			THEN PENC.DISCH_DISP_C 
			ELSE NULL 
		END 
	END                          AS DISCHARGEDISPOSITIONCODE,
	CASE 
		WHEN PATSVC.ABBR IS NOT NULL 
		THEN PATSVC.ABBR 
		ELSE NULL 
	END                          AS MEDICALSERVICECODE,
	NULL                     AS ADMITSTATUS,
	NULL                     AS BILLSTATUS,
	NULL                     AS ACCOUNTSTATUS,
	NULL                     AS ADMITLOCATIONCODE,
	NULL                     AS ADMITTYPECODE,
	NULL                     AS ADMITCODE,
	CASE 
		WHEN ADX.DX IS NOT NULL 
		THEN ADX.DX 
		ELSE NULL 
	END                          AS ADMITDIAGNOSISCODE,
	CASE 
		WHEN BKT.HSP_ACCOUNT_ID IS NOT NULL 
		THEN BKT.INTERNAL_ID 
		ELSE 
		CASE 
			WHEN FC.FIN_CLASS_C IS NOT NULL 
			THEN FC.FIN_CLASS_C 
			ELSE NULL 
		END 
	END                          AS CURRENTFINANCIALCLASSCODE,
	CASE 
		WHEN HAR.TOT_CHGS IS NOT NULL 
		THEN HAR.TOT_CHGS 
		ELSE 0 
	END                          AS TOTALCHARGES,
	NVL(UNCHGS.TOT_CHGS, 0)  AS UNBILLEDCHARGES,
	NVL(HAR.TOT_PMTS, 0)     AS TOTALPAYMENTS,
	NVL(HAR.TOT_ADJ, 0)      AS TOTALADJUSTMENTS,
	NVL(REFUNDS2.REFUNDS, 0) AS TOTALREFUNDS,
	NVL(HAR.TOT_ACCT_BAL, 0) AS ACCOUNTBALANCE,
	CASE 
		WHEN SER2ATTND.NPI IS NOT NULL 
		THEN SER2ATTND.NPI 
		ELSE 
		CASE 
			WHEN SER2ATTND2.NPI IS NOT NULL 
			THEN SER2ATTND2.NPI 
			ELSE NULL 
		END 
	END                          AS PHYSICIANATTENDINGNPI,
	CASE 
		WHEN SER2OPP.NPI IS NOT NULL 
		THEN SER2OPP.NPI 
		ELSE NULL 
	END                          AS PHYSICIANOPERATINGNPI,
	CASE 
		WHEN SER2ADMIT.NPI IS NOT NULL 
		THEN SER2ADMIT.NPI 
		ELSE NULL 
	END                          AS PHYSICIANADMITTINGNPI,
	CASE 
		WHEN SER2PCP.NPI IS NOT NULL 
		THEN SER2PCP.NPI 
		ELSE NULL 
	END                          AS PHYSICIANPRIMARYCARENPI,
	CASE 
		WHEN SER2REF.NPI IS NOT NULL 
		THEN SER2REF.NPI 
		ELSE NULL 
	END                          AS PHYSICIANREFERRINGNPI,
	CASE 
		WHEN HAR.HSP_ACCOUNT_NAME IS NOT NULL 
		THEN HAR.HSP_ACCOUNT_NAME 
		ELSE NULL 
	END                          AS PATIENTNAME,
	NULL                     AS PATIENTSSN,
	NULL                     AS PATIENTDOB,
	NULL                     AS PATIENTCITY,
	NULL                     AS PATIENTSTATE,
	NULL                     AS PATIENTZIP,
	NULL                     AS PATIENTGENDER,
	CASE 
		WHEN HAR.CODING_STATUS_C = '4' AND
		HAR.CODING_STATUS_C IS NOT NULL 
		THEN 'Y' 
		ELSE 
		CASE 
			WHEN HAR.CODING_STATUS_C <> '4' AND
			HAR.CODING_STATUS_C IS NOT NULL 
			THEN 'N' 
			ELSE 'N' 
		END 
	END                          AS CODINGCOMPLETE,
	CASE 
		WHEN LASTUP.INST_OF_UPDATE_DTTM IS NOT NULL 
		THEN TO_CHAR(TRUNC(LASTUP.INST_OF_UPDATE_DTTM), 'mm/dd/yyyy') 
		ELSE NULL 
	END                          AS ACCTLASTUPDATE,
	CASE 
		WHEN ADMTDEPT.REV_LOC_ID IS NOT NULL 
		THEN ADMTDEPT.REV_LOC_ID 
		ELSE NULL 
	END                          AS ADMITLOCATION
FROM
	HSP_ACCOUNT HAR 
		LEFT OUTER JOIN ZC_ACCT_BASECLS_HA BC 
		ON BC.ACCT_BASECLS_HA_C = HAR.ACCT_BASECLS_HA_C 
		LEFT OUTER JOIN ZC_ACCT_CLASS_HA AC 
		ON AC.ACCT_CLASS_HA_C = HAR.ACCT_CLASS_HA_C 
		LEFT OUTER JOIN ZC_FIN_CLASS FC 
		ON FC.FIN_CLASS_C = HAR.ACCT_FIN_CLASS_C 
		LEFT OUTER JOIN ZC_ACCT_BILLSTS_HA ZAB 
		ON ZAB.ACCT_BILLSTS_HA_C = HAR.ACCT_BILLSTS_HA_C 
		LEFT OUTER JOIN CLARITY_EPP EPP 
		ON HAR.PRIMARY_PLAN_ID = EPP.BENEFIT_PLAN_ID 
		LEFT OUTER JOIN HSP_BUCKET SP 
		ON SP.BUCKET_ID = HAR.SELF_PAY_BUCKET_ID 
		LEFT OUTER JOIN CLARITY_SER_SPEC SPEC 
		ON HAR.ATTENDING_PROV_ID = SPEC.PROV_ID AND
		SPEC.LINE = 1 
		LEFT OUTER JOIN ZC_SPECIALTY SPEC1 
		ON SPEC1.SPECIALTY_C = SPEC.SPECIALTY_C 
		LEFT OUTER JOIN BKT 
		ON BKT.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID 
		LEFT OUTER JOIN PAT_ENC_HSP PENC 
		ON PENC.PAT_ENC_CSN_ID = HAR.PRIM_ENC_CSN_ID 
		LEFT OUTER JOIN CLARITY_DEP HSPDEP 
		ON HSPDEP.DEPARTMENT_ID = PENC.DEPARTMENT_ID 
		LEFT OUTER JOIN PAT_ENC ENC 
		ON ENC.PAT_ENC_CSN_ID = HAR.PRIM_ENC_CSN_ID 
		LEFT OUTER JOIN CLARITY_DEP ENCDEP 
		ON ENCDEP.DEPARTMENT_ID = ENC.DEPARTMENT_ID 
		LEFT OUTER JOIN ZC_PAT_SERVICE PATS 
		ON PATS.HOSP_SERV_C = PENC.HOSP_SERV_C 
		LEFT OUTER JOIN MAXAPRTYPE 
		ON MAXAPRTYPE.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID 
		LEFT OUTER JOIN MAXMSDRGTYPE 
		ON MAXMSDRGTYPE.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID 
		LEFT OUTER JOIN MAXAPTYPE 
		ON MAXAPTYPE.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID 
		LEFT OUTER JOIN ADX 
		ON ADX.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID 
		LEFT OUTER JOIN ACCOUNT EAR 
		ON EAR.ACCOUNT_ID = HAR.GUARANTOR_ID 
-- Join from HSP_ACCOUNT would be using HSP_ACCOUNT_ID to HSP_ACCT_PAT_MRN on HSP_ACCOUNT_ID to retrieve PAT_MRN
	        LEFT OUTER JOIN HSP_ACCT_PAT_MRN ACCTMRN
	        ON ACCTMRN.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID
--		ON PT.PAT_MRN_ID = HAR.PATIENT_MRN 
	        LEFT OUTER JOIN PATIENT PT 
		ON PT.PAT_MRN_ID = ACCTMRN.PAT_MRN 
		LEFT OUTER JOIN ZC_STATE ST 
		ON ST.STATE_C = PT.STATE_C 
		LEFT OUTER JOIN HSP_ACCT_LAST_UPDATE LASTUP 
		ON LASTUP.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID 
		LEFT OUTER JOIN ZC_SPECIALTY_SVC HARSVC 
		ON HARSVC.SPECIALTY_SVC_C = HAR.SPECIALTY_SVC_C 
		LEFT OUTER JOIN UNCHGS 
		ON UNCHGS.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID 
		LEFT OUTER JOIN ZC_PRIM_SVC_HA PATSVC 
		ON PATSVC.PRIM_SVC_HA_C = HAR.PRIM_SVC_HA_C 
		LEFT OUTER JOIN CLMBKT 
		ON CLMBKT.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID 
		LEFT OUTER JOIN ADMTDEPT 
		ON ADMTDEPT.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID 
		LEFT OUTER JOIN ATTD_PROV 
		ON ATTD_PROV.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID 
		LEFT OUTER JOIN REFUN 
		ON REFUN.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID 
		LEFT OUTER JOIN PCP_PROV 
		ON PCP_PROV.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID 
		LEFT OUTER JOIN OR_PROV 
		ON OR_PROV.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID 
		LEFT OUTER JOIN CLARITY_SER_2 SER2ATTND 
		ON SER2ATTND.PROV_ID = HAR.ATTENDING_PROV_ID 
		LEFT OUTER JOIN CLARITY_SER_2 SER2ATTND2 
		ON SER2ATTND2.PROV_ID = ATTD_PROV.PROV_ID 
		LEFT OUTER JOIN CLARITY_SER_2 SER2OPP 
		ON SER2OPP.PROV_ID = OR_PROV.OPERATING_PROV_ID 
		LEFT OUTER JOIN CLARITY_SER_2 SER2ADMIT 
		ON SER2ADMIT.PROV_ID = HAR.ADM_PROV_ID 
		LEFT OUTER JOIN CLARITY_SER_2 SER2PCP 
		ON SER2PCP.PROV_ID = PCP_PROV.PCP_PROV_ID 
		LEFT OUTER JOIN CLARITY_SER_2 SER2REF 
		ON SER2REF.PROV_ID = HAR.REFERRING_PROV_ID 
		LEFT OUTER JOIN HSP_ACCT_LAST_UPDATE LASTUP 
		ON LASTUP.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID 
		LEFT OUTER JOIN REFUNDS2 
		ON REFUNDS2.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID 
WHERE
	TO_DATE(LASTUP.INST_OF_UPDATE_DTTM, 'DD/MM/YYYY') BETWEEN TO_DATE(SYSDATE - 3, 'DD/MM/YYYY') AND
	TO_DATE(SYSDATE - 1, 'DD/MM/YYYY') AND
	HAR.HSP_ACCOUNT_ID IS NOT NULL AND
	EAR.ACCOUNT_TYPE_C NOT IN ('101',
	'102') AND
	HAR.NUM_OF_CHARGES > 0
	AND HAR.ACCT_FIN_CLASS_C != 4 -- Remove self-pay accounts. STSK0769632