SELECT
LPL.PAT_ID					"PATIENT ID",	
LPL.ALLERGEN_ID				"ALLERGEN ID",		
LPL.ALLERGY_ID				"ID",
ELG.ALLERGEN_NAME			"ALLERGEN NAME",
COALESCE(CAST(LPL.ALLERGY_SEVERITY_C as varchar), '*No Severity Notes')"SEVERITY CATEGORY",
ZSEV.NAME					"SEVERITY",
LPL.DATE_NOTED				"DATE NOTED"
  FROM ALLERGY LPL
    INNER JOIN CL_ELG ELG
      ON LPL.ALLERGEN_ID = ELG.ALLERGEN_ID
    LEFT OUTER JOIN ZC_ALLERGY_SEVERIT ZSEV
      ON LPL.ALLERGY_SEVERITY_C = ZSEV.ALLERGY_SEVERITY_C
  WHERE ELG.ALLERGEN_ID IN ({{C_ALLERGY_ID}})
    AND DATE_NOTED >= {{REPORT_START_DT}} 
	AND	DATE_NOTED <= ({{REPORT_END_DT}} + 1)