
WITH ANTIMICROBIAL
AS
(
  SELECT --*
  cm.MEDICATION_ID
  ,cm.NAME
  ,coalesce(rx2.SHORT_NAME, zcsg.NAME) "SHORT_NAME"
  ,zct.NAME   "THERA_CLASS"
  ,zcpp.NAME  "PHARM_CLASS"
  ,CASE WHEN cm.NAME LIKE '%CIPROFLOXACIN%' THEN 'FLUOROQUINOLONES' 
        WHEN cm.NAME LIKE '%LEVOFLOXACIN%' THEN 'FLUOROQUINOLONES'
        WHEN cm.NAME LIKE '%MOXIFLOXACIN%' THEN 'FLUOROQUINOLONES'
        WHEN cm.NAME LIKE '%CEFEPIME%' THEN 'BETA-LACTAMS'
        WHEN cm.NAME LIKE '%PIPERACILLIN-TAZOBACTAM%' THEN 'BETA-LACTAMS'
        WHEN cm.NAME LIKE '%IMIPENEM%' THEN 'BETA-LACTAMS'
        WHEN cm.NAME LIKE '%MEROPENEM%' THEN 'BETA-LACTAMS'
        WHEN cm.NAME LIKE 'VANCOMYCIN 1.25 G%' THEN 'VANCOMYCIN IV'
        WHEN cm.NAME LIKE 'VANCOMYCIN%'||'%INTRAV%' THEN 'VANCOMYCIN IV'
        WHEN cm.NAME LIKE 'VANCOMYCIN IT%' THEN 'VANCOMYCIN IV'
        WHEN cm.NAME LIKE 'VANCOMYCIN%'||'%IV SYRI%' THEN 'VANCOMYCIN IV'
        WHEN cm.NAME LIKE 'VANCOMYCIN%'||'%IVPB%' THEN 'VANCOMYCIN IV'
        WHEN cm.NAME LIKE 'VANCOMYCIN%'||'%10 MG/ML INJ%' THEN 'VANCOMYCIN IV'
        WHEN cm.NAME LIKE '%CLINDAMYCIN%' THEN 'OTHER GRAM AGENTS'
        WHEN cm.NAME LIKE '%DAPTOMYCIN%' THEN 'OTHER GRAM AGENTS'
        WHEN cm.NAME LIKE '%LINEZOLID%' THEN 'OTHER GRAM AGENTS'
        WHEN cm.NAME LIKE '%CEFTAROLINE%' THEN 'OTHER GRAM POS AGENTS'
        WHEN cm.NAME LIKE '%CEFTAZIDIME-AVIBACTAM%' THEN 'MULTI GRAM NEG AGENTS'
        WHEN cm.NAME LIKE '%CEFTOLOZANE-TAZOBACTAM%' THEN 'MULTI GRAM NEG AGENTS'
        WHEN cm.NAME LIKE '%MEROPENEM-VABORBACTAM%' THEN 'MULTI GRAM NEG AGENTS'
        WHEN cm.NAME LIKE '%CEFIDEROCOL%' THEN 'MULTI GRAM NEG AGENTS'
        WHEN cm.NAME LIKE '%OMADACYCLINE' THEN 'MULTI GRAM NEG AGENTS'
  


  ELSE 'OTHER' END "GROUPMED"
  FROM CLARITY_MEDICATION cm
  LEFT OUTER JOIN ZC_SIMPLE_GENERIC zcsg ON cm.SIMPLE_GENERIC_C = zcsg.SIMPLE_GENERIC_C
    LEFT OUTER JOIN RX_MED_TWO rx2 ON cm.MEDICATION_ID = rx2.MEDICATION_ID
    LEFT OUTER JOIN ZC_THERA_CLASS zct ON cm.THERA_CLASS_C = zct.THERA_CLASS_C
    LEFT OUTER JOIN ZC_PHARM_CLASS zcpp ON cm.PHARM_CLASS_C = zcpp.PHARM_CLASS_C
  WHERE 
  cm.THERA_CLASS_C = 41


) 

SELECT --*
fdot.PAT_ID
,fdot.TAKEN_DATE
,pat.PAT_MRN_ID
,pat.PAT_NAME
,zcps.NAME
,fdot.MEDICATION_ID
,cm.NAME
,serauth.PROV_NAME
,dep.DEPARTMENT_NAME
,parloc.LOC_NAME
,fdot.ORDER_ID
,fdot.UPDATE_DATE
--,CASE WHEN TRUNC((fdot  - pat.BIRTH_DATE) / 365.25) < 1
--    THEN CASE WHEN months_between (to_date(ucl.SERVICE_DATE_DT), pat.BIRTH_DATE) < 1
--    THEN CONCAT(to_char(floor(TRUNC(ucl.SERVICE_DATE_DT ) - pat.BIRTH_DATE))  ,' Days')
--    ELSE CONCAT(to_char(floor(months_between (to_date( ucl.SERVICE_DATE_DT ), pat.BIRTH_DATE) ) ),' Months')  END        
--    ELSE to_char(TRUNC(floor(ucl.SERVICE_DATE_DT  - pat.BIRTH_DATE) / 365.25))
--    END "PATIENT_AGE_AT_ENCOUNTER"

--,dep.DEPARTMENT_ID
FROM F_DOT_CONTRIB_ORDS_DEPT fdot
INNER JOIN order_med om ON fdot.ORDER_ID = om.ORDER_MED_ID
LEFT OUTER JOIN IP_FREQUENCY freq ON om.HV_DISCR_FREQ_ID=freq.FREQ_ID
LEFT OUTER JOIN ZC_ADMIN_ROUTE zcar ON om.MED_ROUTE_C=zcar.MED_ROUTE_C

LEFT OUTER JOIN clarity_dep dep ON fdot.DEPARTMENT_ID = dep.DEPARTMENT_ID
LEFT OUTER JOIN clarity_loc loc ON dep.REV_LOC_ID = loc.LOC_ID
LEFT OUTER JOIN clarity_loc parloc ON loc.HOSP_PARENT_LOC_ID = parloc.LOC_ID
LEFT OUTER JOIN zc_pat_service zcps ON fdot.PAT_HOSP_SERV_C = zcps.HOSP_SERV_C
LEFT OUTER JOIN clarity_ser serauth ON fdot.AUTHG_PROV_ID = serauth.PROV_ID
LEFT OUTER JOIN CLARITY_SER seratt ON fdot.ATTEND_PROV_ID = seratt.PROV_ID
LEFT OUTER JOIN clarity_ser serord ON fdot.ORDER_PROV_ID = serord.PROV_ID
INNER JOIN patient pat ON fdot.PAT_ID = pat.PAT_ID
LEFT OUTER JOIN ANTIMICROBIAL cm ON fdot.MEDICATION_ID = cm.MEDICATION_ID
WHERE
--fdot.PAT_ID = 'Z212338'
AND fdot.MEDICATION_ID = 32471
AND TRUNC(fdot.TAKEN_DATE) >= '1-sep-2020'
AND TRUNC(fdot.TAKEN_DATE) <= '9-sep-2020'
AND  NOT (zcar.NAME LIKE 'Both%' 
OR zcar.NAME LIKE 'Left%' 
OR zcar.NAME LIKE 'Right%' 
OR zcar.NAME LIKE 'Topical%')

SELECT *
FROM PATIENT pat
WHERE
pat.PAT_MRN_ID = '2012930'


SELECT *
FROM V_RX_CHARGES vrx
WHERE
vrx.ORDER_ID = 562567192

SELECT *
FROM GROUPER_MED_RECS grp
INNER JOIN grouper_items grpi ON grp.GROUPER_ID = grpi.GROUPER_ID
WHERE
grp.EXP_MEDS_LIST_ID = 32471
 
 SELECT *
 FROM ORDER_MED om
 WHERE
 om.ORDER_MED_ID = 562567192

SELECT COUNT(*) 
SELECT *
--,fdays.CENSUS_DTTM
FROM F_IP_HSP_PAT_DAYS fdays
LEFT OUTER JOIN clarity_dep dep ON fdays.DEPARTMENT_ID = dep.DEPARTMENT_ID
LEFT OUTER JOIN clarity_loc loc ON dep.REV_LOC_ID = loc.LOC_ID
LEFT OUTER JOIN clarity_loc parloc ON loc.HOSP_PARENT_LOC_ID = parloc.LOC_ID

WHERE
fdays.CALENDAR_DT >= '1-jan-2020'
AND fdays.CALENDAR_DT < '1-feb-2020'
--fdays.PAT_ENC_CSN_ID = 30126193271
AND fdays.CENSUS_DTTM IS NOT NULL
AND dep.DEPARTMENT_NAME LIKE '%UNIT%'
AND parloc.LOC_ID = 100002
--GROUP BY fdays.CENSUS_DTTM
GROUP BY fdays.PAT_ENC_CSN_ID
--fdays.PAT_ID = 'Z212338'
