SELECT 
fdot.TAKEN_DATE
,pat.PAT_MRN_ID
,CASE when TRUNC((TRUNC(fdot.TAKEN_DATE)  - pat.BIRTH_DATE) / 365.25) > 17 THEN 'ADULT' ELSE 'PEDS' END "AGEGROUP"
,om.PAT_ENC_CSN_ID
,dep.DEPARTMENT_ID
,dep.DEPARTMENT_NAME 
,zcps.NAME  "SERVICE"
,fdot.MEDICATION_ID
,zcar.NAME "ROUTE"
,fdot.DRUG_CODE
,serauth.PROV_NAME  "AUTHORIZED_PROVIDER"
,serord.PROV_NAME  "ORDER_PROVIDER"
,seratt.PROV_NAME  "ATTENDING_PROVIDER"
,fdot.DAY_OF_THERAPY_IV
,fdot.DAY_OF_THERAPY_IM
,fdot.DAY_OF_THERAPY_DIGESTIVE
,fdot.DAY_OF_THERAPY_RESPIRATORY
,fdot.ORDER_ID
,fdot.UPDATE_DATE
,pat3.IS_TEST_PAT_YN
,extract(month from fdot.TAKEN_DATE) "TAKEN_MONTH"
FROM CLARITY_ADT adt
INNER JOIN order_med om ON adt.PAT_ENC_CSN_ID = om.PAT_ENC_CSN_ID
INNER JOIN F_DOT_CONTRIB_ORDS_DEPT fdot ON om.ORDER_MED_ID = fdot.ORDER_ID
inner join ORDER_MEDINFO ominfo ON om.ORDER_MED_ID = ominfo.ORDER_MED_ID
LEFT OUTER join order_medmixinfo ommix ON om.ORDER_MED_ID = ommix.ORDER_MED_ID AND ommix.LINE = 1
LEFT OUTER JOIN CLARITY_MEDICATION cm ON COALESCE( ommix.MEDICATION_ID, ominfo.DISPENSABLE_MED_ID) = cm.MEDICATION_ID
LEFT OUTER JOIN IP_FREQUENCY freq ON om.HV_DISCR_FREQ_ID=freq.FREQ_ID
LEFT OUTER JOIN ZC_ADMIN_ROUTE zcar ON om.MED_ROUTE_C=zcar.MED_ROUTE_C
LEFT OUTER JOIN clarity_dep dep ON fdot.DEPARTMENT_ID = dep.DEPARTMENT_ID
LEFT OUTER JOIN zc_pat_service zcps ON fdot.PAT_HOSP_SERV_C = zcps.HOSP_SERV_C
LEFT OUTER JOIN clarity_ser serauth ON fdot.AUTHG_PROV_ID = serauth.PROV_ID
LEFT OUTER JOIN CLARITY_SER seratt ON fdot.ATTEND_PROV_ID = seratt.PROV_ID
LEFT OUTER JOIN clarity_ser serord ON fdot.ORDER_PROV_ID = serord.PROV_ID
INNER JOIN patient pat ON fdot.PAT_ID = pat.PAT_ID
INNER JOIN patient_3 pat3 ON pat.PAT_ID = pat3.PAT_ID

WHERE
adt.EVENT_SUBTYPE_C <> 2  ---- deleted
AND adt.EVENT_TYPE_C IN (1,3)
AND TRUNC(adt.EFFECTIVE_TIME) = '5-mar-2021' 
AND pat3.IS_TEST_PAT_YN <> 'Y'

