SELECT 
cm.MEDICATION_ID
,cm.NAME
,coalesce(rx2.SHORT_NAME, zcsg.NAME) "SHORT_NAME"
,zct.NAME   "THERA_CLASS"
,zcpp.NAME  "PHARM_CLASS"
,cm.FORM
,zcar.NAME  "ADMIN_ROUTE"
,zcps.NAME "PHARM_SUBCLASS"

FROM CLARITY_MEDICATION cm
LEFT OUTER JOIN ZC_SIMPLE_GENERIC zcsg ON cm.SIMPLE_GENERIC_C = zcsg.SIMPLE_GENERIC_C
LEFT OUTER JOIN RX_MED_TWO rx2 ON cm.MEDICATION_ID = rx2.MEDICATION_ID
LEFT OUTER JOIN ZC_THERA_CLASS zct ON cm.THERA_CLASS_C = zct.THERA_CLASS_C
LEFT OUTER JOIN ZC_PHARM_CLASS zcpp ON cm.PHARM_CLASS_C = zcpp.PHARM_CLASS_C
LEFT OUTER JOIN ZC_ADMIN_ROUTE zcar ON rx2.ADMIN_ROUTE_C = zcar.MED_ROUTE_C
LEFT OUTER JOIN ZC_PHARM_SUBCLASS zcps ON cm.PHARM_SUBCLASS_C = zcps.PHARM_SUBCLASS_C
WHERE 
cm.THERA_CLASS_C in (41,42,43)
AND  NOT (zcar.NAME LIKE 'Both%' 
OR zcar.NAME LIKE 'Left%' 
OR zcar.NAME LIKE 'Right%' 
OR zcar.NAME LIKE 'Topical%')

