WITH
	ARBAL AS 
	(	SELECT
			HARSNAP.HSP_ACCOUNT_ID,
			HARSNAP.TOT_ACCT_BAL 
		FROM
			HSP_HAR_SNAPSHOT HARSNAP 
			INNER JOIN HSP_ACCOUNT HAR 
			ON HARSNAP.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID 
			INNER JOIN DATE_DIMENSION DT 
			ON HARSNAP.SNAP_START_DATE <= DT.CALENDAR_DT AND
			HARSNAP.SNAP_END_DATE >= DT.CALENDAR_DT AND
			DT.CALENDAR_DT = EPIC_UTIL.EFN_DIN('ME-1') 
WHERE
	HARSNAP.TOT_ACCT_BAL <> 0),
	BADDEBT AS (SELECT
					BKTSNAP.HSP_ACCOUNT_ID,
					SUM(
					CASE 
						WHEN BKT.BAD_DEBT_FLAG_YN = 'Y' 
						THEN BKTSNAP.BUCKET_BAL 
						ELSE 0 
					END) BADDEBT 
				FROM
					HSP_BKT_SNAPSHOT BKTSNAP 
					INNER JOIN HSP_BUCKET BKT 
					ON BKTSNAP.BUCKET_ID = BKT.BUCKET_ID 
					INNER JOIN DATE_DIMENSION DT 
					ON BKTSNAP.SNAP_START_DATE <= DT.CALENDAR_DT AND
					BKTSNAP.SNAP_END_DATE >= DT.CALENDAR_DT AND
					DT.CALENDAR_DT = EPIC_UTIL.EFN_DIN('ME-1') 
WHERE
	BKTSNAP.BUCKET_BAL <> 0 AND
	BKT.BAD_DEBT_FLAG_YN = 'Y' 
GROUP BY
	BKTSNAP.HSP_ACCOUNT_ID) 
SELECT
	CASE 
		WHEN HAR.HSP_ACCOUNT_ID IS NOT NULL 
		THEN HAR.HSP_ACCOUNT_ID 
		ELSE NULL 
	END                            AS ACCOUNTNUMBER,
	CASE 
		WHEN HAR.LOC_ID IS NOT NULL 
		THEN HAR.LOC_ID 
		ELSE NULL 
	END                            AS FACILITYCODE,
	CASE 
		WHEN HAR.ADM_DATE_TIME IS NOT NULL 
		THEN TO_CHAR(TRUNC(HAR.ADM_DATE_TIME), 'mm/dd/yyyy') 
		ELSE NULL 
	END                            AS ADMITDATE,
	NVL(ARBAL.TOT_ACCT_BAL, 0) AS ACCOUNTBALANCE,
	NVL(BADDEBT.BADDEBT, 0)    AS BADDEBTBALANCCE,
	CASE 
		WHEN HARUP.INST_OF_UPDATE_DTTM IS NOT NULL 
		THEN TO_CHAR(TRUNC(HARUP.INST_OF_UPDATE_DTTM), 'mm/dd/yyyy') 
		ELSE NULL 
	END                            AS LASTMODIFIEDDATE
FROM
	HSP_ACCOUNT HAR 
		INNER JOIN ARBAL 
		ON ARBAL.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID 
		LEFT OUTER JOIN BADDEBT 
		ON BADDEBT.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID 
		LEFT OUTER JOIN HSP_ACCT_LAST_UPDATE HARUP 
		ON HARUP.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID 
WHERE
	ARBAL.HSP_ACCOUNT_ID IS NOT NULL AND
	BADDEBT.HSP_ACCOUNT_ID IS NOT NULL AND
    HAR.ACCT_FIN_CLASS_C != 4 -- Remove self-pay accounts. STSK0769632
