WITH
	CLMDX AS 
	(	SELECT
			BKT.HSP_ACCOUNT_ID,
			CLMDX.CLM_DX,
			CLMDX.LINE,
			CLMDX.CLM_DX_POA 
		FROM
			CLM_DX CLMDX 
			LEFT OUTER JOIN HSP_CLAIM_DETAIL2 CLM2 
			ON CLM2.CLM_EXT_VAL_ID = CLMDX.RECORD_ID 
			LEFT OUTER JOIN HSP_BUCKET BKT 
			ON BKT.BUCKET_ID = CLM2.HLB_ID 
		GROUP BY
			BKT.HSP_ACCOUNT_ID,
			CLMDX.CLM_DX,
			CLMDX.LINE,
			CLMDX.CLM_DX_POA) 
SELECT
	CASE 
		WHEN HAR.HSP_ACCOUNT_ID IS NOT NULL 
		THEN HAR.HSP_ACCOUNT_ID 
		ELSE NULL 
	END AS ACCOUNTNUMBER,
	CASE 
		WHEN HAR.LOC_ID IS NOT NULL 
		THEN HAR.LOC_ID 
		ELSE NULL 
	END AS FACILITYCODE,
	CASE 
		WHEN CLMDX.LINE IS NOT NULL 
		THEN CLMDX.LINE 
		ELSE NULL 
	END AS DIAGNOSISORDER,
	CASE 
		WHEN CLMDX.CLM_DX IS NOT NULL 
		THEN CLMDX.CLM_DX 
		ELSE NULL 
	END AS DIAGNOSISCODE,
	CASE 
		WHEN CLMDX.CLM_DX_POA IS NOT NULL 
		THEN CLMDX.CLM_DX_POA 
		ELSE NULL 
	END AS POAINDICATOR,
	CASE 
		WHEN SER2.NPI IS NOT NULL 
		THEN SER2.NPI 
		ELSE NULL 
	END AS DIAGNOSINGPHYSICIANNPI 
FROM
	HSP_ACCOUNT HAR 
		LEFT OUTER JOIN HSP_ACCT_DX_LIST DX 
		ON DX.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID 
		LEFT OUTER JOIN CLMDX 
		ON CLMDX.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID 
		LEFT OUTER JOIN CLARITY_SER_2 SER2 
		ON SER2.PROV_ID = HAR.ATTENDING_PROV_ID 
		LEFT OUTER JOIN ZC_DX_POA POA1 
		ON POA1.DX_POA_C = DX.FINAL_DX_POA_C 
		LEFT OUTER JOIN CLARITY_EDG EDG 
		ON EDG.DX_ID = DX.DX_ID 
		LEFT OUTER JOIN ACCOUNT EAR 
		ON EAR.ACCOUNT_ID = HAR.GUARANTOR_ID 
		LEFT OUTER JOIN HSP_ACCT_LAST_UPDATE HARUP 
		ON HARUP.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID 
WHERE
	DX.HSP_ACCOUNT_ID IS NULL AND
	TO_DATE(HARUP.INST_OF_UPDATE_DTTM, 'DD/MM/YYYY') BETWEEN TO_DATE(SYSDATE - 3, 'DD/MM/YYYY') AND
	TO_DATE(SYSDATE - 1, 'DD/MM/YYYY') AND
	HAR.TOT_CHGS > 0 AND
	EAR.ACCOUNT_TYPE_C NOT IN ('101',
	'102') AND
	HAR.ACCT_FIN_CLASS_C != 4 -- Remove self-pay accounts. STSK0769632
UNION
SELECT
	CASE 
		WHEN HAR.HSP_ACCOUNT_ID IS NOT NULL 
		THEN HAR.HSP_ACCOUNT_ID 
		ELSE NULL 
	END AS ACCOUNTNUMBER,
	CASE 
		WHEN HAR.LOC_ID IS NOT NULL 
		THEN HAR.LOC_ID 
		ELSE NULL 
	END AS FACILITYCODE,
	CASE 
		WHEN DX.LINE IS NOT NULL 
		THEN DX.LINE 
		ELSE NULL 
	END AS DIAGNOSISORDER,
	CASE 
		WHEN EDG.REF_BILL_CODE IS NOT NULL 
		THEN EDG.REF_BILL_CODE 
		ELSE NULL 
	END AS DIAGNOSISCODE,
	CASE 
		WHEN POA1.ABBR IS NOT NULL 
		THEN POA1.ABBR 
		ELSE NULL 
	END AS POAINDICATOR,
	CASE 
		WHEN SER2.NPI IS NOT NULL 
		THEN SER2.NPI 
		ELSE NULL 
	END AS DIAGNOSINGPHYSICIANNPI 
FROM
	HSP_ACCOUNT HAR 
		LEFT OUTER JOIN HSP_ACCT_DX_LIST DX 
		ON DX.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID 
		LEFT OUTER JOIN CLARITY_SER_2 SER2 
		ON SER2.PROV_ID = HAR.ATTENDING_PROV_ID 
		LEFT OUTER JOIN ZC_DX_POA POA1 
		ON POA1.DX_POA_C = DX.FINAL_DX_POA_C 
		LEFT OUTER JOIN CLARITY_EDG EDG 
		ON EDG.DX_ID = DX.DX_ID 
		LEFT OUTER JOIN ACCOUNT EAR 
		ON EAR.ACCOUNT_ID = HAR.GUARANTOR_ID 
		LEFT OUTER JOIN HSP_ACCT_LAST_UPDATE HARUP 
		ON HARUP.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID 
WHERE
	TO_DATE(HARUP.INST_OF_UPDATE_DTTM, 'DD/MM/YYYY') BETWEEN TO_DATE(SYSDATE - 3, 'DD/MM/YYYY') AND
	TO_DATE(SYSDATE - 1, 'DD/MM/YYYY') AND
	HAR.TOT_CHGS > 0 AND
	EAR.ACCOUNT_TYPE_C NOT IN ('101',
	'102') AND
	HAR.ACCT_FIN_CLASS_C != 4 AND -- Remove self-pay accounts. STSK0769632
	DX.HSP_ACCOUNT_ID IS NOT NULL 
UNION
SELECT
	CASE 
		WHEN HAR.HSP_ACCOUNT_ID IS NOT NULL 
		THEN HAR.HSP_ACCOUNT_ID 
		ELSE NULL 
	END AS ACCOUNTNUMBER,
	CASE 
		WHEN HAR.LOC_ID IS NOT NULL 
		THEN HAR.LOC_ID 
		ELSE NULL 
	END AS FACILITYCODE,
	CASE 
		WHEN EXTDX.LINE IS NOT NULL 
		THEN EXTDX.LINE 
		ELSE NULL 
	END AS DIAGNOSISORDER,
	CASE 
		WHEN EDG.REF_BILL_CODE IS NOT NULL 
		THEN EDG.REF_BILL_CODE 
		ELSE NULL 
	END AS DIAGNOSISCODE,
	CASE 
		WHEN EXTDX.HSP_ACCOUNT_ID IS NOT NULL AND
		EXTDX.EXT_INJURY_POA_YNU = 'Y' 
		THEN 'Y' 
		ELSE 
		CASE 
			WHEN EXTDX.HSP_ACCOUNT_ID IS NOT NULL AND
			EXTDX.EXT_INJURY_POA_YNU = 'N' 
			THEN 'N' 
			ELSE EXTDX.EXT_INJURY_POA_YNU 
		END 
	END AS POAINDICATOR,
	CASE 
		WHEN SER2.NPI IS NOT NULL 
		THEN SER2.NPI 
		ELSE NULL 
	END DIAGNOSINGPHYSICIANNPI 
FROM
	HSP_ACCOUNT HAR 
		LEFT OUTER JOIN HSP_ACCT_EXTINJ_CD EXTDX 
		ON EXTDX.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID 
		LEFT OUTER JOIN CLARITY_SER_2 SER2 
		ON SER2.PROV_ID = HAR.ATTENDING_PROV_ID 
		LEFT OUTER JOIN CLARITY_EDG EDG 
		ON EDG.DX_ID = EXTDX.EXT_INJURY_DX_ID 
		LEFT OUTER JOIN ACCOUNT EAR 
		ON EAR.ACCOUNT_ID = HAR.GUARANTOR_ID 
		LEFT OUTER JOIN HSP_ACCT_LAST_UPDATE HARUP 
		ON HARUP.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID 
WHERE
	TO_DATE(HARUP.INST_OF_UPDATE_DTTM, 'DD/MM/YYYY') BETWEEN TO_DATE(SYSDATE - 3, 'DD/MM/YYYY') AND
	TO_DATE(SYSDATE - 1, 'DD/MM/YYYY') AND
	HAR.TOT_CHGS > 0 AND
	EAR.ACCOUNT_TYPE_C NOT IN ('101',
	'102') AND
	HAR.ACCT_FIN_CLASS_C != 4 AND -- Remove self-pay accounts. STSK0769632
	EXTDX.HSP_ACCOUNT_ID IS NOT NULL