WITH ANTIB
as
(

SELECT 
cm.MEDICATION_ID
,cm.NAME
,coalesce(rx2.SHORT_NAME, zcsg.NAME) "SHORT_NAME"
,zct.NAME   "THERA_CLASS"
,zcpp.NAME  "PHARM_CLASS"
,cm.FORM
,zcar.NAME  "ADMIN_ROUTE"
,zcps.NAME "PHARM_SUBCLASS"
,gcr.GROUPER_ID
,CASE WHEN gi.PROV_DISPLAY_NAME IS NULL THEN 'Vancomycin' ELSE  gi.PROV_DISPLAY_NAME END "MED_GROUP"

FROM GROUPER_COMPILED_RECORDS gcr
LEFT OUTER JOIN GROUPER_ITEMS gi ON gcr.GROUPER_ID = gi.GROUPER_ID
LEFT OUTER JOIN clarity_medication cm ON gcr.COMPILED_REC_LIST = cm.MEDICATION_ID
LEFT OUTER JOIN ZC_SIMPLE_GENERIC zcsg ON cm.SIMPLE_GENERIC_C = zcsg.SIMPLE_GENERIC_C
LEFT OUTER JOIN RX_MED_TWO rx2 ON cm.MEDICATION_ID = rx2.MEDICATION_ID
LEFT OUTER JOIN ZC_THERA_CLASS zct ON cm.THERA_CLASS_C = zct.THERA_CLASS_C
LEFT OUTER JOIN ZC_PHARM_CLASS zcpp ON cm.PHARM_CLASS_C = zcpp.PHARM_CLASS_C
LEFT OUTER JOIN ZC_ADMIN_ROUTE zcar ON rx2.ADMIN_ROUTE_C = zcar.MED_ROUTE_C
LEFT OUTER JOIN ZC_PHARM_SUBCLASS zcps ON cm.PHARM_SUBCLASS_C = zcps.PHARM_SUBCLASS_C
WHERE 
gcr.GROUPER_ID = 115893
--gcr.GROUPER_ID IN (115893,115895,408117,115899,115899,115901,115905)


)
,FILLDAT
AS
(
   SELECT --*
   dd.CALENDAR_DT
   ,dd.DAY_OF_WEEK
   ,dd.WEEK_NUMBER
   ,dd.DAY_OF_MONTH
   ,dd.MONTH_NAME
   ,dd."YEAR"
   ,dd.YEAR_MONTH
   ,dd.weekend_yn
   ,dd.HOLIDAY_YN
   ,dd.MONTHNAME_YEAR
   ,dd.YEAR_END_DT
   FROM DATE_DIMENSION dd
   WHERE
       dd.CALENDAR_DT >= TRUNC (ADD_MONTHS (CURRENT_DATE , -1), 'MM') 
  --        AND mared.SCHEDULED_TIME < sysdate
        and dd.CALENDAR_DT < TRUNC (ADD_MONTHS (CURRENT_DATE,0 ), 'MM') 
--        and dd.CALENDAR_DT < TRUNC (ADD_MONTHS (CURRENT_DATE , -1), 'MM') 

   
)   
  

SELECT 
fdot.TAKEN_DATE
,pat.PAT_MRN_ID
,CASE when TRUNC((TRUNC(fdot.TAKEN_DATE)  - pat.BIRTH_DATE) / 365.25) > 17 THEN 'ADULT' ELSE 'PEDS' END "AGEGROUP"
,om.PAT_ENC_CSN_ID
,fdot.DEPARTMENT_ID
,dep.DEPARTMENT_NAME 
,zcps.NAME  "SERVICE"
,fdot.MEDICATION_ID
,zcar.NAME "ROUTE"
,fdot.DRUG_CODE
,serauth.PROV_NAME  "AUTHORIZED_PROVIDER"
,serord.PROV_NAME  "ORDER_PROVIDER"
,seratt.PROV_NAME  "ATTENDING_PROVIDER"
,fdot.DAY_OF_THERAPY_IV
,fdot.DAY_OF_THERAPY_IM
,fdot.DAY_OF_THERAPY_DIGESTIVE
,fdot.DAY_OF_THERAPY_RESPIRATORY
,fdot.ORDER_ID
   ,dat.CALENDAR_DT
   ,dat.DAY_OF_WEEK
   ,dat.WEEK_NUMBER
   ,dat.DAY_OF_MONTH
   ,dat.MONTH_NAME
   ,dat."YEAR"
   ,dat.YEAR_MONTH
   ,dat.weekend_yn
   ,dat.HOLIDAY_YN
   ,dat.MONTHNAME_YEAR
   ,dat.YEAR_END_DT

--,fdot.UPDATE_DATE
--,pat3.IS_TEST_PAT_YN
--,extract(month from fdot.TAKEN_DATE) "TAKEN_MONTH"
--,adt.EVENT_TYPE_C
--,adt.EVENT_SUBTYPE_C
--,adt.EFFECTIVE_TIME
FROM CLARITY_ADT adt
INNER JOIN order_med om ON adt.PAT_ENC_CSN_ID = om.PAT_ENC_CSN_ID
INNER JOIN F_DOT_CONTRIB_ORDS_DEPT fdot ON om.ORDER_MED_ID = fdot.ORDER_ID
inner join ANTIB anti on fdot.medication_id = anti.MEDICATION_ID
LEFT OUTER JOIN FILLDAT dat ON fdot.TAKEN_DATE = dat.CALENDAR_DT
--inner join ORDER_MEDINFO ominfo ON om.ORDER_MED_ID = ominfo.ORDER_MED_ID
--LEFT OUTER join order_medmixinfo ommix ON om.ORDER_MED_ID = ommix.ORDER_MED_ID AND ommix.LINE = 1
--LEFT OUTER JOIN CLARITY_MEDICATION cm ON COALESCE( ommix.MEDICATION_ID, ominfo.DISPENSABLE_MED_ID) = cm.MEDICATION_ID
LEFT OUTER JOIN IP_FREQUENCY freq ON om.HV_DISCR_FREQ_ID=freq.FREQ_ID
LEFT OUTER JOIN ZC_ADMIN_ROUTE zcar ON om.MED_ROUTE_C=zcar.MED_ROUTE_C
LEFT OUTER JOIN clarity_dep dep ON fdot.DEPARTMENT_ID = dep.DEPARTMENT_ID
LEFT OUTER JOIN zc_pat_service zcps ON fdot.PAT_HOSP_SERV_C = zcps.HOSP_SERV_C
LEFT OUTER JOIN clarity_ser serauth ON fdot.AUTHG_PROV_ID = serauth.PROV_ID
LEFT OUTER JOIN CLARITY_SER seratt ON fdot.ATTEND_PROV_ID = seratt.PROV_ID
LEFT OUTER JOIN clarity_ser serord ON fdot.ORDER_PROV_ID = serord.PROV_ID
INNER JOIN patient pat ON fdot.PAT_ID = pat.PAT_ID
INNER JOIN patient_3 pat3 ON pat.PAT_ID = pat3.PAT_ID

WHERE
adt.EVENT_SUBTYPE_C <> 2  ---- deleted
AND adt.EVENT_TYPE_C IN (1,3)
--AND TRUNC( fdot.TAKEN_DATE) >= '1-jan-2021' 
--AND TRUNC( fdot.TAKEN_DATE) <= '31-jan-2021' 
AND fdot.TAKEN_DATE >= dat.CALENDAR_DT 
AND fdot.TAKEN_DATE <= dat.CALENDAR_DT
AND pat3.IS_TEST_PAT_YN <> 'Y'
AND fdot.DEPARTMENT_ID = 1000108008
