WITH
	CVGLIST AS 
	(	SELECT
			HTR.TX_ID,
			CVGLIST.LINE 
		FROM
			HSP_TRANSACTIONS HTR 
			LEFT OUTER JOIN HSP_BUCKET BKT 
			ON BKT.BUCKET_ID = HTR.BUCKET_ID 
			LEFT OUTER JOIN HSP_ACCT_CVG_LIST CVGLIST 
			ON CVGLIST.HSP_ACCOUNT_ID = BKT.HSP_ACCOUNT_ID AND
			CVGLIST.COVERAGE_ID = BKT.COVERAGE_ID 
		WHERE
			BKT.BUCKET_ID IS NOT NULL) 
SELECT
	CASE 
		WHEN HTR.HSP_ACCOUNT_ID IS NOT NULL 
		THEN HTR.HSP_ACCOUNT_ID 
		ELSE NULL 
	END AS ACCOUNTNUMBER,
	CASE 
		WHEN HTR.REVENUE_LOC_ID IS NOT NULL 
		THEN HTR.REVENUE_LOC_ID 
		ELSE NULL 
	END AS FACILITYCODE,
	CASE 
		WHEN HTR.TX_ID IS NOT NULL 
		THEN HTR.TX_ID 
		ELSE NULL 
	END AS FINANCIALTRANSACTIONID,
	CASE 
		WHEN EMP.USER_ID IS NOT NULL 
		THEN EMP.USER_ID 
		ELSE NULL 
	END AS USERID,
	CASE 
		WHEN EMP.NAME IS NOT NULL 
		THEN EMP.NAME 
		ELSE NULL 
	END AS USERNAME,
	CASE 
		WHEN TXTYPE.NAME IS NOT NULL 
		THEN TXTYPE.NAME 
		ELSE NULL 
	END AS TRANSACTIONTYPE,
	CASE 
		WHEN HTR.TX_POST_DATE IS NOT NULL 
		THEN TO_CHAR(TRUNC(HTR.TX_POST_DATE), 'mm/dd/yyyy') 
		ELSE NULL 
	END AS TRANSACTIONDATE,
	CASE 
		WHEN HTR.TX_POST_DATE IS NOT NULL 
		THEN TO_CHAR(TRUNC(HTR.TX_POST_DATE), 'mm/dd/yyyy') 
		ELSE NULL 
	END AS POSTDATE,
	CASE 
		WHEN EAP.PROC_CODE IS NOT NULL 
		THEN EAP.PROC_CODE 
		ELSE NULL 
	END AS FINANCIALCODE,
	CASE 
		WHEN EAP.PROC_NAME IS NOT NULL 
		THEN EAP.PROC_NAME 
		ELSE NULL 
	END AS FINANCIALCODEDESCRIPTION,
	CASE 
		WHEN HTR.TX_AMOUNT IS NOT NULL 
		THEN HTR.TX_AMOUNT 
		ELSE NULL 
	END AS FINANCIALAMOUNT,
	CASE 
		WHEN BKT.BENEFIT_PLAN_ID IS NOT NULL 
		THEN BKT.BENEFIT_PLAN_ID 
		ELSE NULL 
	END AS INSURANCEPLANCODE,
	CASE 
		WHEN BILLST.NAME IS NOT NULL 
		THEN BILLST.NAME 
		ELSE NULL 
	END AS ACCOUNTSTATUS,
	CASE 
		WHEN HTR.INT_CONTROL_NUMBER IS NOT NULL 
		THEN HTR.INT_CONTROL_NUMBER 
		ELSE NULL 
	END AS INTERNALCONTROLNUMBER,
	CASE 
		WHEN CVGLIST.LINE IS NOT NULL 
		THEN CVGLIST.LINE 
		ELSE NULL 
	END AS INSURANCEORDER 
FROM
	HSP_TRANSACTIONS HTR 
		LEFT OUTER JOIN ZC_TX_TYPE_HA TXTYPE 
		ON TXTYPE.TX_TYPE_HA_C = HTR.TX_TYPE_HA_C 
		LEFT OUTER JOIN ZC_PAYMENT_SRC_HA PAYSR 
		ON PAYSR.PAYMENT_SRC_HA_C = HTR.PAYMENT_SRC_HA_C 
		LEFT OUTER JOIN HSP_BUCKET BKT 
		ON BKT.BUCKET_ID = HTR.BUCKET_ID 
		LEFT OUTER JOIN HSP_ACCOUNT HAR 
		ON HAR.HSP_ACCOUNT_ID = HTR.HSP_ACCOUNT_ID 
		LEFT OUTER JOIN ACCOUNT EAR 
		ON EAR.ACCOUNT_ID = HAR.GUARANTOR_ID 
		LEFT OUTER JOIN ZC_ACCT_BILLSTS_HA BILLST 
		ON BILLST.ACCT_BILLSTS_HA_C = HAR.ACCT_BILLSTS_HA_C 
		LEFT OUTER JOIN CVGLIST 
		ON CVGLIST.TX_ID = HTR.TX_ID 
		LEFT OUTER JOIN CLARITY_EAP EAP 
		ON EAP.PROC_ID = HTR.PROC_ID 
		LEFT OUTER JOIN CLARITY_EMP EMP 
		ON EMP.USER_ID = HTR.USER_ID 
		LEFT OUTER JOIN HSP_ACCT_LAST_UPDATE HARUP 
		ON HARUP.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID 
WHERE
	TO_DATE(HARUP.INST_OF_UPDATE_DTTM, 'DD/MM/YYYY') BETWEEN TO_DATE(SYSDATE - 3, 'DD/MM/YYYY') AND
	TO_DATE(SYSDATE - 1, 'DD/MM/YYYY') AND
	HTR.TX_ID IS NOT NULL AND
	HTR.TX_TYPE_HA_C IN (2,
	3,
	4) AND
	HAR.TOT_CHGS > 0 AND
	EAR.ACCOUNT_TYPE_C NOT IN ('101',
	'102')
	AND HAR.ACCT_FIN_CLASS_C != 4 -- Remove self-pay accounts. STSK0769632