   SELECT
   mar.ORDER_MED_ID
   ,MIN(mar.TAKEN_TIME)  "FIRST_TAKEN_DTTM"

   FROM ORDER_MED om ON mar.ORDER_MED_ID = om.ORDER_MED_ID
   LEFT OUTER JOIN MAR_ADMIN_INFO mar ON ord2.ORDER_MED_ID = mar.ORDER_MED_ID
   WHERE
   mar.MAR_ACTION_C IN ('1', '6', '102', '105', '113', '114', '115','1002')
   AND om.ORDERING_DATE >= '1-jul-2020'
   GROUP BY mar.ORDER_MED_ID
