/*          
H31a. How many unique patients  received temporal lobe epilepsy surgery including laser ablation (See code list- must have at least one diagnosis 
code and at least one procedure code.) in 2023? [If none, please enter 0.] Of those, how many achieved Engel Class 1-2 after 12 months? 
[Please exclude patients with brain tumors and vascular lesions.]
    
    ________ (1) Unique patients 2023 
    ________ (2) Number achieving Engel class 1-2 after 12 months 
    ________ (3) Percent achieving Engle class 1-2 after 12 months 
    
*/

SELECT DISTINCT --HA.HSP_ACCOUNT_ID,  
      PAT.PAT_MRN_ID "MRN", PAT.PAT_NAME 
     , TO_CHAR(TRUNC(COALESCE(PEH.HOSP_ADMSN_TIME, PE.HOSP_ADMSN_TIME, HA.ADM_DATE_TIME)),'MM/DD/YYYY')  "ADMIT DT"
     , TO_CHAR(TRUNC(COALESCE(PEH.HOSP_DISCH_TIME, PE.HOSP_DISCHRG_TIME, HA.DISCH_DATE_TIME )),'MM/DD/YYYY') "DISCH DT"  
     , TO_CHAR(PAT.BIRTH_DATE, 'MM/DD/YYYY') "PATIENT DOB"
     , TO_CHAR(PAT.DEATH_DATE, 'MM/DD/YYYY') "DEATH DT"
     , TRUNC(MONTHS_BETWEEN(TRUNC(COALESCE( HA.ADM_DATE_TIME, PE.HOSP_ADMSN_TIME, PEH.HOSP_ADMSN_TIME)),TRUNC(PAT.BIRTH_DATE))/12) "ADMIT AGE"    
   --  , EDG.REF_BILL_CODE "DX CODE" 
 ,ICD.REF_BILL_CODE "PROC CODE"
     , SER.PROV_NAME "PROVIDER"
     , Z.NAME "SPECIALTY" 
   ---  , AP.PROV_NAME "ATTENDING" , AP.NAME "ATND SPCLTY"
  -- , DX_EXCL.REF_BILL_CODE
  FROM CLARITY.HSP_ACCOUNT HA
  LEFT JOIN CLARITY.HSP_ACCT_SBO SBO ON SBO.HSP_ACCOUNT_ID = HA.HSP_ACCOUNT_ID AND SBO.SBO_HAR_TYPE_C = 0 -- MIXED ONLY
  LEFT JOIN CLARITY.PATIENT PAT ON PAT.PAT_ID = HA.PAT_ID
  LEFT JOIN CLARITY.PAT_ENC PE ON PE.PAT_ENC_CSN_ID = HA.PRIM_ENC_CSN_ID
  LEFT JOIN CLARITY.PAT_ENC_HSP PEH ON PEH.PAT_ENC_CSN_ID = HA.PRIM_ENC_CSN_ID
  LEFT JOIN CLARITY.HSP_ACCT_DX_LIST DX ON DX.HSP_ACCOUNT_ID = HA.HSP_ACCOUNT_ID
-- DIAGNOSIS  
  LEFT JOIN CLARITY.CLARITY_EDG EDG ON EDG.DX_ID = DX.DX_ID 
  LEFT JOIN CLARITY.ZC_ACCT_CLASS_HA AC ON AC.ACCT_CLASS_HA_C = HA.ACCT_CLASS_HA_C         

-- PROVIDER
   LEFT JOIN CLARITY.CLARITY_SER SER ON SER.PROV_ID = HA.ATTENDING_PROV_ID           
   LEFT JOIN CLARITY.CLARITY_SER_SPEC SPEC ON SPEC.PROV_ID = SER.PROV_ID
   LEFT JOIN CLARITY.ZC_SPECIALTY Z ON Z.SPECIALTY_C = SPEC.SPECIALTY_C       

 -- ICD9 PROCEDURES
   LEFT JOIN CLARITY.HSP_ACCT_PX_LIST PX ON PX.HSP_ACCOUNT_ID = HA.HSP_ACCOUNT_ID 
   LEFT JOIN CLARITY.CL_ICD_PX ICD ON ICD.ICD_PX_ID = PX.FINAL_ICD_PX_ID        
 -- CPT CODES
   LEFT JOIN CLARITY.HSP_ACCT_CPT_CODES CPT ON CPT.HSP_ACCOUNT_ID = HA.HSP_ACCOUNT_ID   
   LEFT JOIN CLARITY_EAP_OT                EOT ON CPT.CPT_CODE         = EOT.CPT_CODE   
   LEFT JOIN CLARITY_EAP                   EAP ON EOT.PROC_ID          = EAP.PROC_ID      

-- LEFT OUTER JOIN  -- DX EXCLUSIONS
--        (SELECT DX2.HSP_ACCOUNT_ID, EDG2.DX_ID, EDG2.REF_BILL_CODE
--        FROM HSP_ACCT_DX_LIST DX2
--            INNER JOIN CLARITY_EDG EDG2 ON DX2.DX_ID = EDG2.DX_ID
--        WHERE 
--           EDG2.REF_BILL_CODE IN                        
--                                ('C70.0','C70.9','C71.0','C71.1','C71.2','C71.3','C71.4','C71.5','C71.6','C71.7',
--                        'C71.8','C71.9','C72.20','C72.21','C72.22','C72.30','C72.31','C72.32','C72.40','C72.41',
--                        'C72.42','C72.50','C72.59','C75.1','C75.2','C75.3','C79.31','C79.32','D32.0','D32.9',
--                        'D33.0','D33.1','D33.2','D33.3','D35.2','D35.3','D35.4','D42.0','D42.9','D43.0',
--                        'D43.1','D43.2','D43.3','D44.3','D44.4','D44.5','D49.6')
--                        
--        ) DX_EXCL ON HA.HSP_ACCOUNT_ID = DX_EXCL.HSP_ACCOUNT_ID
    
 WHERE HA.LOC_ID = 100000 
   AND HA.ACCT_BILLSTS_HA_C NOT IN (99, 40) -- EXCLUDE COMBINED AND VOIDED ACCOUNTS  
  -- PATIENT AGE AT ADMISSION CANNOT BE 18 OR OLDER
   AND TRUNC(MONTHS_BETWEEN(TRUNC(COALESCE( HA.ADM_DATE_TIME, PE.HOSP_ADMSN_TIME, PEH.HOSP_ADMSN_TIME)),TRUNC(PAT.BIRTH_DATE))/12) < 18 
   AND TRUNC(COALESCE( PE.HOSP_DISCHRG_TIME, HA.DISCH_DATE_TIME, PE.HOSP_ADMSN_TIME, HA.ADM_DATE_TIME))
              BETWEEN '01-JAN-2023' AND '01-JAN-2024'    
    --AND DX_EXCL.HSP_ACCOUNT_ID IS NULL
--* DX CODES 
   AND EDG.REF_BILL_CODE IN ('G40.011','G40.019','G40.111','G40.119','G40.211','G40.219','G40.311','G40.319','G40.411','G40.419','G40.803','G40.804','G40.813','G40.814',
'G40.823','G40.824','G40.833','G40.834','G40.843 ','G40.844 ','G40.911','G40.919','G40.A11','G40.A19','G40.B11','G40.B19','G40.C11 ','G40.C19')
        
--* PROCEDURES
 
  AND (ICD.REF_BILL_CODE IN 
  --('00B00ZZ', '00B03ZZ', '00B04ZZ', '00B70ZZ', '00B73ZZ', '00B74ZZ', '00T73ZZ', '00T74ZZ', '00570ZZ', '00573ZZ',
  --                  '00574ZZ', '00800ZZ', '00803ZZ', '00804ZZ', '00870ZZ', '00873ZZ', '00874ZZ', '4A1002Z', '4A1004Z', '4A100BZ')
                    
                            ('00B00ZX','00B00ZZ','00B03ZX','00B03ZZ','00B04ZX','00B04ZZ','00B70ZZ','00B73ZZ','00B74ZZ','00T70ZZ','00T73ZZ','00T74ZZ')
                    
        OR CPT.CPT_CODE IN ('61541','61543')
 )
       
 ORDER BY 1  