SELECT
	HAR.HSP_ACCOUNT_ID AS ACCOUNTNUMBER,
	CASE 
		WHEN HAR.LOC_ID IS NOT NULL 
		THEN HAR.LOC_ID 
		ELSE NULL 
	END                    AS FACILITYCODE,
	CASE 
		WHEN CPT.CPT_CODE_DATE IS NOT NULL 
		THEN TO_CHAR(TRUNC(CPT.CPT_CODE_DATE), 'mm/dd/yyyy') 
		ELSE NULL 
	END                    AS SERVICEDATE,
	CASE 
		WHEN CPT.LINE IS NOT NULL 
		THEN CPT.LINE 
		ELSE NULL 
	END                    AS HIMORDER,
	CASE 
		WHEN CPT.CPT_CODE IS NOT NULL 
		THEN CPT.CPT_CODE 
		ELSE NULL 
	END                    AS HIMCODE,
	CASE 
		WHEN LENGTH(CPT.CPT_MODIFIERS) > 4 
		THEN SUBSTR(LTRIM(CPT.CPT_MODIFIERS), 1, 2) 
		WHEN LENGTH(CPT.CPT_MODIFIERS) = 2 
		THEN SUBSTR(LTRIM(CPT.CPT_MODIFIERS), 1, 2) 
		ELSE NULL 
	END                    AS HIMMODIFIER1,
	CASE 
		WHEN LENGTH(CPT.CPT_MODIFIERS) > 4 
		THEN SUBSTR(RTRIM(CPT.CPT_MODIFIERS), -2, 2) 
		ELSE NULL 
	END                    AS HIMMODIFIER2,
	CASE 
		WHEN SER2.NPI IS NOT NULL 
		THEN SER2.NPI 
		ELSE NULL 
	END                    AS RENDERINGPHYSICIANNPI 
FROM
	HSP_ACCOUNT HAR 
		LEFT OUTER JOIN ACCOUNT EAR 
		ON EAR.ACCOUNT_ID = HAR.GUARANTOR_ID 
		LEFT OUTER JOIN HSP_ACCT_CPT_CODES CPT 
		ON CPT.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID 
		LEFT OUTER JOIN CLARITY_SER_2 SER2 
		ON SER2.PROV_ID = CPT.CPT_PERF_PROV_ID 
		LEFT OUTER JOIN HSP_ACCT_LAST_UPDATE HARUP 
		ON HARUP.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID 
WHERE
	TO_DATE(HARUP.INST_OF_UPDATE_DTTM, 'DD/MM/YYYY') BETWEEN TO_DATE(SYSDATE - 3, 'DD/MM/YYYY') AND
	TO_DATE(SYSDATE - 1, 'DD/MM/YYYY') AND
	EAR.ACCOUNT_TYPE_C NOT IN ('101',
	'102') AND
	HAR.ACCT_FIN_CLASS_C != 4 AND -- Remove self-pay accounts. STSK0769632
	CPT.HSP_ACCOUNT_ID IS NOT NULL AND
	HAR.NUM_OF_CHARGES > 0