 SELECT 
   vrx.REPORT_DATE
 , vrx.CHARGE
 , vrx.BILLING_QUANTITY
 , vrx.MEDICATION_NM_WID
 , vrx.SERVICE_DATE
 , pat.PAT_NAME
 , pat.PAT_MRN_ID
 , pat.BIRTH_DATE
 , om.PAT_ENC_CSN_ID
 , fc.FINANCIAL_CLASS_NAME    "ORIGINAL_FC_DESCRIPTION"
 , ucl.HOSPITAL_ACCOUNT_ID
 , fc_hsp.FINANCIAL_CLASS_NAME  "HAR_FC_DESCRIPTION"
 , hsp_acct.ADM_DATE_TIME
 , hsp_acct.DISCH_DATE_TIME
 , zc_base.NAME   "BASE_CLASS"
 , zc_clas.NAME    "HSP_CLASS"
 , vrx.ORDER_NM_WID
 , cm.GENERIC_NAME
 ,coalesce(rx2.SHORT_NAME, zcg.NAME) "SHORT_NAME"
 , har.PROCEDURE_DESC
 , vrx.REVENUE_LOCATION_NAME
 , vrx.CHARGE_DEPARTMENT_NM_WID
 , parloc.LOC_NAME  "PARENT_LOCATION"
 , vrx.REVENUE_CODE_ID
 , vrx.REVENUE_CODE_NAME
 , vrx.UCL_STATUS
 , har.PROC_ID
 , CLARITY_EAP_hsp.PROC_CODE
 , CLARITY_EAP_hsp.PROC_NAME
 , ucl.UCL_ID
 , rx3.MED_NAME_SUFFIX
 , cm.FORM
 , cm.ROUTE
 ,har.TX_POST_DATE
 FROM  V_RX_CHARGES vrx 
 INNER JOIN PATIENT pat 
 INNER JOIN ORDER_MED om ON pat.PAT_ID=om.PAT_ID ON vrx.ORDER_ID=om.ORDER_MED_ID 
 INNER JOIN CLARITY_UCL ucl ON vrx.UCL_ID=ucl.UCL_ID 
 LEFT OUTER JOIN CLARITY_MEDICATION cm ON vrx.MEDICATION_ID=cm.MEDICATION_ID 
 LEFT OUTER JOIN rx_med_one rx1 ON cm.MEDICATION_ID = rx1.MEDICATION_ID
 LEFT OUTER JOIN rx_med_three rx3 ON cm.MEDICATION_ID = rx3.MEDICATION_ID
 LEFT OUTER JOIN RX_MED_TWO rx2 ON cm.MEDICATION_ID = rx2.MEDICATION_ID
 LEFT OUTER JOIN zc_simple_generic zcg ON cm.SIMPLE_GENERIC_C = zcg.SIMPLE_GENERIC_C
 LEFT OUTER JOIN ZC_PREPARE_TYPE zcpt ON rx1.PREPARATION_TYPE_C = zcpt.PREPARE_TYPE_C
 LEFT OUTER JOIN PAT_ACCT_CVG pat_cvg ON ucl.PATIENT_ID=pat_cvg.PAT_ID AND ucl.ACCOUNT_ID=pat_cvg.ACCOUNT_ID 
 LEFT OUTER JOIN HSP_ACCOUNT hsp_acct ON ucl.HOSPITAL_ACCOUNT_ID=hsp_acct.HSP_ACCOUNT_ID 
 LEFT OUTER JOIN HSP_TRANSACTIONS har ON ucl.UCL_ID=har.CHG_ROUTER_SRC_ID AND hsp_acct.HSP_ACCOUNT_ID=har.HSP_ACCOUNT_ID 
 LEFT OUTER JOIN CLARITY_FC fc_hsp ON hsp_acct.ACCT_FIN_CLASS_C=fc_hsp.FINANCIAL_CLASS 
 LEFT OUTER JOIN ZC_ACCT_BASECLS_HA zc_base ON hsp_acct.ACCT_BASECLS_HA_C=zc_base.ACCT_BASECLS_HA_C 
 LEFT OUTER JOIN ZC_ACCT_CLASS_HA zc_clas ON hsp_acct.ACCT_CLASS_HA_C=zc_clas.ACCT_CLASS_HA_C
 LEFT OUTER JOIN CLARITY_FC fc ON pat_cvg.FIN_CLASS=fc.FINANCIAL_CLASS 
 LEFT OUTER JOIN F_ARHB_INACTIVE_TX f_arhb ON har.TX_ID=f_arhb.TX_ID 
 LEFT OUTER JOIN CL_UB_REV_CODE ub_revcod ON har.UB_REV_CODE_ID=ub_revcod.UB_REV_CODE_ID
 LEFT OUTER JOIN CLARITY_EAP CLARITY_EAP_hsp ON har.PROC_ID=CLARITY_EAP_hsp.PROC_ID
 LEFT OUTER JOIN clarity_dep dep ON vrx.CHARGE_DEPARTMENT_ID = dep.DEPARTMENT_ID
 LEFT OUTER JOIN clarity_loc loc ON dep.REV_LOC_ID = loc.LOC_ID
 LEFT OUTER JOIN clarity_loc parloc ON loc.HOSP_PARENT_LOC_ID = parloc.LOC_ID
 WHERE 
  cm.ROUTE IN ('Injection', 'Intramuscular', 'Intravenous', 'Subcutaneous')
--    ( cm.ROUTE IN ('Injection', 'Intramuscular', 'Intravenous', 'Subcutaneous') OR cm.ROUTE IS NULL) 

  AND vrx.UCL_STATUS<>'VOIDED'
  AND vrx.CHARGE<>0 
  AND vrx.BILLING_QUANTITY>0
  AND  NOT ( hsp_acct.ACCT_BILLSTS_HA_C=40 OR hsp_acct.ACCT_BILLSTS_HA_C=99 )
  AND f_arhb.IS_REVERSAL IS  NULL 
--  AND vrx.REPORT_DATE >= EPIC_UTIL.EFN_DIN('{?Begin Date}') 
--  AND  vrx.REPORT_DATE <= EPIC_UTIL.EFN_DIN('{?End Date}') 
--  AND  vrx.SERVICE_DATE>='1-Oct-2021' AND vrx.SERVICE_DATE<'5-Oct-2021'
    AND  har.TX_POST_DATE >='1-Oct-2021' AND har.TX_POST_DATE <'5-Oct-2021'

--  AND ucl.HOSPITAL_ACCOUNT_ID = 441914570
 ORDER BY vrx.CHARGE, vrx.MEDICATION_NM_WID, pat.PAT_NAME, pat.PAT_MRN_ID, ucl.HOSPITAL_ACCOUNT_ID