SELECT
	HAR.HSP_ACCOUNT_ID AS ACCOUNTNUMBER,
	CASE 
		WHEN HAR.LOC_ID IS NOT NULL 
		THEN HAR.LOC_ID 
		ELSE NULL 
	END                    AS FACILITYCODE,
	CASE 
		WHEN CVG.LINE IS NOT NULL 
		THEN CVG.LINE 
		ELSE NULL 
	END                    AS INSURANCECOB,
	CASE 
		WHEN EPP.BENEFIT_PLAN_ID IS NOT NULL 
		THEN EPP.BENEFIT_PLAN_ID 
		ELSE NULL 
	END                    AS INSURANCEPLANCODE,
	CASE 
		WHEN EPP.BENEFIT_PLAN_NAME IS NOT NULL 
		THEN EPP.BENEFIT_PLAN_NAME 
		ELSE NULL 
	END                    AS INSURANCEPLANNAME,
	CASE 
		WHEN COVERAGE.GROUP_NUM IS NOT NULL 
		THEN COVERAGE.GROUP_NUM 
		ELSE NULL 
	END                    AS GROUPNUMBER,
	CASE 
		WHEN COVERAGE.GROUP_NAME IS NOT NULL 
		THEN COVERAGE.GROUP_NAME 
		ELSE NULL 
	END                    AS GROUPNAME
FROM
	HSP_ACCOUNT HAR 
		LEFT OUTER JOIN HSP_ACCT_CVG_LIST CVG 
		ON CVG.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID 
		LEFT OUTER JOIN COVERAGE COVERAGE 
		ON COVERAGE.COVERAGE_ID = CVG.COVERAGE_ID 
		LEFT OUTER JOIN CLARITY_EPP EPP 
		ON EPP.BENEFIT_PLAN_ID = COVERAGE.PLAN_ID 
		LEFT OUTER JOIN ACCOUNT EAR 
		ON EAR.ACCOUNT_ID = HAR.GUARANTOR_ID 
		LEFT OUTER JOIN CLARITY_FC FC 
		ON FC.FINANCIAL_CLASS = HAR.ACCT_FIN_CLASS_C 
		LEFT OUTER JOIN HSP_ACCT_LAST_UPDATE HARUP 
		ON HARUP.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID 
WHERE
	TO_DATE(HARUP.INST_OF_UPDATE_DTTM, 'DD/MM/YYYY') BETWEEN TO_DATE(SYSDATE - 3, 'DD/MM/YYYY') AND
	TO_DATE(SYSDATE - 1, 'DD/MM/YYYY') AND
	HAR.NUM_OF_CHARGES > 0 AND
	EAR.ACCOUNT_TYPE_C NOT IN ('101',
	'102')
	AND HAR.ACCT_FIN_CLASS_C != 4 -- Remove self-pay accounts. STSK0769632