SELECT
    CL_SPHR.SMARTPHRASE_NAME AS "SmartPhrase Name",
    NOTE_SMARTPHRASES.CONTACT_DATE as "SmartPhrase Usage Date",
    NOTE_SMARTPHRASES.NAME as "SmartPhrase User",
    PATIENT.PAT_MRN_ID as "MRN_ID",
    PATIENT.PAT_NAME as "Patient",
    NOTE_SMARTPHRASES.SMARTPHRASES_ID,
    PAT_ENC.ENC_TYPE_C,
    zcet.NAME  "ENC_TYPE"
    
    
    

FROM PAT_ENC
LEFT JOIN PATIENT ON PAT_ENC.PAT_ID = PATIENT.PAT_ID
Inner JOIN (
    SELECT 
        NOTE_SMARTPHRASE_IDS.*,
        HNO_INFO.PAT_ENC_CSN_ID, 
        CLARITY_EMP.NAME,
        ROW_NUMBER() OVER (PARTITION BY HNO_INFO.PAT_ENC_CSN_ID ORDER BY NOTE_SMARTPHRASE_IDS.CONTACT_DATE_REAL ASC) AS SEQ
    FROM NOTE_SMARTPHRASE_IDS
    LEFT JOIN HNO_INFO ON NOTE_SMARTPHRASE_IDS.NOTE_ID = HNO_INFO.NOTE_ID
    LEFT JOIN CLARITY_EMP ON HNO_INFO.CURRENT_AUTHOR_ID = CLARITY_EMP.USER_ID 
    LEFT OUTER JOIN CLARITY_SER ser ON CLARITY_EMP.USER_ID = ser.USER_ID
--    WHERE 
--   (SMARTPHRASES_ID IN {?SmartPhrase List} '0' OR SMARTPHRASES_ID IN {?SmartPhrase List})
--        WHERE SMARTPHRASES_ID IN (516748,514224,514734,514735,590437,461161)
    WHERE ser.RPT_GRP_TWO = 'CPHT PHARMACY TECHNICIAN'
) NOTE_SMARTPHRASES ON PAT_ENC.PAT_ENC_CSN_ID = NOTE_SMARTPHRASES.PAT_ENC_CSN_ID AND NOTE_SMARTPHRASES.SEQ = 1


LEFT JOIN CL_SPHR ON NOTE_SMARTPHRASES.SMARTPHRASES_ID = CL_SPHR.SMARTPHRASE_ID
LEFT OUTER JOIN ZC_DISP_ENC_TYPE zcet ON PAT_ENC.ENC_TYPE_C = zcet.DISP_ENC_TYPE_C

WHERE 
 NOTE_SMARTPHRASES.CONTACT_DATE >= '1-oct-2021' 
 AND NOTE_SMARTPHRASES.CONTACT_DATE <= '25-oct-2021'

-- NOTE_SMARTPHRASES.CONTACT_DATE >= EPIC_UTIL.EFN_DIN('{?Start Date}') 
-- AND NOTE_SMARTPHRASES.CONTACT_DATE <= EPIC_UTIL.EFN_DIN('{?End Date}')
 AND NOTE_SMARTPHRASES.NOTE_ID IS NOT NULL 


--SELECT *
--FROM CLARITY_SER ser
--WHERE
----ser.PROV_NAME LIKE '%KEBRIA%'
--ser.RPT_GRP_TWO = 'CPHT PHARMACY TECHNICIAN'