
----CREATE PROCEDURE [dbo].[usp_Revint_GetHospitalAccounts]

----AS 


--/*****************************************************************************************

--	DESCRIPTION: THIS STORED PROCEDURE PRESENTS HOSPITAL BILLING ENCOUNTER EXTRACT DATA. 



--*****************************************************************************************/
BEGIN

	USE CLARITY

END
;

--Variables for Recurring/Incremental phase
DECLARE @CurDate DATETIME
DECLARE @BeginDate DATETIME
SET @CurDate = CONVERT(DATETIME, DATEDIFF(DAY, 0, GETDATE()))
SET @BeginDate = DATEADD(DAY,-14,@CurDate) --To modify the lookback period, set the negative integer to the desired number of days (-14 is the default, looking back 14 days)
;

WITH CTE_ACCT_LIST
  AS
  (
        SELECT DISTINCT	HAR.HSP_ACCOUNT_ID
        FROM    CLARITY.dbo.HSP_ACCOUNT AS HAR
        INNER JOIN CLARITY.dbo.HSP_TRANSACTIONS AS HTR     -- Should be good for HB accounts and exclude PB accounts
                ON HTR.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID
		INNER JOIN Clarity.dbo.HSP_ACCT_LAST_UPDATE AS HALU 
                ON HTR.HSP_ACCOUNT_ID = halu.HSP_ACCOUNT_ID
        --WHERE HALU.INST_OF_UPDATE_DTTM >= @BeginDate --Used for Recurring/Incremental phase, comment out for Testing/Historical phase
        WHERE HAR.DISCH_DATE_TIME BETWEEN @STARTDATE AND @ENDDATE --Used for Testing/Historical phase, comment out for Recurring/Incremental phase
	)			
,CTE_BUCKET AS
(
	SELECT 	BKT.HSP_ACCOUNT_ID
       ,'LAST_CLM_INV_NUM'=      MAX(BKT.LAST_CLM_INV_NUM)
       ,'FIRST_CLAIM_DATE' =     MIN(BKT.FIRST_CLAIM_DATE)
       ,'FST_EXT_CLM_SENT_DT'=     MIN(BKT.FST_EXT_CLM_SENT_DT)
       ,'LAST_CLAIM_DATE' =      MAX(BKT.LAST_CLAIM_DATE)
    FROM  CTE_ACCT_LIST TAL
    INNER JOIN CLARITY.dbo.HSP_BUCKET BKT ON BKT.HSP_ACCOUNT_ID = TAL.HSP_ACCOUNT_ID
    WHERE BKT.BKT_TYPE_HA_C = 2 --- PRIMARY BUCKET 
    GROUP BY bkt.HSP_ACCOUNT_ID
)
,CTE_CLM_INFO AS
(
	SELECT DISTINCT

	 'HSP_ACCOUNT_ID' 	= 		HAR.HSP_ACCOUNT_ID
	,'EXP_REIMB_AMT'	=		sum(HLB.XR_BILLED_AMOUNT)
	,'MAX_BUCKET_ID'	=		max(hlb.bucket_id)
	,'LAST_INVOICE_NUM' =		max(HLB.LAST_CLM_INV_NUM)

	FROM CTE_ACCT_LIST HAR
	
	INNER JOIN dbo.hsp_bucket hlb 
		on hlb.hsp_account_id = HAR.hsp_account_id 
			and hlb.bkt_type_ha_c = 2
			and hlb.bkt_sts_ha_c not in (6,8,9)
			and hlb.claim_type_ha_c <> 4
	group by HAR.HSP_ACCOUNT_ID
)
,CTE_FIRST_VISIT AS
(
		SELECT DISTINCT HAR.HSP_ACCOUNT_ID,
				MIN(H.PAT_ENC_DATE) AS 'FIRST_VISIT_DATE'
				
	
		FROM CTE_ACCT_LIST HAR
			INNER JOIN CLARITY.DBO.HSP_ACCT_PAT_CSN H
				ON H.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID

		GROUP BY HAR.HSP_ACCOUNT_ID
), CTE_EXP_ALL AS
(
                SELECT A.HSP_ACCOUNT_ID, A.BUCKET_ID, MAX(A.LINE) AS LINE
                FROM CLARITY.DBO.HSP_BKT_NAA_ADJ_HX A
                INNER JOIN CTE_CLM_INFO C ON C.HSP_ACCOUNT_ID = A.HSP_ACCOUNT_ID
                AND C.MAX_BUCKET_ID = A.BUCKET_ID
                GROUP BY A.HSP_ACCOUNT_ID, A.BUCKET_ID
)


  SELECT DISTINCT
    -- FACILITY INFORMATION
	  'FACILITY_ID'					  = ISNULL(CONVERT(VARCHAR(18),HAR.LOC_ID),'')	
	 ,'FACILITY_NAME'					  = ISNULL(CLH.LOC_NAME,'')
	 ,'REV_LOC_ID'            = COALESCE(CONVERT(VARCHAR(10),DEPH.REV_LOC_ID),CONVERT(VARCHAR(10),DEP.REV_LOC_ID),CONVERT(VARCHAR(10),HAR.DISCH_LOC_ID),'')
     ,'REV_LOC_NAME'           = COALESCE(LOC.LOC_NAME,EAF.LOC_NAME,DLOC.LOC_NAME,'')         -- FACILITY_NAME
     ,'FACILITY_PTAN'          = '' 									-- check identity_type table
     ,'FACILITY_NPI'          = isnull(convert(varchar(18),CEV.BIL_PROV_NPI),'') 
     ,'FACILITY_TAX_ID'         = isnull(convert(varchar(18),CEV.BIL_PROV_TAXID),'')
     ,'ACCOUNT_NUMBER'         = HAR.HSP_ACCOUNT_ID             -- ACCOUNT_NUMBER
    
    -- PATIENT DEMOGRAPHIC INFORMATION
     ,'PATIENT_ID'           = HAR.PAT_ID
     ,'ORIG_PAT_MRN_ID'               = ISNULL(HAR.PAT_MRN,'')
     ,'CUR_PAT_MRN_ID'                = ISNULL(PT.PAT_MRN_ID,'')
     ,'HAR_PAT_MRN_ID'                = ISNULL(HAR_MRN.PAT_MRN,'') -- May have to comment this out if upgrade not in effect (and join on line 220-221)
     ,'ENTERPRISE_MRN'         = ISNULL((SELECT CONVERT(VARCHAR(18),IDENTITY_ID) FROM CLARITY.DBO.IDENTITY_ID 
												 WHERE IDENTITY_TYPE_ID = 0 AND PAT_ID = HAR.PAT_ID),'')
     ,'PATIENT_FIRST_NAME'       = PT.PAT_FIRST_NAME 
     ,'PATIENT_LAST_NAME'        = PT.PAT_LAST_NAME
     ,'PATIENT_GENDER'         = ISNULL(SEX.ABBR,'') 
     ,'PATIENT_DOB'           = ISNULL(FORMAT(PT.BIRTH_DATE,'MM/dd/yyyy'),'')
     ,'PATIENT_SSN'           = ISNULL(HAR.PAT_SSN,'') -- OR PT.SSN
     ,'PATIENT_PHONE'          = ISNULL(HAR.PAT_HOME_PHONE,'') -- DEFAULT MOBILE? OR HOME?; NOT ON ASSURANCE DATA SPEC      
     ,'PATIENT_ADDRESS_LINE_1'     = ISNULL(HAR.PAT_ADDR_1,'')
     ,'PATIENT_CITY'          = ISNULL(HAR.PAT_CITY,'') -- WHAT ABOUT INTERNATIONAL ACCTS?
     ,'PATIENT_STATE'          = ISNULL(HAR.PAT_STATE_C,'')
     ,'PATIENT_5-DIGIT_ZIP_CODE'    = ISNULL(HAR.PAT_ZIP,'')
     ,'EMPLOYER'            = ISNULL((select employer_name from clarity.dbo.clarity_eep where employer_id = ear.employer_id),'') 
     ,'MOTHERS_ACCOUNT'         = ISNULL(CONVERT(VARCHAR(18),HAR.MOM_HSP_ACCT_ID),'')
		   ,'GUARANTOR_FULL_NAME'			  = ISNULL(EAR.ACCOUNT_NAME,'')
     ,'GUARANTOR_FIRST_NAME'      = (CASE WHEN CHARINDEX(',',EAR.ACCOUNT_NAME) = 0 THEN '' ELSE 
													SUBSTRING(EAR.ACCOUNT_NAME,CHARINDEX(',',EAR.ACCOUNT_NAME) + 1, LEN(EAR.ACCOUNT_NAME)) END)
     ,'GUARANTOR_LAST_NAME'       = (CASE WHEN CHARINDEX(',',EAR.ACCOUNT_NAME) = 0 THEN '' ELSE 
													SUBSTRING(EAR.ACCOUNT_NAME,1,CHARINDEX(',',EAR.ACCOUNT_NAME) -1) END)
     ,'GUARANTOR_SSN'          = ISNULL(HAR.GUAR_SSN,'')
     ,'GUARANTOR_GENDER'        = ISNULL((case when HAR.GUAR_SEX_C = 1 then 'F' else (CASE when har.guar_sex_c = 2 then 'M' else 'U' end) end),'')
     ,'GUARANTOR_ADDRESS_LINE_1'    = ISNULL(HAR.GUAR_ADDR_1,'')
     ,'GUARANTOR_CITY'         = ISNULL(HAR.GUAR_CITY,'')
     ,'GUARANTOR_STATE'         = ISNULL((select abbr from dbo.zc_state where state_c = HAR.GUAR_STATE_C),'')
     ,'GUARANTOR_5-DIGIT_ZIP_CODE'   = ISNULL(HAR.GUAR_ZIP,'')
     ,'GUARANTOR_DOB'          = ISNULL(FORMAT(HAR.GUAR_DOB,'MM/dd/yyyy'),'')

    ---- ACCOUNT PROFILE
     ,'ADMIT_DATE_TIME'         = ISNULL(FORMAT(ISNULL(HAR.ADM_DATE_TIME, PE.HOSP_ADMSN_TIME),'MM/dd/yyyy HH:mm:ss'),'')
                   		 ---FOR SERIES ACCOUNTS THIS WILL BE LAST APPT ADMIT; CODED ADMIT DATE?
     ,'DISCHARGE_DATE_TIME'       = ISNULL(FORMAT(ISNULL(HAR.DISCH_DATE_TIME,
                        PEH.HOSP_DISCH_TIME),'MM/dd/yyyy HH:mm:ss'),'') ---FOR SERIES ACCOUNTS THIS WILL BE LAST APPT DISCH; CODED DISCH DATE?
     ,'FROM_DATE'            = ISNULL(FORMAT(enc.first_visit_date,'MM/dd/yyyy'),'') -- INITIAL VISIT DATE -- take the earliest CSN date for CSN's tied to this HAR -->
     ,'PATIENT_TYPE_CODE'        = ISNULL(CONVERT(VARCHAR(10),HAR.ACCT_BASECLS_HA_C),'') -- PATIENT_TYPE - INPATIENT, OUTPATIENT, OBS?
     ,'PATIENT_TYPE_NAME'        = ISNULL(ZBC.NAME,'')                  -- PATIENT_TYPE
     ,'PATIENT_CLASS'          = ISNULL(HAR.ACCT_CLASS_HA_C,'')
     ,'PATIENT_CLASS_NAME'       = ISNULL(ZPC.NAME,'')
     ,'ADMIT_LOCATION'         = isnull(adep.DEPARTMENT_NAME, '') -- double check if it needs to be adm_loc_id 
     ,'ADMIT_SOURCE_CODE'        = ISNULL(zsrc.ADMIT_SOURCE_C,'')
     ,'ADMIT_SOURCE_NAME'        = ISNULL(zsrc.NAME,'')
     ,'ADMIT_TYPE_CODE'         = ISNULL(zaty.ER_ADMIT_TYP_HA_C,'')
     ,'ADMIT_TYPE_NAME'         = ISNULL(zaty.NAME,'')
     ,'DISCHARGE_DEPARTMENT_CODE'    = ISNULL(CONVERT(VARCHAR(18),HAR.DISCH_DEPT_ID),'')
     ,'DISCHARGE_DEPARTMENT_NAME'    = ISNULL(DDEP.DEPARTMENT_NAME,'')
     ,'DISCHARGE_DISPOSITION_CODE'   = ISNULL(CONVERT(VARCHAR(10),HAR.PATIENT_STATUS_C),'')
     ,'DISCHARGE_DISPOSITION_NAME'   = ISNULL(ZPS.NAME,'')
     ,'DISCHARGE_FACILITY'       = ISNULL(CONVERT(VARCHAR(18), HAR.DISCH_LOC_ID), '')-- clarity_adt
     ,'CODING_STATUS_CODE'       = ISNULL(CONVERT(VARCHAR(10),HAR.CODING_STATUS_C),'')
     ,'CODING_STATUS_NAME'       = ISNULL(ZCS.NAME,'')
     ,'CURRENT_AGENCY_CODE'       = ISNULL(CONVERT(VARCHAR(18), HAR.BAD_DEBT_AGENCY_ID), '')
	 ,'CURRENT_AGENCY_NAME'			  = ISNULL((select coll_agency_name from cl_col_agncy where col_agncy_id = har.bad_debt_agency_id),'')

    ---- BILLED DRG INFORMATION
     ,'DRG_CODE'            = ISNULL(DRGS.DRG_MPI_CODE,'')   -- link to hsp_account for all of this info?   
     ,'DRG_NAME'            = ISNULL(CDRG.DRG_NAME,'') 
     ,'DRG_TYPE'            = COALESCE(ZDC.NAME,SUBSTRING(DRGID.ID_TYPE_NAME,1,7),'')
     ,'DRG_VERSION'           = ISNULL(DRGID.ID_TYPE_NAME,'') -- how to link to DRG_CODE_SET_TYPES table and use field DRG_CODE_SET_C & DRG_VERSION_C
     ,'DRG_WEIGHT'           = ISNULL(HAR.BILL_DRG_WEIGHT,'')
     ,'RISK_OF_MORTALITY'        = ISNULL(rom.abbr,'')
     ,'FINAL_CODER'           = ISNULL((SELECT NAME FROM CLARITY.dbo.CLARITY_EMP WHERE USER_ID = HART.CODING_USER),'') -- CODING_USER on HSP_ACCOUNT_2
     ,'COST_OUTLIER_THRESHOLD'     = ISNULL(CONVERT(VARCHAR(32),habd.BL_DRG_CST_OTLR_TH),'')
     ,'SOI'               = (CASE WHEN HAR.ACCT_BASECLS_HA_C = 1 THEN isnull(convert(varchar,HAR.BILL_DRG_PS),'') ELSE ''END)
			   --             
   
    ---- BILLING INFORMATION
     ,'ORIGINAL_BILL_DATE'       = isnull(FORMAT(BKT.FIRST_CLAIM_DATE,'MM/dd/yyyy'),'')
     ,'MOST_RECENT_BILL_DATE'      = isnull(FORMAT(BKT.LAST_CLAIM_DATE,'MM/dd/yyyy'),'')
     ,'BILL_DATE_CLEARINGHOUSE'     = isnull(FORMAT(BKT.FST_EXT_CLM_SENT_DT,'MM/dd/yyyy'),'')
     ,'BILL_TYPE'            = ISNULL(cld.UB_BILL_TYPE,'') -- MOST RECENT TYPE OF BILL SENT
     ,'BILLING_STATUS_CD'        = ISNULL(CONVERT(VARCHAR(18),HAR.ACCT_BILLSTS_HA_C),'')
     ,'BILLING_STATUS'         = ISNULL(zbs.NAME,'')

    ---- ACCOUNT AGGREGATES

     ,'TOTAL_ACCOUNT_BALANCE'      = ISNULL(CONVERT(VARCHAR(18),HAR.TOT_ACCT_BAL),'')
     ,'TOTAL_ACCOUNT_CHARGES'      = ISNULL(CONVERT(VARCHAR(18),HAR.TOT_CHGS),'')
     ,'TOTAL_ADJUSTMENTS'        = ISNULL(CONVERT(VARCHAR(18),(HAR.TOT_ADJ)),'') 
     ,'TOTAL_PAYMENTS'         = ISNULL(CONVERT(VARCHAR(18),(HAR.TOT_PMTS)),'')
     ,'EXPECTED_REIMBURSEMENT'     = ISNULL(CONVERT(VARCHAR(18),CLM.EXP_REIMB_AMT),'') -- HSP_BKT_XPTRBMT_HX (VIEW)
     ,'EXPECTED_ALLOWED_AMT'       = ISNULL(CONVERT(VARCHAR(18),NAA.EXPECT_ALLOWED_AMT),'')
     ,'PATIENT_RESPONSIBILITY'      = ISNULL(CONVERT(VARCHAR(25),SPB.CURRENT_BALANCE),'') -- PRORATED_PAT_BAL	ASK CHRIS IS THIS ORIGINAL OR WHAT'S LEFT (BALANCE?)
														/* HAR 232 The prorated self-pay balance amount for the hospital account. */ 
	 ,'BAD_DEBT_BALANCE'				  = isnull(convert(varchar(25),(case when HAR.ACCT_BILLSTS_HA_C = 20 or ACCT_SLFPYST_HA_C = 5 THEN har.TOT_ACCT_BAL end)),'')

    ---- ACCOUNT ATTRIBUTES
     ,'BAD_DEBT_FLAG'          = isnull(convert(varchar(25),(CASE WHEN HAR.ACCT_BILLSTS_HA_C = 20 or ACCT_SLFPYST_HA_C = 5 THEN 'Y' ELSE '' END)),'') -- (BAD DEBT) HAR 60
     ,'ATTENDING_PHYSICIAN_CODE'    = ISNULL(CONVERT(VARCHAR(18),ATSER.PROV_ID),'') -- pull last known Attending?
     ,'ATTENDING_PHYSICIAN_NPI'     = COALESCE(ATNPI.IDENTITY_ID,ATNPI2.NPI,'')
     ,'ATTENDING_PHYSICIAN_NAME'    = ISNULL(ATSER.PROV_NAME,'')
     ,'RECURRING_INDICATOR'       = (CASE WHEN ISNULL(HAR.RECUR_PARENT_ID,0) > 1 THEN 'Recurring' ELSE 'Not' END)
     ,'RESEARCH_FLAG'          = ISNULL(CONVERT(VARCHAR(10),HAR.RESEARCH_ID),'')-- (HAR 75)
     ,'INSTITUTIONAL_FLAG'       = ISNULL(HAR.IS_INSTI_YN,'')--(HAR 70)

    ---- MISC ACCOUNT ATTRIBUTES

     ,'MOTHER_FIRST_NAME'        = ISNULL((select pat_first_name from clarity.dbo.patient where pat_id = har.mom_patient_id),'')
     ,'MOTHER_LAST_NAME'         = ISNULL((select pat_last_name from clarity.dbo.patient where pat_id = har.mom_patient_id),'')
     ,'GUARANTOR_RELATIONSHIP'      = ISNULL(ZEARR.NAME, '') -- ACCT_GUAR_PAT_INFO
     ,'DATE_OF_DEATH'          = isnull(format(pt.death_date, 'MM/dd/yyyy'),'')
	 ,'TRANSFER_AGENCY_NAME'			  = ISNULL(CLFA.COLL_AGENCY_NAME,'')	
     ,'DATE_TRANSFER_TO_AGENCY'     = isnull(FORMAT(FAD.AGNCY_HST_DT_OF_CH,'MM/dd/yyyy'),'') -- HSP_ACCT_CL_AG_HIS - CREATE cte? HAR 2280 when har 2281 - 1 (Assign)
     ,'AMOUNT_TRANSFER_TO_AGENCY'    = isnull(convert(varchar(18),FAD.AGNCY_HST_ACCT_BAL), '') -- HAR 2284
     ,'RETURN_DATE_FROM_AGENCY'     = isnull(FORMAT(LAD.AGNCY_HST_DT_OF_CH,'MM/dd/yyyy'),'') -- HAR 2280 when har 2281 - 2 (Withdraw) 
     ,'AMOUNT_RETURN_FROM_AGENCY'    = isnull(convert(varchar(18),LAD.AGNCY_HST_ACCT_BAL) ,'') -- HAR 2284
	 ,'FROM_AGENCY_NAME'				  = isnull(convert(varchar(20),CLLA.COLL_AGENCY_NAME),'')
     ,'CHARITY_CARE_FLAG'         = (CASE WHEN HARTH.PRIMARY_WRITE_OFF_RSN_C = 2 THEN 'Y' ELSE '' END) -- ON HSP_ACCOUNT_4 = 2(SELF-PAY DISCOUNT/CHARITY) OR FIN_ASST_PROGRAM
     ,'CHARITY_CARE_LEVEL'        = '' -- FPL.FPL_PERCENTAGE
	 ,'GUARANTOR_ACCOUNT_NUMBER'		  = HAR.GUARANTOR_ID

FROM  CTE_ACCT_LIST TAL 

INNER JOIN CLARITY.dbo.HSP_ACCOUNT AS HAR
    ON HAR.HSP_ACCOUNT_ID = TAL.HSP_ACCOUNT_ID
INNER JOIN CLARITY.dbo.HSP_ACCOUNT_2 AS HART
	ON HART.HSP_ACCOUNT_ID = TAL.HSP_ACCOUNT_ID
LEFT JOIN CTE_FIRST_VISIT enc on enc.HSP_ACCOUNT_ID = har.HSP_ACCOUNT_ID   	 
LEFT JOIN CLARITY.dbo.HSP_ACCOUNT_4 AS HARTH 
	ON HARTH.HSP_ACCOUNT_ID = TAL.HSP_ACCOUNT_ID
LEFT JOIN CLARITY.dbo.PATIENT AS PT 
    ON HAR.PAT_ID = PT.PAT_ID
LEFT JOIN CLARITY.dbo.HSP_ACCT_PAT_MRN as HAR_MRN
    ON HAR.HSP_ACCOUNT_ID = HAR_MRN.HSP_ACCOUNT_ID
LEFT JOIN CLARITY.dbo.ACCOUNT as EAR 
    ON EAR.ACCOUNT_ID = HAR.GUARANTOR_ID
LEFT JOIN CLARITY.dbo.ACCT_GUAR_PAT_INFO AS EARR 
	ON EARR.ACCOUNT_ID = HAR.GUARANTOR_ID
		AND EARR.PAT_ID = HAR.PAT_ID
LEFT JOIN CLARITY_LOC CLH
	ON HAR.LOC_ID = CLH.LOC_ID
	
--- CATEGORY TABLES FOR ACCOUNT AND PATIENT LEVEL CODES

LEFT JOIN CLARITY.dbo.ZC_ACCT_BASECLS_HA AS ZBC
    ON HAR.ACCT_BASECLS_HA_C = ZBC.ACCT_BASECLS_HA_C
LEFT JOIN CLARITY.dbo.ZC_ACCT_CLASS_HA AS ZPC
    ON HAR.ACCT_CLASS_HA_C = ZPC.ACCT_CLASS_HA_C
LEFT JOIN CLARITY.dbo.ZC_ACCT_BILLSTS_HA AS zbs
    ON HAR.ACCT_BILLSTS_HA_C = zbs.ACCT_BILLSTS_HA_C
LEFT JOIN CLARITY.dbo.ZC_CODING_STS_HA AS ZCS
    ON HAR.CODING_STATUS_C = ZCS.CODING_STATUS_C
LEFT JOIN CLARITY.dbo.ZC_SEX AS SEX
    ON PT.SEX_C = SEX.RCPT_MEM_SEX_C -- HARD CODE TO MAKE MORE EFFICIENT?
LEFT JOIN CLARITY.dbo.ZC_ADM_SOURCE AS zsrc
    ON HAR.ADMISSION_SOURCE_C = zsrc.ADMIT_SOURCE_C
LEFT JOIN CLARITY.dbo.ZC_ER_ADMIT_TYP_HA AS zaty
    ON HAR.ADMISSION_TYPE_C = zaty.ER_ADMIT_TYP_HA_C
LEFT JOIN CLARITY.dbo.ZC_GUAR_REL_TO_PAT AS ZEARR 
    ON ZEARR.GUAR_REL_TO_PAT_C = EARR.GUAR_REL_TO_PAT_C
LEFT JOIN [CLARITY].[dbo].[ZC_MC_PAT_STATUS] ZPS
	ON ZPS.ABBR = HAR.PATIENT_STATUS_C 

--- CLAIM INFO

LEFT JOIN CTE_BUCKET AS BKT
    ON HAR.HSP_ACCOUNT_ID = BKT.HSP_ACCOUNT_ID 
LEFT join CTE_CLM_INFO clm
	ON clm.hsp_account_id = har.HSP_ACCOUNT_ID
LEFT JOIN CTE_EXP_ALL AS A
    ON A.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID
LEFT JOIN CLARITY.DBO.HSP_BKT_NAA_ADJ_HX NAA
    ON NAA.HSP_ACCOUNT_ID = A.HSP_ACCOUNT_ID AND NAA.BUCKET_ID = A.BUCKET_ID AND NAA.LINE = A.LINE
LEFT join dbo.HSP_CLAIM_DETAIL2 cld 
	ON cld.hlb_id = clm.max_bucket_id AND CLD.CLAIM_ACCEPT_DTTM IS NOT NULL and cld.INACTV_CLP_YN is null and clm.LAST_INVOICE_NUM = cld.INVOICE_NUM
LEFT JOIN dbo.CLM_VALUES CEV
	ON cev.RECORD_ID = cld.CLM_EXT_VAL_ID

--- ENCOUNTER DATA. USING ONLY HOSPITAL ENCOUNTERS, NOT PAT_ENC, TO REDUCE DATA SET

LEFT JOIN clarity.dbo.PAT_ENC_HSP PEH
    ON HAR.HSP_ACCOUNT_ID = PEH.HSP_ACCOUNT_ID 
        AND HAR.PRIM_ENC_CSN_ID = PEH.PAT_ENC_CSN_ID
LEFT JOIN CLARITY_DEP DEPH
	ON DEPH.DEPARTMENT_ID = PEH.DEPARTMENT_ID
LEFT JOIN CLARITY_LOC LOC
	ON DEPH.REV_LOC_ID = LOC.LOC_ID
LEFT JOIN clarity.dbo.PAT_ENC PE 
    ON HAR.PRIM_ENC_CSN_ID = PE.PAT_ENC_CSN_ID
LEFT JOIN CLARITY_DEP DEP
    ON PE.DEPARTMENT_ID = DEP.DEPARTMENT_ID
LEFT JOIN CLARITY_LOC EAF 
    ON DEP.REV_LOC_ID = EAF.LOC_ID

--- ENCOUNTER LEVEL CATEGORY TABLES
  --LEFT JOIN clarity.dbo.ZC_DISCH_DISP AS ZDISP
  --    ON PEH.DISCH_DISP_C = ZDISP.DISCH_DISP_C
LEFT JOIN clarity.dbo.ZC_DISCH_DEST AS ZDEST
    ON PEH.DISCH_DEST_C = ZDEST.DISCH_DEST_C

--- ENCOUNTER DEPARTMENTS AND LOCATIONS FOR ADMISSION AND DISCHARGE FROM HAR
LEFT JOIN clarity.dbo.CLARITY_ADT AS ADT
    ON PEH.ADM_EVENT_ID = ADT.EVENT_ID
LEFT JOIN clarity.dbo.CLARITY_DEP AS ADEP
    ON ADT.DEPARTMENT_ID = ADEP.DEPARTMENT_ID
LEFT JOIN clarity.dbo.CLARITY_LOC ALOC
    ON ADEP.REV_LOC_ID = ALOC.LOC_ID

--- IF HAR DOESN'T HAVE DISCH DEPARTMENT, GET IT FROM THE ENCOUNTER
LEFT JOIN clarity.dbo.CLARITY_DEP AS DDEP
    ON ISNULL(HAR.DISCH_DEPT_ID,PEH.DEPARTMENT_ID) = DDEP.DEPARTMENT_ID
LEFT JOIN clarity.dbo.CLARITY_LOC AS DLOC
    ON HAR.DISCH_LOC_ID = DLOC.LOC_ID
--- DISCHARGE REVENUE LOCATION MAY BE DIFFERENT FROM DISCH DEPT REVENUE LOCATION BUT SHOULDN'T BE
LEFT JOIN clarity.dbo.CLARITY_LOC AS RLOC
    ON DDEP.REV_LOC_ID = RLOC.LOC_ID
LEFT JOIN clarity.dbo.CLARITY_LOC AS HOSP
    ON HAR.LOC_ID = HOSP.LOC_ID
LEFT JOIN clarity.dbo.CLARITY_SA AS SA
    ON COALESCE(HAR.SERV_AREA_ID,PEH.ADT_SERV_AREA_ID) = SA.SERV_AREA_ID

-----GET DRG INFORMATION
LEFT JOIN clarity.dbo.HSP_ACCT_MULT_DRGS AS DRGS
    ON HAR.HSP_ACCOUNT_ID = DRGS.HSP_ACCOUNT_ID
       AND DRGS.DRG_BILLING_FLAG_YN = 'Y'	--- MUST BE THE BILLING DRG, WHETHER MS OR APR
LEFT JOIN clarity.dbo.IDENTITY_ID_TYPE AS DRGID
    ON DRGS.DRG_ID_TYPE_ID = DRGID.ID_TYPE
LEFT JOIN clarity.dbo.CLARITY_DRG AS CDRG
    ON HAR.FINAL_DRG_ID = CDRG.DRG_ID
LEFT JOIN dbo.ZC_DRG_CODE_SET ZDC
	ON ZDC.DRG_CODE_SET_C = CDRG.DRG_CODE_SET_C
LEFT JOIN dbo.HSP_ACCT_BILL_DRG habd
    ON habd.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID
LEFT JOIN dbo.ZC_SOI_ROM rom
      ON rom.SOI_ROM_C = HAR.BILL_DRG_ROM

--- GET INFO FOR ATTENDING PROVIDER

LEFT JOIN clarity.dbo.CLARITY_SER ATSER
    ON ISNULL(HAR.ATTENDING_PROV_ID,PEH.BILL_ATTEND_PROV_ID) = ATSER.PROV_ID
LEFT JOIN clarity.dbo.IDENTITY_SER_ID AS ATNPI
    ON ATNPI.PROV_ID = ATSER.PROV_ID
		AND ATNPI.IDENTITY_TYPE_ID = 60 
LEFT JOIN clarity.dbo.CLARITY_SER_2 AS ATNPI2
    ON ATSER.PROV_ID = ATNPI2.PROV_ID

-- GET AGENCY HISTORY INFO

LEFT JOIN (
            SELECT HSP_ACCOUNT_ID, 
            MIN(LINE) AS 'FIRST_ASSIGN_LINE'
            FROM CLARITY.DBO.HSP_ACCT_CL_AG_HIS 
            WHERE AGNC_HST_CHG_TP_C = 1 AND AGN_HST_COL_ACT_C = 10
            GROUP BY HSP_ACCOUNT_ID) FA
                ON FA.HSP_ACCOUNT_ID = TAL.HSP_ACCOUNT_ID
LEFT JOIN (
            SELECT HSP_ACCOUNT_ID, 
            MAX(LINE) AS 'LAST_RECALL_LINE'
            FROM CLARITY.DBO.HSP_ACCT_CL_AG_HIS 
            WHERE AGNC_HST_CHG_TP_C = 2 AND AGN_HST_COL_ACT_C = 11
            GROUP BY HSP_ACCOUNT_ID) LA
                ON LA.HSP_ACCOUNT_ID = TAL.HSP_ACCOUNT_ID
					
LEFT JOIN HSP_ACCT_CL_AG_HIS FAD
	ON FAD.HSP_ACCOUNT_ID = TAL.HSP_ACCOUNT_ID AND FAD.LINE = FA.FIRST_ASSIGN_LINE
LEFT JOIN HSP_ACCT_CL_AG_HIS LAD
	ON LAD.HSP_ACCOUNT_ID = TAL.HSP_ACCOUNT_ID AND LAD.LINE = LA.LAST_RECALL_LINE	
LEFT JOIN CL_COL_AGNCY CLFA
	ON CLFA.COL_AGNCY_ID = FAD.AGNCY_HST_AGNCY_ID
LEFT JOIN CL_COL_AGNCY CLLA
	ON CLLA.COL_AGNCY_ID = LAD.AGNCY_HST_AGNCY_ID 
		
-- GET PATIENT RESPONSIBILITY

LEFT JOIN HSP_BUCKET SPB
	ON SPB.BUCKET_ID = HAR.SELF_PAY_BUCKET_ID
		AND SPB.BKT_TYPE_HA_C = 4  --- SELF-PAY BUCKET

-- GET FPL LEVEL FROM GUARANTOR
	--LEFT JOIN dbo.ACCOUNT_FPL_INFO FPL 
	--	ON FPL.ACCOUNT_ID = HAR.GUARANTOR_ID 

