BEGIN

	USE CLARITY

END
;

--Variables for Recurring/Incremental phase
DECLARE @CurDate DATETIME
DECLARE @BeginDate DATETIME
SET @CurDate = CONVERT(DATETIME, DATEDIFF(DAY, 0, GETDATE()))
SET @BeginDate = DATEADD(DAY,-14,@CurDate) --To modify the lookback period, set the negative integer to the desired number of days (-14 is the default, looking back 14 days)
;

WITH CTE_ACCT_LIST
  AS
  (
        SELECT DISTINCT	HAR.HSP_ACCOUNT_ID
        FROM    CLARITY.dbo.HSP_ACCOUNT AS HAR
        INNER JOIN CLARITY.dbo.HSP_TRANSACTIONS AS HTR     -- Should be good for HB accounts and exclude PB accounts
                ON HTR.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID
		INNER JOIN Clarity.dbo.HSP_ACCT_LAST_UPDATE AS HALU 
                ON HTR.HSP_ACCOUNT_ID = halu.HSP_ACCOUNT_ID
        --WHERE HALU.INST_OF_UPDATE_DTTM >= @BeginDate --Used for Recurring/Incremental phase, comment out for Testing/Historical phase
        WHERE HAR.DISCH_DATE_TIME BETWEEN @STARTDATE AND @ENDDATE --Used for Testing/Historical phase, comment out for Recurring/Incremental phase
	), CTE_CVG AS
(


  SELECT 'HSP_ACCOUNT_ID'		  = HALU.HSP_ACCOUNT_ID
		   ,'PRIM_COVERAGE_ID'		  = MAX(CASE WHEN HCVG.LINE = 1 THEN HCVG.COVERAGE_ID END)
     ,'PRIM_FIN_CLASS'     = MAX(CASE WHEN HCVG.LINE = 1 THEN FC.FINANCIAL_CLASS_NAME END)
     ,'PRIM_PAYOR_ID'      = MAX(CASE WHEN HCVG.LINE = 1 THEN EPM.PAYOR_ID END) 
     ,'PRIM_PAYOR_NAME'     = MAX(CASE WHEN HCVG.LINE = 1 THEN ISNULL(EPM.PAYOR_NAME,'Self-Pay') END)
     ,'PRIM_PLAN_ID'      = MAX(CASE WHEN HCVG.LINE = 1 THEN EPP.BENEFIT_PLAN_ID END)
     ,'PRIM_PLAN_NAME'     = MAX(CASE WHEN HCVG.LINE = 1 THEN ISNULL(EPP.BENEFIT_PLAN_NAME,'Self-Pay') END)
     ,'PRIM_PLAN_GROUP'     = MAX(CASE WHEN HCVG.LINE = 1 THEN ISNULL(CVG.GROUP_NUM,'') END)
     ,'PRIM_PLAN_POLICY'    = MAX(CASE WHEN HCVG.LINE = 1 THEN ISNULL(CVG.SUBSCR_NUM,'') END)
		   ,'SEC_COVERAGE_ID'		  = MAX(CASE WHEN HCVG.LINE = 2 THEN HCVG.COVERAGE_ID END)
     ,'SEC_FIN_CLASS'      = MAX(CASE WHEN HCVG.LINE = 2 THEN FC.FINANCIAL_CLASS_NAME END)
     ,'SEC_PAYOR_ID'      = MAX(CASE WHEN HCVG.LINE = 2 THEN EPM.PAYOR_ID END)
     ,'SEC_PAYOR_NAME'     = MAX(CASE WHEN HCVG.LINE = 2 THEN ISNULL(EPM.PAYOR_NAME,'Self-Pay')END)
     ,'SEC_PLAN_ID'       = MAX(CASE WHEN HCVG.LINE = 2 THEN EPP.BENEFIT_PLAN_ID END)
     ,'SEC_PLAN_NAME'      = MAX(CASE WHEN HCVG.LINE = 2 THEN ISNULL(EPP.BENEFIT_PLAN_NAME,'Self-Pay')END)
		   ,'SEC_PLAN_GROUP'		  = MAX(CASE WHEN HCVG.LINE = 2 THEN ISNULL(CVG.GROUP_NUM,'') END)
		   ,'SEC_PLAN_POLICY'		  = MAX(CASE WHEN HCVG.LINE = 2 THEN ISNULL(CVG.SUBSCR_NUM,'') END)
		   ,'TERT_COVERAGE_ID'		  = MAX(CASE WHEN HCVG.LINE = 3 THEN HCVG.COVERAGE_ID END)		   
     ,'TERT_FIN_CLASS'     = MAX(CASE WHEN HCVG.LINE = 3 THEN FC.FINANCIAL_CLASS_NAME END)
     ,'TERT_PAYOR_ID'      = MAX(CASE WHEN HCVG.LINE = 3 THEN EPM.PAYOR_ID END)
     ,'TERT_PAYOR_NAME'     = MAX(CASE WHEN HCVG.LINE = 3 THEN ISNULL(EPM.PAYOR_NAME,'Self-Pay') END)
     ,'TERT_PLAN_ID'      = MAX(CASE WHEN HCVG.LINE = 3 THEN EPP.BENEFIT_PLAN_ID END)
     ,'TERT_PLAN_NAME'     = MAX(CASE WHEN HCVG.LINE = 3 THEN ISNULL(EPP.BENEFIT_PLAN_NAME,'Self-Pay')END)
		   ,'TERT_PLAN_GROUP'		  =	MAX(CASE WHEN HCVG.LINE = 3 THEN ISNULL(CVG.GROUP_NUM,'') END)
		   ,'TERT_PLAN_POLICY'		  = MAX(CASE WHEN HCVG.LINE = 3 THEN ISNULL(CVG.SUBSCR_NUM,'') END)
		   ,'QUANT_COVERAGE_ID'		  = MAX(CASE WHEN HCVG.LINE = 4 THEN HCVG.COVERAGE_ID END)     
		   ,'QUANT_PAYOR_ID'     = MAX(CASE WHEN HCVG.LINE = 4 THEN EPM.PAYOR_ID END)
     ,'QUANT_PAYOR_NAME'    = MAX(CASE WHEN HCVG.LINE = 4 THEN ISNULL(EPM.PAYOR_NAME,'Self-Pay') END)
     ,'QUANT_PLAN_ID'      = MAX(CASE WHEN HCVG.LINE = 4 THEN EPP.BENEFIT_PLAN_ID END)
     ,'QUANT_PLAN_NAME'     = MAX(CASE WHEN HCVG.LINE = 4 THEN ISNULL(EPP.BENEFIT_PLAN_NAME,'Self-Pay')END)
		   ,'QUANT_PLAN_GROUP'		  =	MAX(CASE WHEN HCVG.LINE = 4 THEN ISNULL(CVG.GROUP_NUM,'') END)
		   ,'QUANT_PLAN_POLICY'		  = MAX(CASE WHEN HCVG.LINE = 4 THEN ISNULL(CVG.SUBSCR_NUM,'') END)



  FROM  CTE_ACCT_LIST HALU --- JUST USE LISTED ACCOUNTS
  
  INNER JOIN dbo.HSP_ACCT_CVG_LIST AS HCVG
      ON HALU.HSP_ACCOUNT_ID = HCVG.HSP_ACCOUNT_ID
  LEFT JOIN dbo.COVERAGE AS CVG
      ON HCVG.COVERAGE_ID = CVG.COVERAGE_ID
  LEFT JOIN dbo.CLARITY_EPM AS EPM
      ON CVG.PAYOR_ID = EPM.PAYOR_ID
  LEFT JOIN dbo.CLARITY_EPP AS EPP
      ON EPP.BENEFIT_PLAN_ID = CVG.PLAN_ID
  LEFT JOIN dbo.CLARITY_FC AS FC
      ON EPM.FINANCIAL_CLASS = FC.FINANCIAL_CLASS
  WHERE  HCVG.LINE IN (1,2,3)
  GROUP BY HALU.HSP_ACCOUNT_ID
)
,CTE_BUCKET AS
(

	SELECT DISTINCT		
			 'HSP_ACCOUNT_ID'			= TAL.HSP_ACCOUNT_ID
			,'COVERAGE_ID'				= BKT.COVERAGE_ID	
			,'PAYMENT_TOTAL'			= SUM(BKT.PAYMENT_TOTAL)
			,'CURRENT_BALANCE'			= SUM(BKT.CURRENT_BALANCE)
			,'MAX_BUCKET_ID'			= MAX(BUCKET_ID)

	FROM CTE_ACCT_LIST TAL

	INNER JOIN HSP_BUCKET BKT ON TAL.HSP_ACCOUNT_ID = BKT.HSP_ACCOUNT_ID

	WHERE BKT.BKT_TYPE_HA_C NOT IN (1,4,5,8,30) -- Not a type of 'Prebilled, Self-Pay, Bad-Debt, Undistributed, Informational)
			AND BKT.BKT_STS_HA_C NOT IN (6,8,9) --Not a bucket status of Error, Rejected, or Replaced
			AND BKT.CLAIM_TYPE_HA_C NOT IN (4) -- EXCLUDE 'LATE WRITE OFF' CLAIM
	GROUP BY TAL.HSP_ACCOUNT_ID, BKT.COVERAGE_ID


)

	SELECT DISTINCT		
			'FACILITY_ID'									= ISNULL(CONVERT(VARCHAR(80),HAR.LOC_ID),'')
			,'ACCOUNT_NUMBER'								= ISNULL(CONVERT(VARCHAR(80),TAL.HSP_ACCOUNT_ID),'')
			,'PRIMARY_PAYER_PLAN_CODE'						= ISNULL(CONVERT(VARCHAR(80),CVG.PRIM_PLAN_ID),'')
			,'PRIMARY_PAYER_PLAN_NAME'					        = ISNULL(CVG.PRIM_PLAN_NAME,'')
			,'PRIMARY_PAYER_CODE'							= ISNULL(CONVERT(VARCHAR(80),CVG.PRIM_PAYOR_ID),'')
			,'PRIMARY_PAYER_NAME'							= ISNULL(CVG.PRIM_PAYOR_NAME,'')
			,'PRIMARY_PAYER_FINANCIAL_CLASS'				= COALESCE(CONVERT(VARCHAR(80),CVG.PRIM_FIN_CLASS), CONVERT(VARCHAR(80),ZFC.Name),'Self-Pay')
			,'PRIMARY_POLICY_NUMBER'						= ISNULL(CONVERT(VARCHAR(80),CVG.PRIM_PLAN_POLICY),'')
			,'PRIMARY_GROUP_NUMBER'							= ISNULL(CONVERT(VARCHAR(80),CVG.PRIM_PLAN_GROUP),'')
			,'PRIMARY_INSURANCE_BALANCE'					= ISNULL(CONVERT(VARCHAR(80),PRIM_BKT.CURRENT_BALANCE),0)
			,'PRIMARY_INSURANCE_AUTHORIZATION_NUMBER'		= ISNULL(CONVERT(VARCHAR(80),PRIM_CEV.AUTH_NUM ),'')
			,'PRIMARY_PAYER_TOTAL_PAYMENTS'					= ISNULL(CONVERT(VARCHAR(80),PRIM_BKT.PAYMENT_TOTAL),'') 
			,'PRIMARY_PAYER_CONTRACT_ID'					= ISNULL(CONVERT(VARCHAR(80),HCD.CONTRACT_ID),'')
			,'PRIMARY_PAYER_CONTRACT_NAME'					= ISNULL(CONT.CONTRACT_NAME,'')
			,'SECONDARY_PAYER_PLAN_CODE'					= ISNULL(CONVERT(VARCHAR(80),CVG.SEC_PLAN_ID),'')	
			,'SECONDARY_PAYER_PLAN_NAME'					= ISNULL(CVG.SEC_PLAN_NAME,'')
			,'SECONDARY_PAYER_CODE'							= ISNULL(CONVERT(VARCHAR(80),CVG.SEC_PAYOR_ID),'')
			,'SECONDARY_PAYER_NAME'							= ISNULL(CVG.SEC_PAYOR_NAME,'')
			,'SECONDARY_PAYER_FINANCIAL_CLASS'				= ISNULL(CONVERT(VARCHAR(80),CVG.SEC_FIN_CLASS),'Self-Pay')
			,'SECONDARY_POLICY_NUMBER'						= ISNULL(CONVERT(VARCHAR(80), CVG.SEC_PLAN_POLICY),'')
			,'SECONDARY_GROUP_NUMBER'						= ISNULL(CONVERT(VARCHAR(80),CVG.SEC_PLAN_GROUP),'')
			,'SECONDARY_INSURANCE_BALANCE'					= ISNULL(CONVERT(VARCHAR(80),SEC_BKT.CURRENT_BALANCE),'')
			,'SECONDARY_INSURANCE_AUTHORIZATION_NUMBER'		= ISNULL(CONVERT(VARCHAR(80),SEC_CEV.AUTH_NUM),'')
			,'SECONDARY_PAYER_TOTAL_PAYMENTS'				= ISNULL(CONVERT(VARCHAR(80),SEC_BKT.PAYMENT_TOTAL),0)
			,'TERTIARY_PAYER_PLAN_CODE'						= ISNULL(CONVERT(VARCHAR(80),CVG.TERT_PLAN_ID),'')
			,'TERTIARY_PAYER_PLAN_NAME'						= ISNULL(CVG.TERT_PLAN_NAME,'')
			,'TERTIARY_PAYER_CODE'							= ISNULL(CONVERT(VARCHAR(80),CVG.TERT_PAYOR_ID),'')
			,'TERTIARY_PAYER_NAME'							= ISNULL(CVG.TERT_PAYOR_NAME,'')
			,'TERTIARY_PAYER_FINANCIAL CLASS'				= ISNULL(CONVERT(VARCHAR(80),CVG.TERT_FIN_CLASS),'Self-Pay')
			,'TOTAL_TERTIARY_PAYER_PAYMENTS'				= ISNULL(CONVERT(VARCHAR(80),TERT_BKT.PAYMENT_TOTAL),'')
			,'TERTIARY_POLICY_NUMBER'						= ISNULL(CONVERT(VARCHAR(80),CVG.TERT_PLAN_POLICY),'')
			,'QUATERNARY_PAYER_PLAN_CODE'					= ISNULL(CONVERT(VARCHAR(80),CVG.QUANT_PLAN_ID),'')
			,'QUATERNARY_PAYER_PLAN_NAME'						= ISNULL(CVG.QUANT_PLAN_NAME,'')
			,'QUATERNARY_PAYER_CODE'						= ISNULL(CONVERT(VARCHAR(80),CVG.QUANT_PAYOR_ID),'')
			,'QUATERNARY_PAYER_NAME'						= ISNULL(CVG.QUANT_PAYOR_NAME,'')
			,'QUATERNARY_POLICY_NUMBER'						= ISNULL(CONVERT(VARCHAR(80),CVG.QUANT_PLAN_POLICY),'')

	FROM CTE_ACCT_LIST TAL
	
	INNER JOIN dbo.HSP_ACCOUNT HAR 
		ON HAR.HSP_ACCOUNT_ID = TAL.HSP_ACCOUNT_ID
	
	LEFT JOIN ZC_FINANCIAL_CLASS ZFC 
		ON ZFC.INTERNAL_ID = HAR.ACCT_FIN_CLASS_C

	LEFT JOIN CTE_CVG CVG
		ON CVG.HSP_ACCOUNT_ID = TAL.HSP_ACCOUNT_ID
		
	LEFT JOIN  CTE_BUCKET PRIM_BKT
		ON PRIM_BKT.HSP_ACCOUNT_ID = TAL.HSP_ACCOUNT_ID
			AND PRIM_BKT.COVERAGE_ID = CVG.PRIM_COVERAGE_ID
	LEFT JOIN HSP_BUCKET HLB 
		ON HLB.BUCKET_ID = PRIM_BKT.MAX_BUCKET_ID
	LEFT JOIN HSP_CLAIM_DETAIL2 PRIM_CLD 
		ON PRIM_CLD.HLB_ID = PRIM_BKT.MAX_BUCKET_ID
			AND PRIM_CLD.INVOICE_NUM = HLB.LAST_CLM_INV_NUM
			AND PRIM_CLD.CLAIM_ACCEPT_DTTM IS NOT NULL and PRIM_CLD.INACTV_CLP_YN is null
	LEFT JOIN HSP_CLAIM_DETAIL1 hcd
		on hcd.CLAIM_PRINT_ID = prim_cld.CLAIM_PRINT_ID
	LEFT JOIN dbo.VEN_NET_CONT CONT
		ON CONT.CONTRACT_ID = HCD.CONTRACT_ID
	LEFT JOIN CLM_VALUES_2 PRIM_CEV
		ON PRIM_CEV.RECORD_ID = PRIM_CLD.CLM_EXT_VAL_ID 


	LEFT JOIN CTE_BUCKET SEC_BKT
		ON SEC_BKT.HSP_ACCOUNT_ID = TAL.HSP_ACCOUNT_ID
			AND SEC_BKT.COVERAGE_ID = CVG.SEC_COVERAGE_ID
	LEFT JOIN HSP_BUCKET HLB2 
		ON HLB2.BUCKET_ID = SEC_BKT.MAX_BUCKET_ID
	LEFT JOIN HSP_CLAIM_DETAIL2 SEC_CLD 
		ON SEC_CLD.HLB_ID = SEC_BKT.MAX_BUCKET_ID AND SEC_CLD.INVOICE_NUM = HLB2.LAST_CLM_INV_NUM
			AND SEC_CLD.CLAIM_ACCEPT_DTTM IS NOT NULL and SEC_CLD.INACTV_CLP_YN is null
	LEFT JOIN CLM_VALUES_2 SEC_CEV
		ON SEC_CEV.RECORD_ID = SEC_CLD.CLM_EXT_VAL_ID

	LEFT JOIN CTE_BUCKET TERT_BKT
		ON TERT_BKT.HSP_ACCOUNT_ID = CVG.TERT_COVERAGE_ID

		
	ORDER BY ACCOUNT_NUMBER
		


