BEGIN

	USE CLARITY

END
;

--Variables for Recurring/Incremental phase
DECLARE @CurDate DATETIME
DECLARE @BeginDate DATETIME
SET @CurDate = CONVERT(DATETIME, DATEDIFF(DAY, 0, GETDATE()))
SET @BeginDate = DATEADD(DAY,-14,@CurDate) --To modify the lookback period, set the negative integer to the desired number of days (-14 is the default, looking back 14 days)
;

WITH CTE_ACCT_LIST
  AS
  (
        SELECT DISTINCT	HAR.HSP_ACCOUNT_ID
        FROM    CLARITY.dbo.HSP_ACCOUNT AS HAR
        INNER JOIN CLARITY.dbo.HSP_TRANSACTIONS AS HTR     -- Should be good for HB accounts and exclude PB accounts
                ON HTR.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID
		INNER JOIN Clarity.dbo.HSP_ACCT_LAST_UPDATE AS HALU 
                ON HTR.HSP_ACCOUNT_ID = halu.HSP_ACCOUNT_ID
        --WHERE HALU.INST_OF_UPDATE_DTTM >= @BeginDate --Used for Recurring/Incremental phase, comment out for Testing/Historical phase
        WHERE HAR.DISCH_DATE_TIME BETWEEN @STARTDATE AND @ENDDATE --Used for Testing/Historical phase, comment out for Recurring/Incremental phase
	)

/******************************************************************************************

MAIN CODE LOGIC

******************************************************************************************/

SELECT   	 'FACILITY_ID'						= ISNULL(CONVERT(VARCHAR(18),HAR.LOC_ID),'') 
			,'ACCOUNT_NUMBER' 					= HAR.HSP_ACCOUNT_ID
			,'SEQUENCE'							= PX.LINE
			,'PROCEDURE_CODE'					= ISNULL(ICDPX.REF_BILL_CODE,'')
			,'PROCEDURE_DESCRIPTION'			= ISNULL(ICDPX.ICD_PX_NAME,'')
			,'PROCEDURE_VERSION'				= (CASE WHEN ICDPX.REF_BILL_CODE_SET_C = 1 THEN '9'
			  										WHEN ICDPX.REF_BILL_CODE_SET_C = 2 THEN '10' 
			  										ELSE 'B' END)	
			,'PROCEDURE_DATE'					= ISNULL(CONVERT(VARCHAR(10),PX.PROC_DATE,101),'')
			,'PERFORMING_PHYSICIAN CODE'		= ISNULL(CONVERT(VARCHAR(18),PX.PROC_PERF_PROV_ID),'')
			,'PERFORMING_PHYSICIAN NAME'		= ISNULL(SER.PROV_NAME,'')
			,'PERFORMING_PHYSICIAN NPI'			= COALESCE(ID.IDENTITY_ID,SER2.NPI,'')
			,'PERFORMING_PHYSICIAN SPECIALTY'	= ISNULL(ZSPEC.TITLE,'')



FROM  CTE_ACCT_LIST TAL
INNER JOIN CLARITY.DBO.HSP_ACCOUNT AS HAR 
	ON HAR.HSP_ACCOUNT_ID = TAL.HSP_ACCOUNT_ID

--- PUT ALL OF THE PROCEDURE CODE RECORDS TOGETHER INTO A UNION AND THEN DETERMINE IF ICD9 OR 10
INNER JOIN ( SELECT PX.HSP_ACCOUNT_ID
					,PX.LINE
					,PX.FINAL_ICD_PX_ID AS PX_ID
					,PX.PROC_DATE
					,PX.PROC_PERF_PROV_ID
					,'MAIN' AS SOURCE
			FROM CLARITY.DBO.HSP_ACCT_PX_LIST AS PX 
			INNER JOIN CTE_ACCT_LIST AS TAL 
			ON PX.HSP_ACCOUNT_ID = TAL.HSP_ACCOUNT_ID

			UNION ALL

			SELECT PXALT.ACCT_ID AS HSP_ACCOUNT_ID
					,PXALT.LINE
					,PXALT.ICD_PX_ALT_ID AS PX_ID
					,PXALT.ICD_PX_ALT_DATE AS PROC_DATE
					,PXALT.ICD_PX_ALT_PROV_ID AS PROC_PERF_PROV_ID
					,'ALT' AS SOURCE
			FROM CLARITY.DBO.HSP_ACCT_ICDPX_ALT AS PXALT 
				 INNER JOIN CTE_ACCT_LIST AS TAL 
				 ON PXALT.ACCT_ID = TAL.HSP_ACCOUNT_ID
			) AS PX ON HAR.HSP_ACCOUNT_ID = PX.HSP_ACCOUNT_ID

LEFT JOIN CLARITY.DBO.CL_ICD_PX AS ICDPX 
	ON PX.PX_ID = ICDPX.ICD_PX_ID

LEFT JOIN CLARITY.DBO.PATIENT AS PT 
	ON HAR.PAT_ID = PT.PAT_ID

LEFT JOIN CLARITY.DBO.CLARITY_LOC AS LOC 
	ON HAR.LOC_ID = LOC.LOC_ID

LEFT JOIN CLARITY.DBO.CLARITY_SER AS SER 
	ON PX.PROC_PERF_PROV_ID = SER.PROV_ID

LEFT JOIN CLARITY.DBO.CLARITY_SER_2 AS SER2 
	ON SER.PROV_ID = SER2.PROV_ID

--- GET NPI NUMBER IF STORED IN IDENTITY_SER_ID
LEFT JOIN CLARITY.DBO.IDENTITY_SER_ID AS ID 
	ON SER.PROV_ID = ID.PROV_ID 
	AND ID.IDENTITY_TYPE_ID = 60

--- GET PRIMARY SPECIALTY
LEFT JOIN CLARITY.DBO.CLARITY_SER_SPEC AS PSPEC 
	ON SER.PROV_ID = PSPEC.PROV_ID 
	AND PSPEC.LINE = 1
LEFT JOIN CLARITY.DBO.ZC_SPECIALTY AS ZSPEC 
	ON PSPEC.SPECIALTY_C = ZSPEC.SPECIALTY_C

WHERE ICDPX.REF_BILL_CODE_SET_C IN(1,2)
