BEGIN

	USE CLARITY

END
;

--Variables for Recurring/Incremental phase
DECLARE @CurDate DATETIME
DECLARE @BeginDate DATETIME
SET @CurDate = CONVERT(DATETIME, DATEDIFF(DAY, 0, GETDATE()))
SET @BeginDate = DATEADD(DAY,-14,@CurDate) --To modify the lookback period, set the negative integer to the desired number of days (-14 is the default, looking back 14 days)
;

WITH CTE_ACCT_LIST
  AS
  (
        SELECT DISTINCT	HAR.HSP_ACCOUNT_ID
        FROM    CLARITY.dbo.HSP_ACCOUNT AS HAR
        INNER JOIN CLARITY.dbo.HSP_TRANSACTIONS AS HTR     -- Should be good for HB accounts and exclude PB accounts
                ON HTR.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID
		INNER JOIN Clarity.dbo.HSP_ACCT_LAST_UPDATE AS HALU 
                ON HTR.HSP_ACCOUNT_ID = halu.HSP_ACCOUNT_ID
        --WHERE HALU.INST_OF_UPDATE_DTTM >= @BeginDate --Used for Recurring/Incremental phase, comment out for Testing/Historical phase
        WHERE HAR.DISCH_DATE_TIME BETWEEN @STARTDATE AND @ENDDATE --Used for Testing/Historical phase, comment out for Recurring/Incremental phase
), CTE_TX_MOD1 AS
(


	SELECT DISTINCT 		 'HSP_ACCOUNT_ID'			= TAL.HSP_ACCOUNT_ID
							,'TX_ID'					= HTR.TX_ID
							,'MODIFIER1'				= HTRM.EXT_MODIFIER
							
	
	FROM CTE_ACCT_LIST TAL 
	
	INNER JOIN CLARITY.dbo.HSP_TRANSACTIONS HTR
		ON HTR.HSP_ACCOUNT_ID = TAL.HSP_ACCOUNT_ID
		
	INNER JOIN CLARITY.dbo.HSP_TX_MODIFIERS  HTRM
		ON HTRM.TX_ID = HTR.TX_ID AND HTRM.LINE = 1
		
	
), CTE_TX_MOD2 AS
(

	SELECT DISTINCT 		 'HSP_ACCOUNT_ID'			= TAL.HSP_ACCOUNT_ID
							,'TX_ID'					= HTR.TX_ID
							,'MODIFIER2'				= HTRM.EXT_MODIFIER
							
	
	FROM CTE_ACCT_LIST TAL 
	
	INNER JOIN CLARITY.dbo.HSP_TRANSACTIONS HTR
		ON HTR.HSP_ACCOUNT_ID = TAL.HSP_ACCOUNT_ID
		
	INNER JOIN CLARITY.dbo.HSP_TX_MODIFIERS  HTRM
		ON HTRM.TX_ID = HTR.TX_ID AND HTRM.LINE = 2



), CTE_TX_MOD3 AS
(
	SELECT DISTINCT 		 'HSP_ACCOUNT_ID'			= TAL.HSP_ACCOUNT_ID
							,'TX_ID'					= HTR.TX_ID
							,'MODIFIER3'				= HTRM.EXT_MODIFIER
							
	
	FROM CTE_ACCT_LIST TAL 
	
	INNER JOIN CLARITY.dbo.HSP_TRANSACTIONS HTR
		ON HTR.HSP_ACCOUNT_ID = TAL.HSP_ACCOUNT_ID
		
	INNER JOIN CLARITY.dbo.HSP_TX_MODIFIERS  HTRM
		ON HTRM.TX_ID = HTR.TX_ID AND HTRM.LINE = 3

), CTE_TX_MOD4 AS
(
	SELECT DISTINCT 		 'HSP_ACCOUNT_ID'			= TAL.HSP_ACCOUNT_ID
							,'TX_ID'					= HTR.TX_ID
							,'MODIFIER4'				= HTRM.EXT_MODIFIER
							
	
	FROM CTE_ACCT_LIST TAL 
	
	INNER JOIN CLARITY.dbo.HSP_TRANSACTIONS HTR
		ON HTR.HSP_ACCOUNT_ID = TAL.HSP_ACCOUNT_ID
		
	INNER JOIN CLARITY.dbo.HSP_TX_MODIFIERS  HTRM
		ON HTRM.TX_ID = HTR.TX_ID AND HTRM.LINE = 4

)



/******************************************************************************************************************
MAIN CODE GETTING TRANSACTIONS

******************************************************************************************************************/
SELECT  
      'FACILITY_ID'                       = COALESCE(CONVERT(VARCHAR(25),CLARITY_DEP.REV_LOC_ID),CONVERT(VARCHAR(10),TAL.LOC_ID),'')
     ,'HAR_FACILITY_ID'                   = CONVERT(VARCHAR(25),TAL.LOC_ID)
     ,'ACCOUNT_NUMBER'                    = HSP_TRANSACTIONS.HSP_ACCOUNT_ID 
     ,'TRANSACTION_ID'    		 		  = HSP_TRANSACTIONS.TX_ID
     ,'DEPARTMENT_CODE'                   = ISNULL(CONVERT(VARCHAR(18),CLARITY_DEP.DEPARTMENT_ID),'')
     ,'DEPARTMENT_NAME'                   = ISNULL(CLARITY_DEP.DEPARTMENT_NAME,'')
	 ,'REV_LOC_ID'						  = CLARITY_DEP.REV_LOC_ID	
     ,'CPT_CHARGE_CODE'                   = ISNULL(HSP_TRANSACTIONS.CPT_CODE,'')
     ,'HCPCS_CHARGE_CODE'                 = ISNULL(HSP_TRANSACTIONS.HCPCS_CODE,'')
     ,'MODIFIER1'                         = ISNULL(TXM1.MODIFIER1,'') 
     ,'MODIFIER2'                         = ISNULL(TXM2.MODIFIER2,'')
     ,'MODIFIER3'                         = ISNULL(TXM3.MODIFIER3,'')
     ,'MODIFIER4'                         = ISNULL(TXM4.MODIFIER4,'')
     ,'CHARGE_CODE'                       = ISNULL(EAP.PROC_CODE,'') 
     ,'CHARGE_CODE_DESCRIPTION'           = ISNULL(REPLACE(REPLACE(HSP_TRANSACTIONS.PROCEDURE_DESC, '"',''),'|',''),'')
     ,'REVENUE_CODE'                      = ISNULL(CONVERT(VARCHAR(18), CL_UB_REV_CODE.REVENUE_CODE),'')
     ,'CHARGE_AMOUNT'                     = HSP_TRANSACTIONS.TX_AMOUNT 	  
     ,'CHARGE_QUANTITY'                   = HSP_TRANSACTIONS.QUANTITY
     ,'SERVICE_DATE'                      = ISNULL(CONVERT(VARCHAR(10),SERVICE_DATE,101),'')
     ,'POSTING_DATE'                      = CONVERT(VARCHAR(10),TX_POST_DATE,101)
     ,'PERFORMING_PHYSICIAN_CODE'         = ISNULL(CLARITY_SER.PROV_ID,'')
     ,'PERFORMING_PHYSICIAN_NAME'         = ISNULL(CLARITY_SER.PROV_NAME,'')
     ,'PERFORMING_PHYSICIAN_NPI'          = COALESCE(IDENTITY_SER_ID.IDENTITY_ID,SER_2.NPI,'')
     ,'PERFORMING_PHYSICIAN_SPECIALTY'    = ISNULL(ZC_SPECIALTY.TITLE,'')
     ,'BILLING_PHYSICIAN_CODE'            = ISNULL(BILLING_CLARITY_SER.PROV_ID,'')
     ,'BILLING_PHYSICIAN_NAME'            = ISNULL(BILLING_CLARITY_SER.PROV_NAME,'')
     ,'BILLING PHYSICIAN_NPI'             = COALESCE(BILL_IDENTITY_SER_ID.IDENTITY_ID,BILLING_SER_2.NPI,'')
     ,'BILLING_PHYSICIAN_SPECIALTY'       = ISNULL(ZC_SPECIALTY.TITLE,'')
     ,'USER_ID'							  = ISNULL(CONVERT(VARCHAR(18),HSP_TRANSACTIONS.USER_ID),'')
	 ,'MEDICATION_NAME'					  = ISNULL(ERX.NAME,'')



FROM  CTE_ACCT_LIST TAL 

INNER JOIN	CLARITY.dbo.HSP_TRANSACTIONS HSP_TRANSACTIONS
	ON TAL.HSP_ACCOUNT_ID = HSP_TRANSACTIONS.HSP_ACCOUNT_ID AND HSP_TRANSACTIONS.TX_TYPE_HA_C = 1 --- CHARGE TRANSACTION TYPE
        
LEFT OUTER JOIN CLARITY.dbo.PATIENT PATIENT
        ON PATIENT.PAT_ID = TAL.PAT_ID

LEFT OUTER JOIN CLARITY.dbo.ZC_TX_TYPE_HA ZC_TX_TYPE_HA
        ON ZC_TX_TYPE_HA.TX_TYPE_HA_C = HSP_TRANSACTIONS.TX_TYPE_HA_C

LEFT OUTER JOIN CLARITY.dbo.ZC_TX_SOURCE_HA ZC_TX_SOURCE_HA
        ON HSP_TRANSACTIONS.TX_SOURCE_HA_C = ZC_TX_SOURCE_HA.TX_SOURCE_HA_C

LEFT OUTER JOIN CLARITY.dbo.CL_COST_CNTR CL_COST_CNTR
        ON HSP_TRANSACTIONS.COST_CNTR_ID = CL_COST_CNTR.COST_CNTR_ID

LEFT OUTER JOIN CLARITY.dbo.CLARITY_EAP EAP
        ON EAP.PROC_ID = HSP_TRANSACTIONS.PROC_ID
------------- PULL TX MODIFIER INFO
LEFT JOIN  CTE_TX_MOD1 TXM1
		ON TXM1.TX_ID = HSP_TRANSACTIONS.TX_ID
LEFT JOIN  CTE_TX_MOD2 TXM2
		ON TXM2.TX_ID = HSP_TRANSACTIONS.TX_ID
LEFT JOIN  CTE_TX_MOD3 TXM3
		ON TXM3.TX_ID = HSP_TRANSACTIONS.TX_ID
LEFT JOIN  CTE_TX_MOD4 TXM4
		ON TXM4.TX_ID = HSP_TRANSACTIONS.TX_ID

LEFT OUTER JOIN CLARITY.dbo.CLARITY_SA CLARITY_SA
        ON HSP_TRANSACTIONS.SERV_AREA_ID = CLARITY_SA.SERV_AREA_ID
LEFT OUTER JOIN CLARITY.dbo.CLARITY_EMP CLARITY_EMP
        ON HSP_TRANSACTIONS.[USER_ID] = CLARITY_EMP.[USER_ID]
LEFT OUTER JOIN DBO.CLARITY_DEP CLARITY_DEP
        ON CLARITY_DEP.DEPARTMENT_ID = HSP_TRANSACTIONS.DEPARTMENT
LEFT OUTER JOIN CLARITY.dbo.CLARITY_LOC CLARITY_LOC
        ON TAL.LOC_ID = CLARITY_LOC.LOC_ID
        
LEFT JOIN CLARITY.dbo.CLARITY_POS CLARITY_POS 
		ON HSP_TRANSACTIONS.PLACE_OF_SVC_ID = CLARITY_POS.POS_ID

 ------------ PERFORMING PROVIDER INFORMATION
LEFT OUTER JOIN CLARITY.dbo.CLARITY_SER CLARITY_SER
        ON HSP_TRANSACTIONS.PERFORMING_PROV_ID = CLARITY_SER.PROV_ID
LEFT OUTER JOIN CLARITY.dbo.CLARITY_SER_2 SER_2
        ON SER_2.PROV_ID = CLARITY_SER.PROV_ID
LEFT OUTER JOIN CLARITY.dbo.CLARITY_SER_SPEC CLARITY_SER_SPEC
        ON CLARITY_SER_SPEC.PROV_ID = CLARITY_SER.PROV_ID
           AND CLARITY_SER_SPEC.LINE = 1
LEFT OUTER JOIN CLARITY.dbo.ZC_SPECIALTY ZC_SPECIALTY
        ON ZC_SPECIALTY.SPECIALTY_C = CLARITY_SER_SPEC.SPECIALTY_C
LEFT JOIN CLARITY.dbo.IDENTITY_SER_ID AS IDENTITY_SER_ID
        ON IDENTITY_SER_ID.PROV_ID = SER_2.PROV_ID
           AND IDENTITY_SER_ID.IDENTITY_TYPE_ID = 60


 ----------- BILLING PROVIDER INFORMATION
LEFT OUTER JOIN CLARITY.dbo.CLARITY_SER BILLING_CLARITY_SER
        ON HSP_TRANSACTIONS.BILLING_PROV_ID = BILLING_CLARITY_SER.PROV_ID
LEFT OUTER JOIN CLARITY.dbo.CLARITY_SER_2 BILLING_SER_2
        ON BILLING_SER_2.PROV_ID = BILLING_CLARITY_SER.PROV_ID
LEFT OUTER JOIN CLARITY.dbo.CLARITY_SER_SPEC BILLING_CLARITY_SER_SPEC
        ON BILLING_CLARITY_SER_SPEC.PROV_ID = BILLING_CLARITY_SER.PROV_ID
           AND BILLING_CLARITY_SER_SPEC.LINE = 1
LEFT OUTER JOIN CLARITY.dbo.ZC_SPECIALTY BILLING_ZC_SPECIALTY
        ON BILLING_ZC_SPECIALTY.SPECIALTY_C = BILLING_CLARITY_SER_SPEC.SPECIALTY_C
LEFT JOIN CLARITY.dbo.IDENTITY_SER_ID AS BILL_IDENTITY_SER_ID
        ON BILL_IDENTITY_SER_ID.PROV_ID = BILLING_SER_2.PROV_ID
           AND BILL_IDENTITY_SER_ID.IDENTITY_TYPE_ID = 60


------------ UB REV CODES, CLASSES, GROUPER FOR UB REV CODE
LEFT OUTER JOIN CLARITY.dbo.CL_UB_REV_CODE CL_UB_REV_CODE
        ON CL_UB_REV_CODE.UB_REV_CODE_ID = HSP_TRANSACTIONS.UB_REV_CODE_ID
LEFT OUTER JOIN CLARITY.dbo.ZC_UBC_GROUPER ZC_UBC_GROUPER
        ON ZC_UBC_GROUPER.UBC_GROUPER_C = CL_UB_REV_CODE.UBC_GROUPER_C
LEFT OUTER JOIN CLARITY.dbo.ZC_ACCT_BASECLS_HA ZC_ACCT_BASECLS_HA
        ON ZC_ACCT_BASECLS_HA.ACCT_BASECLS_HA_C =TAL.ACCT_BASECLS_HA_C
LEFT OUTER JOIN CLARITY.dbo.ZC_PAT_CLASS ZC_PAT_CLASS
        ON ZC_PAT_CLASS.ADT_PAT_CLASS_C =TAL.ACCT_CLASS_HA_C

----------- PHARMACY MEDICATION NAME
LEFT JOIN CLARITY.dbo.CLARITY_MEDICATION ERX
	ON ERX.MEDICATION_ID = HSP_TRANSACTIONS.ERX_ID