SELECT DISTINCT
   OR_LOG_CHARGES.SUPPLY_ID,
   USED,
   OR_SPLY.SUPPLY_NAME,
   OR_SPLY.PRIMARY_EXT_ID,
   ZC_OR_MANUFACTURER.NAME "MANUFACTURER NAME",
   OR_SPLY_MANFACTR.MAN_CTLG_NUM "MANUFACTURER PART NUMBER" ,
   CASE WHEN OR_LOG_CHARGES.CHARGE_SOURCE_C =4 then 'Y' ELSE 'N' END  ImplantFlag,
   SUPPLY.SURGERY_DATE

FROM
   OR_LOG_CHARGES 
   INNER JOIN
      (
         SELECT
            OR_LOG.LOG_ID,
            OR_LOG.CASE_ID,
            OR_PKLST_SUP_LIST.SUPPLY_ID,
            OR_LOG.SURGERY_DATE,
            SUM(OR_PKLST_SUP_LIST.SUPPLIES_USED) USED 
         FROM
            OR_PKLST 
            INNER JOIN
               OR_LOG 
               ON OR_PKLST.LOG_ID = OR_LOG.LOG_ID 
            INNER JOIN
               OR_PKLST_SUP_LIST 
               ON OR_PKLST.PICK_LIST_ID = OR_PKLST_SUP_LIST.PICK_LIST_ID 
         WHERE
            NULLIF(NULLIF(OR_PKLST_SUP_LIST.IMPLANT_YN, ''), 'N') IS NULL 
            AND NULLIF(OR_PKLST.PICK_LIST_TYPE_C, 99) IS NOT NULL 
            AND NULLIF(OR_PKLST.DELETED_YN, 'N') IS NULL 
         GROUP BY
            OR_LOG.LOG_ID,
            OR_PKLST_SUP_LIST.SUPPLY_ID,
             OR_LOG.CASE_ID,OR_LOG.SURGERY_DATE
      )
      SUPPLY 
      ON OR_LOG_CHARGES.LOG_ID = SUPPLY.LOG_ID 
      LEFT JOIN OR_CASE 
    ON SUPPLY.CASE_ID = OR_CASE.OR_CASE_ID
   LEFT OUTER JOIN
      OR_SPLY_MANFACTR 
      ON OR_LOG_CHARGES.SUPPLY_ID = OR_SPLY_MANFACTR.ITEM_ID 
      AND OR_SPLY_MANFACTR.LINE = 1 
   JOIN
      (
         SELECT DISTINCT
            OR_SPLY.SUPPLY_ID,
            OR_SPLY.SUPPLY_NAME ,
            OR_SPLY.PRIMARY_EXT_ID
            
         FROM
            OR_SPLY
      )
      OR_SPLY 
      ON OR_SPLY.SUPPLY_ID = OR_LOG_CHARGES.SUPPLY_ID 
   LEFT OUTER JOIN
      ZC_OR_MANUFACTURER 
      ON OR_SPLY_MANFACTR.MANUFACTURER_C = ZC_OR_MANUFACTURER.MANUFACTURER_C 
WHERE
OR_CASE.OR_CASE_ID IS NULL
AND SUPPLY.SURGERY_DATE BETWEEN    '01-JAN-2021' and  '31-DEC-2022' 

  -- AND LENGTH(OR_LOG_CHARGES.SUPPLY_ID) > 1 
  

