SELECT DISTINCT
   OR_LOG_CHARGES.SUPPLY_ID,
   SUM(OR_LOG_CHARGES.QUANTITY)
   USED,
   OR_SPLY.SUPPLY_NAME,
   OR_SPLY.PRIMARY_EXT_ID,
   ZC_OR_MANUFACTURER.NAME "MANUFACTURER NAME",
   OR_SPLY_MANFACTR.MAN_CTLG_NUM "MANUFACTURER PART NUMBER" ,
   CASE WHEN OR_LOG_CHARGES.CHARGE_SOURCE_C =4 then 'Y' ELSE 'N' END  ImplantFlag


FROM
   OR_LOG_CHARGES 
 
      LEFT JOIN OR_LOG 
      ON OR_LOG.LOG_ID=OR_LOG_CHARGES.LOG_ID
   LEFT OUTER JOIN
      OR_SPLY_MANFACTR 
      ON OR_LOG_CHARGES.SUPPLY_ID = OR_SPLY_MANFACTR.ITEM_ID 
      AND OR_SPLY_MANFACTR.LINE = 1 
   JOIN
      (
         SELECT DISTINCT
            OR_SPLY.SUPPLY_ID,
            OR_SPLY.SUPPLY_NAME ,
            OR_SPLY.PRIMARY_EXT_ID
            
         FROM
            OR_SPLY
      )
      OR_SPLY 
      ON OR_SPLY.SUPPLY_ID = OR_LOG_CHARGES.SUPPLY_ID 
   LEFT OUTER JOIN
      ZC_OR_MANUFACTURER 
      ON OR_SPLY_MANFACTR.MANUFACTURER_C = ZC_OR_MANUFACTURER.MANUFACTURER_C 
WHERE
OR_LOG.CASE_ID IS NULL
AND OR_LOG_CHARGES.CHRG_SERVICE_DATE BETWEEN    '01-JAN-2021' and  '31-DEC-2022' 

  -- AND LENGTH(OR_LOG_CHARGES.SUPPLY_ID) > 1 
  --- or_log_charges.LOG_ID  =1307024
group by OR_LOG_CHARGES.SUPPLY_ID,

   OR_SPLY.SUPPLY_NAME,
   OR_SPLY.PRIMARY_EXT_ID,
   ZC_OR_MANUFACTURER.NAME ,
   OR_SPLY_MANFACTR.MAN_CTLG_NUM ,
  OR_LOG_CHARGES.CHARGE_SOURCE_C 


