WITH FILLDAT
AS
(
   SELECT  -- *
   dd.CALENDAR_DT
   ,dd.DAY_OF_WEEK
   ,dd.WEEK_NUMBER
   ,dd.DAY_OF_MONTH
   ,dd.MONTH_NAME
    ,dd.MONTH_NUMBER
   ,dd."YEAR"
   ,dd.YEAR_MONTH
   ,dd.weekend_yn
   ,dd.HOLIDAY_YN
   ,dd.MONTHNAME_YEAR
   ,dd.YEAR_END_DT
   FROM DATE_DIMENSION dd
   WHERE
   
       dd.CALENDAR_DT >= TRUNC (ADD_MONTHS (CURRENT_DATE , -1), 'MM') 
  --        AND mared.SCHEDULED_TIME < sysdate
        and dd.CALENDAR_DT < TRUNC (ADD_MONTHS (CURRENT_DATE,0 ), 'MM') 
--        and dd.CALENDAR_DT < TRUNC (ADD_MONTHS (CURRENT_DATE , -1), 'MM') 

   
)
  
,ANTIB
as
(

SELECT 
cm.MEDICATION_ID
,cm.NAME
,coalesce(rx2.SHORT_NAME, zcsg.NAME) "SHORT_NAME"
,zct.NAME   "THERA_CLASS"
,zcpp.NAME  "PHARM_CLASS"
,cm.FORM
,zcar.NAME  "ADMIN_ROUTE"
,zcps.NAME "PHARM_SUBCLASS"
,gcr.GROUPER_ID
,cm.ROUTE  
,CASE WHEN gi.PROV_DISPLAY_NAME IS NULL THEN 'Vancomycin' ELSE  gi.PROV_DISPLAY_NAME END "MED_GROUP"

FROM GROUPER_COMPILED_RECORDS gcr
LEFT OUTER JOIN GROUPER_ITEMS gi ON gcr.GROUPER_ID = gi.GROUPER_ID
LEFT OUTER JOIN clarity_medication cm ON gcr.COMPILED_REC_LIST = cm.MEDICATION_ID
LEFT OUTER JOIN ZC_SIMPLE_GENERIC zcsg ON cm.SIMPLE_GENERIC_C = zcsg.SIMPLE_GENERIC_C
LEFT OUTER JOIN RX_MED_TWO rx2 ON cm.MEDICATION_ID = rx2.MEDICATION_ID
LEFT OUTER JOIN ZC_THERA_CLASS zct ON cm.THERA_CLASS_C = zct.THERA_CLASS_C
LEFT OUTER JOIN ZC_PHARM_CLASS zcpp ON cm.PHARM_CLASS_C = zcpp.PHARM_CLASS_C
LEFT OUTER JOIN ZC_ADMIN_ROUTE zcar ON rx2.ADMIN_ROUTE_C = zcar.MED_ROUTE_C
LEFT OUTER JOIN ZC_PHARM_SUBCLASS zcps ON cm.PHARM_SUBCLASS_C = zcps.PHARM_SUBCLASS_C
WHERE 
--gcr.GROUPER_ID = 115893
gcr.GROUPER_ID IN (115893,115895,408117,115899,115899,115901,115905)

)


SELECT DISTINCT

sfi.DEPT_TARGET_ID  "DEPARTMENT_ID"
,dat.CALENDAR_DT
,dd.DAY_DT    "SOURCE_DT"
,dd.VALUE_DAY  "PATDAYS_NUM"
,0 AS "DAY_OF_THERAPY_IV"
,0 AS "DAY_OF_THERAPY_IM"
,0 AS "DAY_OF_THERAPY_DIGESTIVE"
,0 AS "DAY_OF_THERAPY_RESPIRATORY"
,0 AS "MEDICATION_ID"
,0 AS "ORDER_ID"
,'A' AS "MYGROUP"

FROM METRIC_INFO mi
INNER JOIN SUM_FACTS_INFO sfi ON mi.DEFINITION_ID = sfi.DEFINITION_ID
INNER JOIN daily_Data dd ON sfi.SUM_FACTS_ID = dd.SUM_FACTS_ID
LEFT OUTER JOIN FILLDAT dat ON dd.DAY_DT = dat.CALENDAR_DT

LEFT OUTER JOIN clarity_dep dep ON sfi.DEPT_TARGET_ID = dep.DEPARTMENT_ID

WHERE
dd.DAY_DT >= dat.CALENDAR_DT 
and dd.DAY_DT <= dat.CALENDAR_DT 
AND mi.DEFINITION_ID =11073
AND sfi.DEPT_TARGET_ID IS NOT NULL



UNION ALL

  

SELECT 

fdot.DEPARTMENT_ID  "DEPARTMENT_ID"
,dat.CALENDAR_DT
,fdot.TAKEN_DATE     "SOURCE_DT"
,0 as  "PATDAYS_NUM"
,fdot.DAY_OF_THERAPY_IV
,fdot.DAY_OF_THERAPY_IM
,fdot.DAY_OF_THERAPY_DIGESTIVE
,fdot.DAY_OF_THERAPY_RESPIRATORY
,fdot.MEDICATION_ID
,fdot.ORDER_ID
,'B' AS "MYGROUP"

FROM CLARITY_ADT adt
INNER JOIN order_med om ON adt.PAT_ENC_CSN_ID = om.PAT_ENC_CSN_ID
INNER JOIN F_DOT_CONTRIB_ORDS_DEPT fdot ON om.ORDER_MED_ID = fdot.ORDER_ID
inner join ANTIB anti on fdot.medication_id = anti.MEDICATION_ID
LEFT OUTER JOIN FILLDAT dat ON fdot.TAKEN_DATE = dat.CALENDAR_DT
LEFT OUTER JOIN clarity_dep dep ON fdot.DEPARTMENT_ID = dep.DEPARTMENT_ID
INNER JOIN patient pat ON fdot.PAT_ID = pat.PAT_ID
INNER JOIN patient_3 pat3 ON pat.PAT_ID = pat3.PAT_ID

WHERE
adt.EVENT_SUBTYPE_C <> 2  ---- deleted
AND adt.EVENT_TYPE_C IN (1,3)
--AND TRUNC( fdot.TAKEN_DATE) >= '1-jan-2021' 
--AND TRUNC( fdot.TAKEN_DATE) <= '31-jan-2021' 
AND fdot.TAKEN_DATE >= dat.CALENDAR_DT 
AND fdot.TAKEN_DATE <= dat.CALENDAR_DT
AND pat3.IS_TEST_PAT_YN <> 'Y'
--AND fdot.DEPARTMENT_ID = 1000108008


to_number