SELECT 
EXTRACT(month FROM fadt.CALENDAR_DT) "Month"
,fadt.CALENDAR_DT
,zcps.NAME
,dep.DEPARTMENT_ID
,dep.DEPARTMENT_NAME 
,fadt.PAT_DAY_VALUE
,parloc.LOC_ID
,parloc.LOC_NAME  
,zcbc.NAME  "BASE_CLASS"
,zcet.NAME "EVENT_NAME"
,zcps.NAME "SERVICE"
,fadt.PAT_ENC_CSN_ID
FROM F_ADT_TX fadt
LEFT OUTER JOIN clarity_dep dep ON fadt.DEPARTMENT_ID = dep.DEPARTMENT_ID
LEFT OUTER JOIN clarity_loc loc ON dep.REV_LOC_ID = loc.LOC_ID
LEFT OUTER JOIN clarity_loc parloc ON loc.HOSP_PARENT_LOC_ID = parloc.LOC_ID
LEFT OUTER JOIN zc_pat_service zcps ON fadt.PAT_SERVICE_C = zcps.HOSP_SERV_C
LEFT OUTER JOIN ZC_REP_BASE_CLASS zcbc ON fadt.BASE_CLASS_C = zcbc.INT_REP_BASE_CLS_C
LEFT OUTER JOIN ZC_EVENT_TYPE zcet ON fadt.INT_EVENT_TYPE_C = zcet.EVENT_TYPE_C
LEFT OUTER JOIN ZC_PAT_SERVICE zcps ON fadt.PAT_SERVICE_C = zcps.HOSP_SERV_C
WHERE
 fadt.CALENDAR_DT >= '1-jan-2020'
AND fadt.CALENDAR_DT <= '31-May-2020'
AND fadt.PAT_DAY_VALUE IS NOT null
AND fadt.INT_EVENT_TYPE_C = 6 ---- census
