SELECT
	HAR.HSP_ACCOUNT_ID AS ACCOUNTNUMBER,
	CASE 
		WHEN HAR.LOC_ID IS NOT NULL 
		THEN HAR.LOC_ID 
		ELSE NULL 
	END                    AS FACILITYCODE,
	CASE 
		WHEN BKTINV.INVOICE_NUMBER IS NOT NULL 
		THEN BKTINV.INVOICE_NUMBER 
		ELSE NULL 
	END                    AS PATIENTCONTROLNUMBER 
FROM
	HSP_ACCOUNT HAR 
		LEFT OUTER JOIN HSP_BUCKET BKT 
		ON BKT.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID 
		LEFT OUTER JOIN HSP_BKT_INV_NUM BKTINV 
		ON BKTINV.BUCKET_ID = BKT.BUCKET_ID 
		LEFT OUTER JOIN ACCOUNT EAR 
		ON EAR.ACCOUNT_ID = HAR.GUARANTOR_ID 
		LEFT OUTER JOIN HSP_ACCT_LAST_UPDATE HARUP 
		ON HARUP.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID 
WHERE
	HAR.HSP_ACCOUNT_ID IS NOT NULL AND
	TO_DATE(HARUP.INST_OF_UPDATE_DTTM, 'DD/MM/YYYY') BETWEEN TO_DATE(SYSDATE - 3, 'DD/MM/YYYY') AND
	TO_DATE(SYSDATE - 1, 'DD/MM/YYYY') AND
	EAR.ACCOUNT_TYPE_C NOT IN ('101',
	'102') AND
	HAR.ACCT_FIN_CLASS_C != 4 AND -- Remove self-pay accounts. STSK0769632
	HAR.NUM_OF_CHARGES > 0 AND
	BKTINV.BUCKET_ID IS NOT NULL