 SELECT 
    V_ARPB_REMIT_CODES.MATCH_CHG_TX_ID
    , V_ARPB_REMIT_CODES.PAT_ID
    , V_ARPB_REMIT_CODES.ACCOUNT_ID
    , V_ARPB_REMIT_CODES.MATCH_CHG_TX_NUM
    , V_ARPB_REMIT_CODES.DEPT_NM_WID
    , V_ARPB_REMIT_CODES.LOC_NM_WID
    , V_ARPB_REMIT_CODES.MATCH_CHG_ORIG_AMT
    , V_ARPB_REMIT_CODES.BILLING_PROV_NM_WID
    , V_ARPB_REMIT_CODES.CPT_CODE
    , V_ARPB_REMIT_CODES.PAYMENT_POST_DATE
    , V_ARPB_REMIT_CODES.PAYMENT_TX_ID
    , V_ARPB_REMIT_CODES.INVOICE_NUM
    , V_ARPB_REMIT_CODES.EOB_CODES
    , V_ARPB_REMIT_CODES.REMIT_CODE_NAME
    , V_ARPB_REMIT_CODES.REMIT_ACTION_NAME
    , V_ARPB_REMIT_CODES.REMIT_CODE_CAT_NAME
    , V_ARPB_REMIT_CODES.REMIT_CODE_TYPE_NAME
    , PMT_EOB_INFO_I_1.DENIAL_CODES
    , V_ARPB_REMIT_CODES.PAYOR_NM_WID
    , V_ARPB_REMIT_CODES.PAYOR_FIN_CLASS_NM_WID
    , V_ARPB_REMIT_CODES.PLAN_NM_WID
    , V_ARPB_REMIT_CODES.NON_PRIMARY_YN
    , V_ARPB_REMIT_CODES.EOB_ICN
    , V_ARPB_REMIT_CODES.SERV_AREA_ID
    , V_ARPB_REMIT_CODES.REMIT_ACTION
    , V_ARPB_REMIT_CODES.REMIT_CODE_TYPE_C
    , V_ARPB_REMIT_CODES.REMIT_AMOUNT
    , V_ARPB_REMIT_CODES.SERVICE_DATE
    , CLARITY_DEP.DEPARTMENT_NAME
    , CLARITY_DEP.DEPARTMENT_ID
    , V_ARPB_REMIT_CODES.APPT_DEPT_ID
    , V_ARPB_REMIT_CODES.SOURCE_AREA_NAME
    , REMARK_1.REMIT_CODE_NAME
    , REMARK_2.REMIT_CODE_NAME
    , REMARK_3.REMIT_CODE_NAME
    , REMARK_4.REMIT_CODE_NAME
    , V_ARPB_REMIT_CODES.BILL_AREA_NM_WID
    , V_ARPB_REMIT_CODES.FIN_SUBDIV_NM_WID
    , V_ARPB_REMIT_CODES.FIN_DIV_NM_WID
    , REMARK_4.RMC_EXTERNAL_ID
    , REMARK_1.RMC_EXTERNAL_ID
    , REMARK_2.RMC_EXTERNAL_ID
    , REMARK_3.RMC_EXTERNAL_ID
    , V_ARPB_REMIT_CODES.POS_NM_WID
    , V_ARPB_REMIT_CODES.SERVICE_AREA_NM_WID
    , CLARITY_RMC.PREVENTABLE_YN
 FROM V_ARPB_REMIT_CODES V_ARPB_REMIT_CODES 
    LEFT OUTER JOIN PMT_EOB_INFO_I PMT_EOB_INFO_I_1 ON V_ARPB_REMIT_CODES.PAYMENT_TX_ID = PMT_EOB_INFO_I_1.TX_ID
        AND V_ARPB_REMIT_CODES.EOB_LINE = PMT_EOB_INFO_I_1.LINE 
    LEFT OUTER JOIN CLARITY_RMC REMARK_1 ON V_ARPB_REMIT_CODES.REMARK_CODE_1_ID = REMARK_1.REMIT_CODE_ID
    LEFT OUTER JOIN CLARITY_RMC REMARK_2 ON V_ARPB_REMIT_CODES.REMARK_CODE_2_ID = REMARK_2.REMIT_CODE_ID
    LEFT OUTER JOIN CLARITY_RMC REMARK_3 ON V_ARPB_REMIT_CODES.REMARK_CODE_3_ID = REMARK_3.REMIT_CODE_ID
    LEFT OUTER JOIN CLARITY_RMC REMARK_4 ON V_ARPB_REMIT_CODES.REMARK_CODE_4_ID = REMARK_4.REMIT_CODE_ID
    LEFT OUTER JOIN CLARITY_DEP CLARITY_DEP ON V_ARPB_REMIT_CODES.APPT_DEPT_ID = CLARITY_DEP.DEPARTMENT_ID 
    LEFT OUTER JOIN CLARITY_RMC CLARITY_RMC ON V_ARPB_REMIT_CODES.REMIT_CODE_ID = CLARITY_RMC.REMIT_CODE_ID
-- WHERE  (V_ARPB_REMIT_CODES.PAYMENT_POST_DATE>={ts '2016-06-18 00:00:00'} 
--    AND V_ARPB_REMIT_CODES.PAYMENT_POST_DATE<{ts '2016-07-18 00:00:00'})
 WHERE  V_ARPB_REMIT_CODES.PAYMENT_POST_DATE >= to_date('06/01/2016', 'MM-DD-YYYY') 
    AND V_ARPB_REMIT_CODES.PAYMENT_POST_DATE <= to_date('06/07/2016', 'MM-DD-YYYY')



