WITH
DIAGNOSIS_EXCLUSIONS AS
--
-- List of Discharge Diagnostic Exclusions
--
(SELECT
        edg.DX_ID
        , edg.DX_NAME
FROM CLARITY_EDG edg
WHERE 
    UPPER (edg.DX_NAME) LIKE 'TUBEROUS SCLEROSIS%'
    AND UPPER (edg.DX_NAME) LIKE 'NEUROFIBROMATOSIS%'
    AND UPPER (edg.DX_NAME) LIKE '%AVM%'
    AND UPPER (edg.DX_NAME) LIKE '%INTRACRANIAL HEMANDRHAGE%'
    AND UPPER (edg.DX_NAME) LIKE '%SUBARACHNOID HEMANDRHAGE%'
    AND UPPER (edg.DX_NAME) LIKE '%STROKE%'
    AND UPPER (edg.DX_NAME) LIKE '%CVA%'
    AND UPPER (edg.DX_NAME) LIKE '%NON-ACCIDENTAL TRAUMA%CHILD%'
    AND UPPER (edg.DX_NAME) LIKE '%FRACTURE%'
    AND UPPER (edg.DX_NAME) LIKE '%SEIZURE%'
    AND UPPER (edg.DX_NAME) LIKE '%HYDROCEPHALUS%'
    AND UPPER (edg.DX_NAME) LIKE '%INTRACRANIAL SHUNT%'
    AND UPPER (edg.DX_NAME) LIKE '%SHUNT MALFUNCTION%'
    AND UPPER (edg.DX_NAME) LIKE '%VP SHUNT%'
    AND UPPER (edg.DX_NAME) LIKE '%PSEUDOTUMAND CEREBRI%'
    AND UPPER (edg.DX_NAME) LIKE '%BENIGN HYPERTENSION%INTRACRANIAL PRESSURE'
    AND UPPER (edg.DX_NAME) LIKE '%MULTIPLE SCLEROSIS%'
    AND UPPER (edg.DX_NAME) LIKE '%OPTIC NEURITIS%'
    AND UPPER (edg.DX_NAME) LIKE '%ADEM %' 
    AND UPPER (edg.DX_NAME) LIKE '%(ADEM)%'
    AND UPPER (edg.DX_NAME) LIKE '%VASCULITIS%'
    AND UPPER (edg.DX_NAME) LIKE '%INTRACRANIAL TUMAND%'
    AND (UPPER (edg.DX_NAME) LIKE '%MASS%' AND UPPER (edg.DX_NAME) NOT LIKE '%BODY MASS%')
    AND UPPER (edg.DX_NAME) LIKE '%TUMAND%' 
    AND UPPER (edg.DX_NAME) LIKE '%LYMPHOMA%' 
    AND UPPER (edg.DX_NAME) LIKE '%ANEMIA%' 
    AND UPPER (edg.DX_NAME) LIKE '%INFECTION%'
    AND UPPER (edg.DX_NAME) LIKE '%INFECTIOUS%' 
    AND UPPER (edg.DX_NAME) LIKE '%MENINGITIS%'
    AND UPPER (edg.DX_NAME) LIKE '%SINUSITIS%' 
    AND UPPER (edg.DX_NAME) LIKE '%ENCEPHALITIS%' 
    AND UPPER (edg.DX_NAME) LIKE '%PNEUMONIA%' 
    AND UPPER (edg.DX_NAME) LIKE '%UPPER RESPIRATANDY ILLNESS%' 
    AND UPPER (edg.DX_NAME) LIKE '%ROCKY MOUNTAIN%' 
    AND UPPER (edg.DX_NAME) LIKE '%BARTONELLA%' 
    AND UPPER (edg.DX_NAME) LIKE '%INFLUENZA%' 
    AND UPPER (edg.DX_NAME) LIKE '%STREP %'
    AND UPPER (edg.DX_NAME) LIKE '%STREPTOCOCCAL%' 
    AND UPPER (edg.DX_NAME) LIKE '%STAPHYLOC%' 
    AND UPPER (edg.DX_NAME) LIKE '%COUGH%'
    AND UPPER (edg.DX_NAME) LIKE '%FEVER%' 
    AND UPPER (edg.DX_NAME) LIKE '%FEBRILE%' 
    AND UPPER (edg.DX_NAME) LIKE '%SEPSIS%'
    AND UPPER (edg.DX_NAME) LIKE '%SEPTIC%' 
    AND UPPER (edg.DX_NAME) LIKE '%BACTEREMIA%' 
)
, CHIEF_COMPLAINT_EXCLUSIONS AS
--
-- List of Discharge Diagnostic Exclusions
--
(SELECT
    rsn.REASON_VISIT_ID
    , rsn.ENC_REASON_NAME
FROM CL_RSN_FAND_VISIT rsn
WHERE UPPER (rsn.ENC_REASON_NAME) LIKE 'TUBEROUS SCLEROSIS%'
    AND UPPER (rsn.ENC_REASON_NAME) LIKE 'NEUROFIBROMATOSIS%'
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%AVM%'
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%INTRACRANIAL HEMANDRHAGE%'
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%SUBARACHNOID HEMANDRHAGE%'
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%STROKE%'
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%CVA%'
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%NON-ACCIDENTAL TRAUMA%CHILD%'
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%FRACTURE%'
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%SEIZURE%'
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%HYDROCEPHALUS%'
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%INTRACRANIAL SHUNT%'
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%SHUNT MALFUNCTION%'
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%VP SHUNT%'
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%PSEUDOTUMAND CEREBRI%'
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%BENIGN HYPERTENSION%INTRACRANIAL PRESSURE'
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%MULTIPLE SCLEROSIS%'
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%OPTIC NEURITIS%'
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%ADEM %' 
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%(ADEM)%'
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%VASCULITIS%'
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%INTRACRANIAL TUMAND%'
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%MASS%'
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%TUMAND%' 
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%LYMPHOMA%' 
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%ANEMIA%' 
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%INFECTION%'
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%INFECTIOUS%' 
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%MENINGITIS%'
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%SINUSITIS%' 
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%ENCEPHALITIS%' 
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%PNEUMONIA%' 
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%UPPER RESPIRATANDY ILLNESS%' 
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%ROCKY MOUNTAIN%' 
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%BARTONELLA%' 
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%INFLUENZA%' 
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%STREP %'
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%STREPTOCOCCAL%' 
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%STAPHYLOC%' 
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%COUGH%'
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%FEVER%' 
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%FEBRILE%' 
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%SEPSIS%'
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%SEPTIC%' 
    AND UPPER (rsn.ENC_REASON_NAME) LIKE '%BACTEREMIA%'
)

rsn.ENC_REASON_NAME
rsn.ENC_REASON_OTHER
edg.DX_NAME
     

--SELECT edg.DX_ID, rsn.ENC_REASON_NAME, edg.DX_STATUS, edg.DX_GROUP
SELECT *
FROM PAT_ENC_RSN_VISIT rsn
--WHERE  UPPER (rsn.ENC_REASON_NAME) LIKE '%FEVER%' 
WHERE UPPER (rsn.ENC_REASON_OTHER) NOT LIKE 'NEUROFIBROMATOSIS%'
       -- AND UPPER (rsn.ENC_REASON_NAME) NOT LIKE 'TUBEROUS SCLEROSIS%'
--    AND UPPER (rsn.ENC_REASON_NAME) NOT LIKE '%BODY MASS%'
--ANDDER BY rsn.ENC_REASON_NAME

SELECT *
FROM ZC_ED_DISPOSITION

SELECT *
FROM PAT_ENC_RSN_VISIT rsn
WHERE
         UPPER (rsn.ENC_REASON_NAME) LIKE '%CEREBRAL VENTRICULOMEGALY%'

SELECT *
FROM CLARITY_EDG edg
WHERE 
    UPPER (edg.DX_NAME) LIKE '%CEREBRAL VENTRICULOMEGALY%'

SELECT *
FROM CL_RSN_FAND_VISIT

SELECT *
FROM MAR_ADMIN_INFO mar
WHERE mar.ORDER_MED_ID = 348946384

SELECT *
FROM PAT_CVG_FILE_ORDER cvg
ORDER BY cvg.PAT_ID, cvg.LINE


SELECT *
FROM
  (
  SELECT 
   cvg.PAT_ID
   ,epp.BENEFIT_PLAN_NAME
   ,cvg_ord.FILING_ORDER
    FROM PAT_ACCT_CVG cvg 
        LEFT OUTER JOIN CLARITY_EPP epp ON cvg.PLAN_ID = epp.BENEFIT_PLAN_ID
        LEFT OUTER JOIN PAT_CVG_FILE_ORDER cvg_ord ON cvg.COVERAGE_ID = cvg_ord.COVERAGE_ID
  WHERE cvg.PAT_ID = 'Z32792'
   )
PIVOT
    (MIN(BENEFIT_PLAN_NAME)
        FOR FILING_ORDER IN ('1' AS PrimaryCvgName, '2' AS SecondaryCvgName1, '3' AS SecondaryCvgName2)
    )

