SELECT --*
pat.PAT_MRN_ID
,om.ORDERING_DATE  "SERVICE_DATE"
,om.ORDER_MED_ID
,dep.DEPARTMENT_NAME  "PATIENT_UNIT"
,parloc.LOC_NAME
,serphrm.PROV_NAME     "VERBAL_COMMAND_PROV"
,serauth.PROV_NAME   "AUTHORIZING_PROV"
,om.DISPLAY_NAME
,om.DISCON_TIME
,zcvt.NAME    "SIGNED_TYPE"

FROM ORDER_SIGNED_MED osm
INNER JOIN order_med om ON osm.ORDER_MED_ID = om.ORDER_MED_ID
INNER JOIN patient pat ON om.PAT_ID = pat.PAT_ID
LEFT OUTER JOIN clarity_ser serphrm ON osm.VERB_COMM_PROV_ID = serphrm.PROV_ID
LEFT OUTER JOIN clarity_ser serauth ON om.AUTHRZING_PROV_ID = serauth.PROV_ID
LEFT OUTER JOIN clarity_dep dep ON om.PAT_LOC_ID = dep.DEPARTMENT_ID
LEFT OUTER JOIN clarity_loc loc ON dep.REV_LOC_ID = loc.LOC_ID
LEFT OUTER JOIN clarity_loc parloc ON loc.HOSP_PARENT_LOC_ID = parloc.LOC_ID
LEFT OUTER JOIN ZC_VERB_ORD_TYPE zcvt ON osm.SIGNED_TYPE_C = zcvt.SIGNED_TYPE_C
LEFT OUTER JOIN ZC_ORDERING_MODE zcom ON om.ORDERING_MODE_C = zcom.ORDERING_MODE_C
WHERE
osm.VERBAL_MODE_C = 30410904
--AND om.ORDERING_DATE >= '1-jul-2021'
      AND  om.ORDERING_DATE >= EPIC_UTIL.EFN_DIN('{?Begin Date}') 
      AND  om.ORDERING_DATE <= EPIC_UTIL.EFN_DIN('{?End Date}') 

