SELECT
	CASE 
		WHEN HAR.HSP_ACCOUNT_ID IS NOT NULL 
		THEN HAR.HSP_ACCOUNT_ID 
		ELSE NULL 
	END AS ACCOUNTNUMBER,
	CASE 
		WHEN HAR.LOC_ID IS NOT NULL 
		THEN HAR.LOC_ID 
		ELSE NULL 
	END AS FACILITYCODE,
	CASE 
		WHEN PX.PROC_DATE IS NOT NULL 
		THEN TO_CHAR(TRUNC(PX.PROC_DATE), 'mm/dd/yyyy') 
		ELSE NULL 
	END AS PROCEDUREDATE,
	CASE 
		WHEN PX.LINE IS NOT NULL 
		THEN PX.LINE 
		ELSE NULL 
	END AS PROCEDUREORDER,
	CASE 
		WHEN ICDPX.REF_BILL_CODE IS NOT NULL 
		THEN ICDPX.REF_BILL_CODE 
		ELSE NULL 
	END AS PROCEDURECODE,
	CASE 
		WHEN SER2.NPI IS NOT NULL 
		THEN SER2.NPI 
		ELSE NULL 
	END AS RENDERINGPHYSICIANNPI 
FROM
	HSP_ACCOUNT HAR 
		LEFT OUTER JOIN HSP_ACCT_PX_LIST PX 
		ON PX.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID 
		LEFT OUTER JOIN CLARITY_SER_2 SER2 
		ON SER2.PROV_ID = PX.PROC_PERF_PROV_ID 
		LEFT OUTER JOIN CL_ICD_PX ICDPX 
		ON ICDPX.ICD_PX_ID = PX.FINAL_ICD_PX_ID 
		LEFT OUTER JOIN ACCOUNT EAR 
		ON EAR.ACCOUNT_ID = HAR.GUARANTOR_ID 
		LEFT OUTER JOIN HSP_ACCT_LAST_UPDATE HARUP 
		ON HARUP.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID 
WHERE
	TO_DATE(HARUP.INST_OF_UPDATE_DTTM, 'DD/MM/YYYY') BETWEEN TO_DATE(SYSDATE - 3, 'DD/MM/YYYY') AND
	TO_DATE(SYSDATE - 1, 'DD/MM/YYYY') AND
	HAR.NUM_OF_CHARGES > 0 AND
	PX.HSP_ACCOUNT_ID IS NOT NULL AND
	EAR.ACCOUNT_TYPE_C NOT IN ('101',
	'102') AND
	HAR.ACCT_FIN_CLASS_C != 4 -- Remove self-pay accounts. STSK0769632