--SELECT dep.*
SELECT dep.DEPARTMENT_ID, dep.DEPARTMENT_NAME, dep.DEPT_ABBREVIATION, loc.LOC_NAME, loc.LOC_ID, dep.RPT_GRP_EIGHT
FROM CLARITY_DEP dep INNER JOIN 
	CLARITY_LOC loc ON dep.REV_LOC_ID = loc.LOC_ID LEFT OUTER JOIN
	F_PAT_ICU_LOCATION icu ON icu.DEPARTMENT_ID = dep.DEPARTMENT_ID
WHERE 
	dep.RPT_GRP_EIGHT IN ('3','4','5','11')
	AND loc.LOC_ID = 10001

SELECT *
FROM CLARITY_DEP dep
WHERE dep.DEPARTMENT_NAME LIKE '%NEONATAL%'
--SELECT pat.PAT_MRN_ID, pat.PAT_NAME, enc.DEPARTMENT_ID
--FROM PAT_ENC enc INNER JOIN 
--	PATIENT pat ON pat.PAT_ID = enc.PAT_ID
--WHERE enc.DEPARTMENT_ID = '1000116038' AND enc.CONTACT_DATE >= to_date('07/01/2015', 'DD-MM-YYYY')


SELECT *
FROM ZC_DEP_RPT_GRP_8

SELECT *
FROM CLARITY_ADT adt
        INNER JOIN EVENT_NOTIF_HX hx ON adt.PAT_ENC_CSN_ID = hx.PAT_ENC_CSN_ID
--WHERE adt.EVENT_ID IN ('6268522','6268641','6268711','6292581','6313011')
WHERE adt.PAT_ENC_CSN_ID = 30042308832
        AND adt.EVENT_TYPE_C IN ('3','4') 
        AND hx.EVENT_TYPE_C = '22'
        AND adt.EVENT_ID IN (6292580,6292581)
ORDER BY adt.EVENT_ID

SELECT *
-- hx.PEND_ID
--        , hx.LINE
--        , hx.UPDATE_USER_ID
FROM BED_PLAN_HX hx
WHERE hx.LINKED_EVENT_ID IN (6292580,6292581)

SELECT *
FROM PEND_ACTION pnd
WHERE pnd.PAT_ENC_CSN_ID = 30042308832
        AND pnd.PEND_EVENT_TYPE_C = 3

SELECT *
FROM EVENT_NOTIF_HX adt
WHERE adt.PAT_ENC_CSN_ID = 30042308832
       AND adt.EVENT_TYPE_C IN ('3','22')