--SELECT * FROM F_PAT_ICU_LOCATION

SELECT *
FROM CLARITY_EDG edg
WHERE edg.REF_BILL_CODE_SET_C = '1' AND edg.CURRENT_ICD10_LIST = 'A15.6'
--WHERE edg.REF_BILL_CODE = 'A15.6'

--SELECT edg.DX_ID, edg.DX_NAME, edg.ICD9_CODE
--FROM CLARITY_EDG edg
---- WHERE REGEXP_LIKE (edg.DX_NAME, '\((1|2|3|4|5|6|7|8|9|0)\)')
----WHERE REGEXP_LIKE (edg.DX_NAME, '\([0-9]+\)')
--WHERE REGEXP_LIKE (edg.DX_NAME, '\([0-9] \. ([0-9]+)\)')
