SELECT
    COUNT(DISTINCT lda.IP_LDA_ID) "Procedure_Count"
    , EXTRACT(YEAR FROM hsp.HOSP_ADMSN_TIME) AS "Procedure_Year"
    , EXTRACT(MONTH FROM hsp.HOSP_ADMSN_TIME) AS "Procedure_Month"
    ,  'Flow Sheet Measures' AS "SOM_Module"
    ,  'Nasogastric Tube Placement' AS "Proc_Category" 
FROM
    CLARITY.PAT_ENC_HSP hsp
    INNER JOIN  CLARITY.IP_FLOWSHEET_ROWS ip ON hsp.INPATIENT_DATA_ID = ip.INPATIENT_DATA_ID
    INNER JOIN CLARITY.IP_LDA_NOADDSINGLE lda ON ip.IP_LDA_ID = lda.IP_LDA_ID AND ip.FLO_MEAS_ID = lda.FLO_MEAS_ID
WHERE
  	NOT ip.FLOWSHT_ROW_NAME LIKE '%REMOVED%'
  	AND NOT lda.DESCRIPTION LIKE '%REMOVED%'
    AND hsp.HOSP_ADMSN_TIME >= ADD_MONTHS(SYSDATE, -12)
    AND ((ip.FLOWSHT_ROW_NAME LIKE '%Feeding%'
       AND ip.FLOWSHT_ROW_NAME LIKE '%Tube%'
       AND ip.FLOWSHT_ROW_NAME LIKE '%Nasogast%')
       OR
       (ip.FLOWSHT_ROW_NAME LIKE '%NG/OG%'
       AND ip.FLOWSHT_ROW_NAME LIKE '%Tube%'
       AND ip.FLOWSHT_ROW_NAME LIKE '%Nasogast%')) 
GROUP BY 
    EXTRACT(YEAR FROM hsp.HOSP_ADMSN_TIME)
    , EXTRACT(MONTH FROM hsp.HOSP_ADMSN_TIME)
