SELECT
DISTINCT 
pat.PAT_NAME
,pat.BIRTH_DATE
,sex.NAME as SEX
,TRUNC((HAR.DISCH_DATE_TIME - PAT.BIRTH_DATE) / 365.25) "PAT_AGE_AT_TIME_PROC"
,TRUNC((SYSDATE- PAT.BIRTH_DATE) / 365.25) "PAT_AGE"
,RACE.NAME as ETHNICITY_RACE
,ENC.HEIGHT
,HAR.HSP_ACCOUNT_ID
,HAR.HSP_ACCOUNT_NAME
,HAR.ADM_DATE_TIME
,HAR.DISCH_DATE_TIME
,enc.DEPARTMENT_ID AS PRIM_ENC_DEPT_ID
,DEP.DEPARTMENT_NAME AS PRIM_ENC_DEPT_NAME
,eap.PROC_NAME as PROC_NAME
,ACC_NUM as "ACCESSION"
FROM HSP_TRANSACTIONS TX
INNER JOIN HSP_ACCOUNT HAR ON TX.HSP_ACCOUNT_ID = HAR.HSP_ACCOUNT_ID
LEFT JOIN CLARITY_EAP eap on TX.PROC_ID=eap.PROC_ID
LEFT JOIN PAT_ENC  ENC ON ENC.PAT_ENC_CSN_ID = HAR.PRIM_ENC_CSN_ID
LEFT JOIN  ORDER_PROC  ord on ENC.PAT_ENC_CSN_ID=ord.PAT_ENC_CSN_ID
LEFT  JOIN ORDER_RAD_ACC_NUM num on ord.ORDER_PROC_ID=num.ORDER_PROC_ID
LEFT  JOIN PATIENT pat on ENC.PAT_ID = pat.PAT_ID
LEFT JOIN PATIENT_RACE pat_race on pat.PAT_ID=pat_race.PAT_ID
LEFT JOIN ZC_PATIENT_RACE race on pat_race.PATIENT_RACE_C=race.PATIENT_RACE_C
LEFT  JOIN ZC_SEX sex  on pat.SEX_C=sex.RCPT_MEM_SEX_C
LEFT JOIN CLARITY_DEP DEP ON DEP.DEPARTMENT_ID = ENC.DEPARTMENT_ID
WHERE HAR.ADM_DATE_TIME >= '01-DEC-2015' AND HAR.ADM_DATE_TIME <= SYSDATE
AND TX.CPT_CODE IN ('77072')----
MINUS 
select  distinct pat.PAT_NAME
,pat.BIRTH_DATE
,sex.NAME as SEX
,TRUNC((ARPB.SERVICE_DATE - PAT.BIRTH_DATE) / 365.25) "PAT_AGE_AT_TIME_PROC"
,TRUNC((SYSDATE- PAT.BIRTH_DATE) / 365.25) "PAT_AGE"
,RACE.NAME as ETHNICITY_RACE
,ENC.HEIGHT
,ARPB.ACCOUNT_ID
,ARPB.SERVICE_DATE
,ACC.ACCOUNT_NAME

,ENC.HOSP_ADMSN_TIME
,ENC.HOSP_DISCHRG_TIME
,enc.DEPARTMENT_ID AS PRIM_ENC_DEPT_ID
,DEP.DEPARTMENT_NAME AS PRIM_ENC_DEPT_NAME
,eap.PROC_NAME as PROC_NAME
,ACC_NUM as "ACCESSION"
  FROM ARPB_TRANSACTIONS ARPB 
  LEFT JOIN ACCOUNT ACC on ARPB.ACCOUNT_ID=ACC.ACCOUNT_ID
LEFT JOIN CLARITY_EAP eap on ARPB.PROC_ID=eap.PROC_ID
LEFT JOIN PAT_ENC  ENC ON ENC.PAT_ENC_CSN_ID = ARPB.PAT_ENC_CSN_ID
LEFT JOIN  ORDER_PROC  ord on ENC.PAT_ENC_CSN_ID=ord.PAT_ENC_CSN_ID
LEFT  JOIN ORDER_RAD_ACC_NUM num on ord.ORDER_PROC_ID=num.ORDER_PROC_ID
LEFT  JOIN PATIENT pat on ENC.PAT_ID = pat.PAT_ID
LEFT JOIN PATIENT_RACE pat_race on pat.PAT_ID=pat_race.PAT_ID
LEFT JOIN ZC_PATIENT_RACE race on pat_race.PATIENT_RACE_C=race.PATIENT_RACE_C
LEFT  JOIN ZC_SEX sex  on pat.SEX_C=sex.RCPT_MEM_SEX_C
LEFT JOIN CLARITY_DEP DEP ON DEP.DEPARTMENT_ID = ENC.DEPARTMENT_ID
WHERE ARPB.SERVICE_DATE >= '01-DEC-2015' AND ARPB.SERVICE_DATE <= SYSDATE
AND ARPB.CPT_CODE IN ('77072')
and ARPB.TX_TYPE_C =1----


select * from PAT_ENC where PAT_ID='Z1434502'--30115900526

select * from HSP_ACCOUNT where PRIM_ENC_CSN_ID='30115900526'
select * From HSP_TRANSACTIONS where HSP_ACCOUNT_ID = 432858457


select ord_rad_acc_num  from order_proc

select * from ORDER_PROC 


select  *  From HSP_TRANSACTIONS where CPT_CODE=  '77072'

select * From HSP_ACCOUNT where HSP_ACCOUNT_NAME like 'JUSTIN%'

select * from patient where PAT_ID ='Z1434502'
select * from order_PROC where PAT_ID ='Z1434502'


order_rad_acc_num
 

select CPT_CODE from HSP_TRANSCATONS 

select * from PATIENT_RACE 
 from ZC_ACC_RACE

select *  from ACCCATH3_ADMISSION


select * from  patient