WITH ACCT_DX AS
(SELECT  
HSP_ACCOUNT.HSP_ACCOUNT_ID
,HSP_ACCOUNT.PAT_ID
,HSP_ACCOUNT.PRIM_ENC_CSN_ID
,HSP_ACCT_DX_LIST.DX_ID
,HSP_ACCT_DX_LIST.LINE
,CLARITY_EDG.DX_NAME
,CLARITY_EDG.CURRENT_ICD10_LIST
,HSP_ACCOUNT.ADM_DATE_TIME
FROM HSP_ACCT_DX_LIST 
JOIN HSP_ACCOUNT ON HSP_ACCT_DX_LIST.HSP_ACCOUNT_ID = HSP_ACCOUNT.HSP_ACCOUNT_ID
LEFT OUTER JOIN CLARITY_EDG ON HSP_ACCT_DX_LIST.DX_ID = CLARITY_EDG.DX_ID
WHERE 
--HSP_ACCOUNT.PRIM_ENC_CSN_ID = '30152958284' 
HSP_ACCOUNT.ADM_DATE_TIME BETWEEN '01-JAN-2022' AND '31-DEC-2022'
AND

((CLARITY_EDG.CURRENT_ICD10_LIST LIKE '%I60%') 
		   OR (CLARITY_EDG.CURRENT_ICD10_LIST LIKE '%I61%') 
		   OR (CLARITY_EDG.CURRENT_ICD10_LIST LIKE '%I63%')
		   OR (CLARITY_EDG.CURRENT_ICD10_LIST LIKE '%I21%')
		   OR (CLARITY_EDG.CURRENT_ICD10_LIST LIKE '%I65%'))  
 )
 , ENC_DX AS (
 
  SELECT DISTINCT PATIENT.PAT_MRN_ID,
  PAT_ENC_HSP.PAT_ID, 
			PATIENT.PAT_NAME,
		   PAT_ENC_HSP.PAT_ENC_CSN_ID,
			PAT_ENC_HSP.ADT_ARRIVAL_TIME,
			PAT_ENC_HSP.HOSP_DISCH_TIME,
			EDG_CURRENT_ICD10.CODE,
			CLARITY_EDG.DX_NAME,
		   CLARITY_DEP.DEPARTMENT_NAME
		   --STENT.DESCRIPTION
		   --,STENT.ORDERING_DATE
		   --,Round ((PAT_ENC_HSP.ADT_ARRIVAL_TIME - STENT.ORDERING_DATE) ) Days
		
    
    	FROM PAT_ENC_HSP
			INNER JOIN PATIENT ON PAT_ENC_HSP.PAT_ID = PATIENT.PAT_ID
			LEFT OUTER JOIN CLARITY_DEP ON PAT_ENC_HSP.DEPARTMENT_ID=CLARITY_DEP.DEPARTMENT_ID
			LEFT OUTER JOIN PAT_ENC_DX ON PAT_ENC_HSP.PAT_ENC_CSN_ID = PAT_ENC_DX.PAT_ENC_CSN_ID
			INNER JOIN EDG_CURRENT_ICD10 ON PAT_ENC_DX.DX_ID = EDG_CURRENT_ICD10.DX_ID
			INNER JOIN CLARITY_EDG ON EDG_CURRENT_ICD10.DX_ID = CLARITY_EDG.DX_ID
  Where
		   ((EDG_CURRENT_ICD10.CODE LIKE '%I60%') 
		   OR (EDG_CURRENT_ICD10.CODE LIKE '%I61%') 
		   OR (EDG_CURRENT_ICD10.CODE LIKE '%I63%')
		   OR (EDG_CURRENT_ICD10.CODE LIKE '%I21%')
		    OR (CLARITY_EDG.CURRENT_ICD10_LIST LIKE '%I65%')
		   ) 		   
		 AND PAT_ENC_HSP.ADT_ARRIVAL_TIME BETWEEN '01-JAN-2022' AND '31-DEC-2022'  
)
,STENT AS (
SELECT  
ORDER_PROC.ORDER_PROC_ID
,ORDER_PROC.PAT_ENC_CSN_ID
,ORDER_PROC.PAT_ID
,ORDER_PROC.ORDERING_DATE
,ORDER_PROC_DETAILS.PROC_AS_ORDERED ORDER_PROCEDURE
,OR_PROC.PROC_NAME PEFROMED_PROC

,PAT_MRN_ID
,PAT_NAME
--,DEATH_DATE 
--,Round ((PATIENT.DEATH_DATE -ORDERING_DATE) ) DiffDAte



FROM ORDER_PROC ORDER_PROC
left join ORDER_PROC_DETAILS on ORDER_PROC.ORDER_PROC_ID=ORDER_PROC_DETAILS.ORDER_ID
left join  OR_CASE_ORDER_IDS on ORDER_PROC_DETAILS.ORDER_ID=OR_CASE_ORDER_IDS.ORDER_ID
left join OR_CASE_ALL_PROC on OR_CASE_ORDER_IDS.CASE_ID=OR_CASE_ALL_PROC.OR_CASE_ID
left join OR_PROC on OR_CASE_ALL_PROC.OR_PROC_ID=OR_PROC.OR_PROC_ID
JOIN PATIENT ON  ORDER_PROC.PAT_ID = PATIENT.PAT_ID
WHERE PROC_PREFCARD_ID = '192'
AND ORDERING_DATE BETWEEN '01-JAN-2022' AND '31-DEC-2022'
AND PATIENT.DEATH_DATE IS NULL
)


SELECT
distinct 
STENT.PAT_ID
,STENT.PAT_MRN_ID
,STENT.PAT_NAME
,STENT.ORDERING_DATE
,STENT.ORDER_PROCEDURE ORDERED_PROC_NAME
,STENT.PEFROMED_PROC PERFORMED_PROC_NAME
,ENC_DX.ADT_ARRIVAL_TIME
,ENC_DX.HOSP_DISCH_TIME
,ENC_DX.CODE ENC_DX_CODE
,ENC_DX.DX_NAME ENC_DX_NAME
,ACCT_DX.DX_ID
,ACCT_DX.LINE
,ACCT_DX.CURRENT_ICD10_LIST ACCT_DX_CODE
,ACCT_DX.DX_NAME ACCT_DX_NAME

,ACCT_DX.ADM_DATE_TIME
,Round ((ENC_DX.ADT_ARRIVAL_TIME - STENT.ORDERING_DATE) ) ENC_DX_Diff_Days
,Round ((ACCT_DX.ADM_DATE_TIME - STENT.ORDERING_DATE) ) ACCT_DX_Diff_Days

FROM STENT
LEFT OUTER JOIN ENC_DX ON  STENT.PAT_ID = ENC_DX.PAT_ID AND (STENT.ORDERING_DATE < ENC_DX.ADT_ARRIVAL_TIME) 
LEFT OUTER JOIN ACCT_DX ON STENT.PAT_ID = ACCT_DX.PAT_ID AND (STENT.ORDERING_DATE < ACCT_DX.ADM_DATE_TIME)


