WITH SUPPLY_LIST as (SELECT CAST( Implant.IMP_INV_TYPE_ID AS varchar(18) ) SUPPLYID,
       CAST( Implant.Used AS integer ) NUMBERUSED,
       CAST( Implant.Chargeable AS integer ) ImplantFlag,
       COST_PER_UNIT
  FROM OR_LOG
    LEFT JOIN OR_CASE
      ON OR_LOG.CASE_ID = OR_CASE.OR_CASE_ID and OR_LOG.SURGERY_DATE between   '01-JAN-2021' and  '28-FEB-2023' 
    INNER JOIN ( SELECT OR_LOG_LN_IMPLANT.LOG_ID,
                        OR_LNLG_IMPLANTS.IMP_INV_TYPE_ID,
                        OR_IMP.SITE_ID,
                        MAX ( CASE WHEN OR_IMP.CHARGEABLE_YN = 'Y' THEN 1
                                   WHEN OR_IMP.CHARGEABLE_YN = 'N' THEN 0
                                   ELSE NULL END ) Chargeable,
                        SUM ( OR_IMP.COST_PER_UNIT * ( CASE WHEN OR_LNLG_IMPLANTS.IMPLANT_USAGE_C IS NOT NULL THEN OR_LNLG_IMPLANTS.IMPLANT_NUM_USED 
                                                            ELSE 0 END ) ) TotalCost,
                        SUM ( CASE WHEN OR_LNLG_IMPLANTS.IMPLANT_USAGE_C = 1
                                     AND OR_LNLG_IMPLANTS.IMPLANT_NUM_USED IS NOT NULL THEN OR_LNLG_IMPLANTS.IMPLANT_NUM_USED
                                   ELSE 0 END ) Used,
                        SUM( CASE WHEN OR_LNLG_IMPLANTS.IMPLANT_USAGE_C = 2
                                    AND OR_LNLG_IMPLANTS.IMPLANT_NUM_USED IS NOT NULL THEN OR_LNLG_IMPLANTS.IMPLANT_NUM_USED
                                  ELSE 0 END ) Wasted,
                                  OR_IMP.COST_PER_UNIT COST_PER_UNIT
                   FROM OR_LOG_LN_IMPLANT
                     INNER JOIN OR_LNLG_IMPLANTS
                       ON OR_LOG_LN_IMPLANT.IMPLANTS_ID = OR_LNLG_IMPLANTS.RECORD_ID
                     INNER JOIN OR_IMP
                       ON OR_LNLG_IMPLANTS.IMPLANT_ID = OR_IMP.IMPLANT_ID
                   WHERE OR_LNLG_IMPLANTS.IMPLANT_USAGE_C IS NOT NULL 
                     AND OR_LNLG_IMPLANTS.IMP_INV_TYPE_ID IS NOT NULL
                   GROUP BY OR_LOG_LN_IMPLANT.LOG_ID, OR_LNLG_IMPLANTS.IMP_INV_TYPE_ID, OR_IMP.SITE_ID,COST_PER_UNIT ) Implant
      ON OR_LOG.LOG_ID = Implant.LOG_ID
    LEFT OUTER JOIN ( SELECT OR_PKLST.CASE_ID,
                        OR_PKLST_SUP_LIST.SUPPLY_ID,
                        OR_PKLST_SUP_LIST.SUPPLY_INV_LOC_ID,
                        SUM( OR_PKLST_SUP_LIST.NUM_NEEDED_OPEN ) Opened,
                        SUM( OR_PKLST_SUP_LIST.NUM_SUPPLIES_PRN ) Prn
                   FROM OR_PKLST
                     INNER JOIN OR_LOG
                       ON OR_PKLST.LOG_ID = OR_LOG.LOG_ID
                     INNER JOIN OR_PKLST_SUP_LIST
                       ON OR_PKLST.PICK_LIST_ID = OR_PKLST_SUP_LIST.PICK_LIST_ID
                   WHERE NULLIF( OR_PKLST.PICK_LIST_TYPE_C, 99 ) IS NOT NULL
                     AND NULLIF( OR_PKLST.DELETED_YN, 'N' ) IS NULL
                   GROUP BY OR_PKLST.CASE_ID, OR_PKLST_SUP_LIST.SUPPLY_ID, OR_PKLST_SUP_LIST.SUPPLY_INV_LOC_ID ) Supply
      ON OR_LOG.CASE_ID = Supply.CASE_ID
        AND NVL(Implant.IMP_INV_TYPE_ID, -1) = NVL(Supply.SUPPLY_ID, -1)
        AND NVL(Implant.SITE_ID, -1) = NVL(Supply.SUPPLY_INV_LOC_ID, -1)
    LEFT OUTER JOIN ( SELECT PAT_OR_ADM_LINK.LOG_ID,
                             MIN( PAT_OR_ADM_LINK.OR_LINK_CSN ) OR_LINK_CSN,
                             MIN( PAT_OR_ADM_LINK.PAT_ENC_CSN_ID ) PAT_ENC_CSN_ID
                        FROM PAT_OR_ADM_LINK
                        GROUP BY PAT_OR_ADM_LINK.LOG_ID ) HospitalEncounterLink
      ON OR_LOG.LOG_ID = HospitalEncounterLink.LOG_ID
    LEFT OUTER JOIN OR_LOG_VIRTUAL
      ON OR_LOG.LOG_ID = OR_LOG_VIRTUAL.LOG_ID
    LEFT OUTER JOIN ZC_OR_SERVICE
      ON OR_LOG.SERVICE_C = ZC_OR_SERVICE.SERVICE_C
  WHERE OR_LOG.STATUS_C = 2
    AND ( OR_LOG_VIRTUAL.LOG_EXCLUSION_REASON_C <> 2 OR OR_LOG_VIRTUAL.LOG_EXCLUSION_REASON_C IS NULL )

	UNION ALL
	SELECT 
       CAST( OR_IMP.IMPLANT_ID AS varchar(18) ) SUPPLYID,
       CASE WHEN OR_LNLG_IMPLANTS.IMPLANT_USAGE_C = 1 
              AND OR_LNLG_IMPLANTS.IMPLANT_NUM_USED IS NOT NULL THEN OR_LNLG_IMPLANTS.IMPLANT_NUM_USED
            ELSE 0 END NUMBERUSED,
    
       CASE WHEN OR_IMP.CHARGEABLE_YN = 'Y' THEN 1
            WHEN OR_IMP.CHARGEABLE_YN = 'N' THEN 0
            ELSE NULL END ImplantFlag,
            OR_IMP.COST_PER_UNIT
  FROM OR_LOG
    LEFT  JOIN OR_CASE
      ON OR_LOG.CASE_ID = OR_CASE.OR_CASE_ID and OR_LOG.SURGERY_DATE between   '01-JAN-2021' and  '28-FEB-2023' 
    INNER JOIN OR_LOG_LN_IMPLANT
      ON OR_LOG_LN_IMPLANT.LOG_ID = OR_LOG.LOG_ID
    INNER JOIN OR_LNLG_IMPLANTS
      ON OR_LOG_LN_IMPLANT.IMPLANTS_ID = OR_LNLG_IMPLANTS.RECORD_ID
    INNER JOIN OR_IMP
      ON OR_LNLG_IMPLANTS.IMPLANT_ID = OR_IMP.IMPLANT_ID
    LEFT OUTER JOIN ( SELECT PAT_OR_ADM_LINK.LOG_ID,
                             MIN( PAT_OR_ADM_LINK.OR_LINK_CSN ) OR_LINK_CSN,
                             MIN( PAT_OR_ADM_LINK.PAT_ENC_CSN_ID ) PAT_ENC_CSN_ID
                        FROM PAT_OR_ADM_LINK
         
                        GROUP BY PAT_OR_ADM_LINK.LOG_ID ) HospitalEncounterLink
      ON OR_LOG.LOG_ID = HospitalEncounterLink.LOG_ID
    LEFT OUTER JOIN OR_LOG_VIRTUAL
      ON OR_LOG.LOG_ID = OR_LOG_VIRTUAL.LOG_ID
    LEFT OUTER JOIN ZC_OR_SERVICE
      ON OR_LOG.SERVICE_C = ZC_OR_SERVICE.SERVICE_C
  WHERE OR_LOG.STATUS_C = 2
    AND OR_IMP.INVENTORY_ITEM_ID IS NULL
    AND OR_LNLG_IMPLANTS.IMPLANT_USAGE_C IS NOT NULL
    AND OR_LNLG_IMPLANTS.IMP_TRAY_ID IS NULL
    AND ( OR_LOG_VIRTUAL.LOG_EXCLUSION_REASON_C <> 2 OR OR_LOG_VIRTUAL.LOG_EXCLUSION_REASON_C IS NULL )
 
 UNION ALL

SELECT
 CAST( Supply.SUPPLY_ID AS varchar(18) ) SUPPLYID,
       CAST( Supply.Used AS integer ) NUMBERUSED,
       CAST( CASE WHEN Supply.Chargeable = 'Y' THEN 1
                  WHEN Supply.Chargeable = 'N' THEN 0
           ELSE NULL END AS integer ) ImplantFlag,
         COST_PER_UNIT
  FROM OR_LOG
    LEFT  JOIN OR_CASE
      ON OR_LOG.CASE_ID = OR_CASE.OR_CASE_ID and OR_LOG.SURGERY_DATE between   '01-JAN-2021' and  '28-FEB-2023' 
    INNER JOIN ( SELECT OR_PKLST.CASE_ID,
                        OR_PKLST_SUP_LIST.SUPPLY_ID,
                        OR_PKLST_SUP_LIST.SUPPLY_INV_LOC_ID,
                        SUM( OR_PKLST_SUP_LIST.SUPPLIES_USED ) Used,
                        SUM( OR_PKLST_SUP_LIST.SUPPLIES_WASTED ) Wasted,
                        SUM( OR_PKLST_SUP_LIST.NUM_NEEDED_OPEN ) Opened,
                        SUM( OR_PKLST_SUP_LIST.NUM_SUPPLIES_PRN ) Prn,
                        MIN( OR_PKLST_SUP_LIST.SUP_UNIT_COST ) COST_PER_UNIT,
                        MIN( OR_PKLST_SUP_LIST.CHARGEABLE_YN ) Chargeable
                   FROM OR_PKLST
                     INNER JOIN OR_LOG
                       ON OR_PKLST.LOG_ID = OR_LOG.LOG_ID
                     INNER JOIN OR_PKLST_SUP_LIST
                       ON OR_PKLST.PICK_LIST_ID = OR_PKLST_SUP_LIST.PICK_LIST_ID
                   WHERE NULLIF( NULLIF( OR_PKLST_SUP_LIST.IMPLANT_YN, '' ), 'N' ) IS NULL
                     AND NULLIF( OR_PKLST.PICK_LIST_TYPE_C, 99 ) IS NOT NULL
                     AND NULLIF( OR_PKLST.DELETED_YN, 'N' ) IS NULL
                   
                   GROUP BY OR_PKLST.CASE_ID, OR_PKLST_SUP_LIST.SUPPLY_ID, OR_PKLST_SUP_LIST.SUPPLY_INV_LOC_ID ) Supply
      ON OR_LOG.CASE_ID = Supply.CASE_ID
    LEFT OUTER JOIN ( SELECT PAT_OR_ADM_LINK.LOG_ID,
                             MIN( PAT_OR_ADM_LINK.OR_LINK_CSN ) OR_LINK_CSN,
                             MIN( PAT_OR_ADM_LINK.PAT_ENC_CSN_ID ) PAT_ENC_CSN_ID
                        FROM PAT_OR_ADM_LINK
                    
                        GROUP BY PAT_OR_ADM_LINK.LOG_ID ) HospitalEncounterLink
      ON OR_LOG.LOG_ID = HospitalEncounterLink.LOG_ID
    LEFT OUTER JOIN OR_LOG_VIRTUAL
      ON OR_LOG.LOG_ID = OR_LOG_VIRTUAL.LOG_ID
    LEFT OUTER JOIN ZC_OR_SERVICE
      ON OR_LOG.SERVICE_C = ZC_OR_SERVICE.SERVICE_C
  WHERE OR_LOG.STATUS_C = 2
    AND ( OR_LOG_VIRTUAL.LOG_EXCLUSION_REASON_C <> 2 OR OR_LOG_VIRTUAL.LOG_EXCLUSION_REASON_C IS NULL )
    
 ) 
 
 

 Select  SUPPLY_LIST.SUPPLYID,
   SUM(SUPPLY_LIST.NUMBERUSED) USED,
   OR_SPLY.SUPPLY_NAME,
   OR_SPLY.PRIMARY_EXT_ID,
   ZC_OR_MANUFACTURER.NAME MANUFACTURERNAME,
   OR_SPLY_MANFACTR.MAN_CTLG_NUM MANUFACTURERPARTNUMBER ,
SUPPLY_LIST.ImplantFlag,
COST_PER_UNIT
 from 
 
 SUPPLY_LIST
  JOIN
      (
         SELECT DISTINCT
            OR_SPLY.SUPPLY_ID,
            OR_SPLY.SUPPLY_NAME ,
            OR_SPLY.PRIMARY_EXT_ID
            
         FROM
            OR_SPLY
      )
      OR_SPLY 
      ON OR_SPLY.SUPPLY_ID = SUPPLY_LIST.SUPPLYID 
       LEFT OUTER JOIN
      OR_SPLY_MANFACTR 
      ON SUPPLY_LIST.SUPPLYID = OR_SPLY_MANFACTR.ITEM_ID 
      AND OR_SPLY_MANFACTR.LINE = 1 
   LEFT OUTER JOIN
      ZC_OR_MANUFACTURER 
      ON OR_SPLY_MANFACTR.MANUFACTURER_C = ZC_OR_MANUFACTURER.MANUFACTURER_C 
    
      group by SUPPLY_LIST.SUPPLYID,
   OR_SPLY.SUPPLY_NAME,
   OR_SPLY.PRIMARY_EXT_ID,
   ZC_OR_MANUFACTURER.NAME ,
   OR_SPLY_MANFACTR.MAN_CTLG_NUM  ,
SUPPLY_LIST.ImplantFlag,COST_PER_UNIT
  having  SUM(SUPPLY_LIST.NUMBERUSED)>0
order by 2 desc
 
    
