SELECT * -------DISTINCT

--sfi.DEPT_TARGET_ID  "DEPARTMENT_ID"
----,dat.CALENDAR_DT
--,dd.DAY_DT    "SOURCE_DT"
--,dd.VALUE_DAY  "PATDAYS_NUM"
--,0 AS "DAY_OF_THERAPY_IV"
--,0 AS "DAY_OF_THERAPY_IM"
--,0 AS "DAY_OF_THERAPY_DIGESTIVE"
--,0 AS "DAY_OF_THERAPY_RESPIRATORY"
--,0 AS "MEDICATION_ID"
--,0 AS "ORDER_ID"
--,'A' AS "MYGROUP"

FROM METRIC_INFO mi
INNER JOIN SUM_FACTS_INFO sfi ON mi.DEFINITION_ID = sfi.DEFINITION_ID
INNER JOIN daily_Data dd ON sfi.SUM_FACTS_ID = dd.SUM_FACTS_ID
--left outer join NHSN nhsn on sfi.DEPT_TARGET_ID = nhsn.DEPARTMENT_ID
--LEFT OUTER JOIN FILLDAT dat ON dd.DAY_DT = dat.CALENDAR_DT


WHERE
dd.DAY_DT >= '1-apr-2021'
--dd.DAY_DT >= dat.CALENDAR_DT 
--and dd.DAY_DT <= dat.CALENDAR_DT 
AND mi.DEFINITION_ID =11073
AND sfi.DEPT_TARGET_ID IS NOT NULL
and sfi.DEPT_TARGET_ID = 1000108008



SELECT 

fdot.DEPARTMENT_ID  "DEPARTMENT_ID"
--,dat.CALENDAR_DT
,fdot.TAKEN_DATE     "SOURCE_DT"
,0 as  "PATDAYS_NUM"
,fdot.DAY_OF_THERAPY_IV
,fdot.DAY_OF_THERAPY_IM
,fdot.DAY_OF_THERAPY_DIGESTIVE
,fdot.DAY_OF_THERAPY_RESPIRATORY
,fdot.MEDICATION_ID
,fdot.ORDER_ID
,'B' AS "MYGROUP"

FROM CLARITY_ADT adt
INNER JOIN order_med om ON adt.PAT_ENC_CSN_ID = om.PAT_ENC_CSN_ID
INNER JOIN F_DOT_CONTRIB_ORDS_DEPT fdot ON om.ORDER_MED_ID = fdot.ORDER_ID
--INNER JOIN  ANTIB anti on fdot.medication_id = anti.MEDICATION_ID
--LEFT OUTER JOIN FILLDAT dat ON fdot.TAKEN_DATE = dat.CALENDAR_DT
LEFT OUTER JOIN clarity_dep dep ON fdot.DEPARTMENT_ID = dep.DEPARTMENT_ID
INNER JOIN patient pat ON fdot.PAT_ID = pat.PAT_ID
INNER JOIN patient_3 pat3 ON pat.PAT_ID = pat3.PAT_ID

WHERE
adt.EVENT_SUBTYPE_C <> 2  ---- deleted
AND adt.EVENT_TYPE_C IN (1,3)
--AND TRUNC( fdot.TAKEN_DATE) >= '1-jan-2021' 
--AND TRUNC( fdot.TAKEN_DATE) <= '31-jan-2021' 
--AND fdot.TAKEN_DATE >= dat.CALENDAR_DT 
--AND fdot.TAKEN_DATE <= dat.CALENDAR_DT
AND pat3.IS_TEST_PAT_YN <> 'Y'
AND fdot.ORDER_ID = 602745335
--AND fdot.DEPARTMENT_ID = 1000108008
602,745,335

