WITH DEPARTMENT_LIST
AS 
	(SELECT
	  		dep.DEPARTMENT_ID
	  		,dep.DEPARTMENT_NAME
	  		,dep.DEPT_ABBREVIATION
	  		,CASE 
	  					WHEN dep.DEPARTMENT_ID IN (1000102015,1000102025,1000102026,1000102027,1000102028,1000102029,1000102033,1000102035,1000102036,1000102038,1000102044,1000102045,1000116045) THEN 1 
	  					 WHEN dep.DEPARTMENT_ID IN (1000102022, 1000102031) THEN 2
	  					 WHEN dep.DEPARTMENT_ID IN (1000102023,1000102030) THEN 3 END "DEP_LVL_OF_CARE"

	  FROM
	  		CLARITY_DEP dep
	  
	  WHERE
	  		dep.DEPARTMENT_ID IN (1000102015,1000102025,1000102026,1000102027,1000102028,1000102029,1000102033,1000102035,1000102036
	  															,1000102038,1000102044,1000102045,1000116045,1000102023,1000102022,1000102030,1000102031))
,LVL_OF_CARE_META
AS
	(SELECT
		hsp.INP_ADM_DATE "ADMIT_DATE"
		,hsp.HOSP_DISCH_TIME "DISCH_DATE"
		,pat.PAT_MRN_ID
		,hsp.HSP_ACCOUNT_ID
		,admserv.NAME "ADMIT_MD_SERVICE"
		,dcserv.NAME "DISCH_MD_SERVICE"
		,adms.NAME "ADMIT_ORIGIN"
		,depout.DEPARTMENT_NAME "TRANSFER_FROM_DEP"
		,CASE WHEN adtout.PAT_LVL_OF_CARE_C = 6 THEN depout.DEP_LVL_OF_CARE + 2
					 WHEN adtout.PAT_LVL_OF_CARE_C = 13 THEN depout.DEP_LVL_OF_CARE + 1 
					 ELSE depout.DEP_LVL_OF_CARE END "FROM_DEP_LVL"
		,adtout.EFFECTIVE_TIME "FROM_EFFECTIVE_DTTM"
		,depin.DEPARTMENT_NAME "TRANSFER_TO_DEP"
		,CASE WHEN adtin.PAT_LVL_OF_CARE_C = 6 THEN depin.DEP_LVL_OF_CARE + 2
					 WHEN adtin.PAT_LVL_OF_CARE_C = 13 THEN depin.DEP_LVL_OF_CARE + 1 
					 ELSE depin.DEP_LVL_OF_CARE END "TO_DEP_LVL"
		,adtin.EFFECTIVE_TIME "TO_EFFECTIVE_DTTM"
		,CASE WHEN extract(HOUR FROM CAST(adtout.EFFECTIVE_TIME AS TIMESTAMP)) BETWEEN 6 AND 20 THEN 1  ELSE NULL END "0600_2000"
		,CASE WHEN extract(HOUR FROM CAST(adtout.EFFECTIVE_TIME AS TIMESTAMP)) BETWEEN 0 AND 8 OR extract(HOUR FROM CAST(adtout.EFFECTIVE_TIME AS TIMESTAMP))  BETWEEN 18 AND 23 THEN 1 ELSE NULL END "1800_0600"
		,TRUNC(adtout.EFFECTIVE_TIME)  "CENSUS_DATE"
		,row_number() OVER (PARTITION BY adtout.PAT_ENC_CSN_ID ORDER BY adtout.EFFECTIVE_TIME ASC) "SEQ_NUM"
		,adtout.EVENT_ID
		,adtout.PAT_ID
		
	FROM
		CLARITY_ADT adtout
		INNER JOIN PAT_ENC_HSP hsp ON adtout.PAT_ENC_CSN_ID = hsp.PAT_ENC_CSN_ID
			LEFT JOIN ZC_ADM_SOURCE adms ON hsp.ADMIT_SOURCE_C = adms.ADMIT_SOURCE_C
			LEFT JOIN CLARITY_SER_2 admit ON hsp.ADMISSION_PROV_ID = admit.PROV_ID
				LEFT JOIN ZC_PAT_SERVICE admserv ON admit.SERVICE_DEFAULT_C = admserv.HOSP_SERV_C
			LEFT JOIN CLARITY_SER_2 disch ON hsp.BILL_ATTEND_PROV_ID = disch.PROV_ID
				LEFT JOIN ZC_PAT_SERVICE dcserv ON admit.SERVICE_DEFAULT_C = dcserv.HOSP_SERV_C
		INNER JOIN PATIENT pat ON adtout.PAT_ID = pat.PAT_ID
		INNER JOIN CLARITY_ADT adtin ON adtout.XFER_IN_EVENT_ID = adtin.EVENT_ID
		INNER JOIN DEPARTMENT_LIST depout ON adtout.DEPARTMENT_ID = depout.DEPARTMENT_ID
 		INNER JOIN DEPARTMENT_LIST depin ON adtin.DEPARTMENT_ID = depin.DEPARTMENT_ID
			
	
	WHERE
		adtout.EFFECTIVE_TIME BETWEEN to_date('2015-01-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') AND to_date('2015-06-22 23:59:59', 'yyyy-mm-dd hh24:mi:ss')
		AND adtout.EVENT_TYPE_C = 4
		AND adtout.EVENT_SUBTYPE_C <> 2
		AND EXISTS(SELECT
										1
								  FROM
								  		CLARITY_ADT adt2
								  WHERE
								  		adtout.PAT_ENC_CSN_ID = adt2.PAT_ENC_CSN_ID AND adt2.EVENT_TYPE_C = 2)
		
	ORDER BY
		"PAT_MRN_ID"
		,"FROM_EFFECTIVE_DTTM")

,DEPARTMENT_CENSUS
AS
	(SELECT
			*
	FROM
		(SELECT
		  		adt.EVENT_ID 
		  		,TRUNC(ADT.EFFECTIVE_TIME) "CENSUS_DATE"
		  		,adt.DEPARTMENT_ID
		  					 
		  FROM
		  		CLARITY_ADT adt
		  		
		  WHERE
	  		EXISTS(SELECT
	  							 1
	  					   FROM
	  					   		 LVL_OF_CARE_META lvl
	  					   	WHERE
	  					   			TRUNC(adt.EFFECTIVE_TIME) = lvl.CENSUS_DATE)		  		
	  			AND adt.DEPARTMENT_ID IN (1000102023, 1000102030, 1000102022)
		  		AND adt.EVENT_TYPE_C = 6
		  		AND adt.PAT_ID IS NOT NULL
				AND adt.EVENT_SUBTYPE_C <> 2) SOURCE_PIVOT
		  		
		  	PIVOT
		  	(count("EVENT_ID") 
		  	FOR "DEPARTMENT_ID" IN (1000102023 "PICU", 1000102030 "NICU", 1000102022 "PIMC")) CENSUS_PIVOT)

,BOUNCE_BACK
AS
	(SELECT
	  		BOUNCE.*
	  FROM
		(SELECT
		  		meta.HSP_ACCOUNT_ID
		  		,meta.FROM_EFFECTIVE_DTTM 
		  		,meta24.FROM_EFFECTIVE_DTTM "24_DTTM"
		  		,meta24.EVENT_ID
		  		,ROUND(24*(to_date(to_char(meta.FROM_EFFECTIVE_DTTM, 'yyyy-mm-dd hh24:mi'),'yyyy-mm-dd hh24:mi') - to_date(to_char(meta24.FROM_EFFECTIVE_DTTM, 'yyyy-mm-dd hh24:mi'),'yyyy-mm-dd hh24:mi')),0)  "FLAG"
		  		
		  FROM
		  		LVL_OF_CARE_META meta
		  		INNER JOIN LVL_OF_CARE_META meta24 ON meta.HSP_ACCOUNT_ID = meta24.HSP_ACCOUNT_ID
		  		
		  WHERE
		  meta.EVENT_ID < meta24.EVENT_ID
		  AND meta.FROM_EFFECTIVE_DTTM <> meta24.FROM_EFFECTIVE_DTTM
		  AND meta.TO_DEP_LVL > meta.FROM_DEP_LVL
		  AND meta24.TO_DEP_LVL > meta24.FROM_DEP_LVL) BOUNCE
	 WHERE
	 		BOUNCE.FLAG BETWEEN -24 AND 0)

,ED_24_HOUR_VISIT
AS 		
	(SELECT
	  		ROUND(24*(to_date(to_char(meta.FROM_EFFECTIVE_DTTM, 'yyyy-mm-dd hh24:mi'),'yyyy-mm-dd hh24:mi') - to_date(to_char(ED_EVENT.IEV_DTTM, 'yyyy-mm-dd hh24:mi'),'yyyy-mm-dd hh24:mi')),0) "FLAG"
	  		,meta.EVENT_ID
	  		,meta.FROM_EFFECTIVE_DTTM
	  		,ED_EVENT.IEV_DTTM
	  FROM
		  (SELECT
		  		max(ievpat.CREATE_DTTM) "IEV_DTTM"
		  		,ievpat.PAT_ID
		  		
		  FROM
		  		ED_IEV_PAT_INFO ievpat
	  	
	  	  WHERE 
	  				ievpat.TYPE_ID = 50
	  		
	  		GROUP BY
	  				ievpat.PAT_ID) ED_EVENT
	  				INNER JOIN LVL_OF_CARE_META meta ON ED_EVENT.PAT_ID = meta.PAT_ID AND meta.TO_DEP_LVL > meta.FROM_DEP_LVL)
			
SELECT
	meta.ADMIT_DATE
	,meta.DISCH_DATE
	,meta.PAT_MRN_ID
	,meta.HSP_ACCOUNT_ID
	,meta.ADMIT_MD_SERVICE
	,meta.DISCH_MD_SERVICE
	,meta.ADMIT_ORIGIN
	,meta.TRANSFER_FROM_DEP
	,meta.FROM_EFFECTIVE_DTTM
	,meta.TRANSFER_TO_DEP
	,meta.TO_EFFECTIVE_DTTM
	,CASE WHEN bounce.EVENT_ID IS NOT NULL THEN 1 ELSE NULL END "BOUNCE_BACK"
	,CASE WHEN edvisit.EVENT_ID IS NOT NULL THEN 1 ELSE NULL END "ED_24HOURS"
	,meta."0600_2000"
	,meta."1800_0600"
	,cens.PICU
	,cens.NICU
	,cens.PIMC
	
FROM
	LVL_OF_CARE_META meta
		LEFT JOIN DEPARTMENT_CENSUS cens ON meta.CENSUS_DATE = cens.CENSUS_DATE
		LEFT JOIN BOUNCE_BACK bounce ON meta.EVENT_ID = bounce.EVENT_ID
		LEFT JOIN ED_24_HOUR_VISIT edvisit ON meta.EVENT_ID = edvisit.EVENT_ID AND edvisit.FLAG BETWEEN 0 AND 24
		
WHERE
	TO_DEP_LVL > FROM_DEP_LVL
